Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2023-02, with the labels that each got.

#1783 Update Active Countries to be a non-required field in both Registration (added as new field) and in Update profile
  src/components/ActivityCountries.tsx
  src/components/Selector.tsx
  src/pages/Admin/Charity/EditProfile/ActivityCountries.tsx
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Registration/Steps/Documentation/Form/index.tsx
  src/pages/Registration/Steps/Documentation/Form/useSubmit.ts
  src/pages/Registration/Steps/Documentation/index.tsx
  src/pages/Registration/Steps/Documentation/schema.ts
  src/pages/Registration/Steps/Documentation/types.ts
  src/pages/Registration/Steps/getRegistrationState.ts
  src/pages/Registration/types.ts
  src/schemas/string.ts
  src/types/aws/ap/registration.ts
Labels: enhancement

#1785 Active in should show HQ Country if empty
  src/pages/Marketplace/Cards/Card.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/Details.tsx
Labels: enhancement

#1784 Require HQ Country in Registration flow
  src/pages/Registration/Steps/Documentation/Form/index.tsx
  src/pages/Registration/Steps/Documentation/Form/useSubmit.ts
  src/pages/Registration/Steps/Documentation/index.tsx
  src/pages/Registration/Steps/Documentation/schema.ts
  src/pages/Registration/Steps/Documentation/types.ts
  src/pages/Registration/Steps/getRegistrationState.ts
  src/pages/Registration/types.ts
  src/types/aws/ap/registration.ts
Labels: enhancement

#1790 RC-v1.7.1: fix overlooked errors (type and lint) from #1738
  src/pages/Registration/Steps/Documentation/Form/index.tsx
  src/pages/Registration/Steps/Documentation/Form/useSubmit.ts
  src/pages/Registration/Steps/Documentation/index.tsx
  src/pages/Registration/Steps/Documentation/schema.ts
  src/pages/Registration/Steps/Documentation/types.ts
  src/pages/Registration/Steps/getRegistrationState.ts
  src/pages/Registration/types.ts
Labels: bug

#1788 add proper length check to tagline (required & <= 140 chars)
  src/pages/Admin/Charity/EditProfile/schema.ts
Labels: bug

#1794 Added a `limit` param for `useEndowmentCardsQuery()`
  src/pages/Marketplace/Cards/useCards.ts
  src/types/aws/ap/index.ts
Labels: enhancement

#1798 RC-v1.7.1: cherry pick: update test file types
  src/pages/Admin/Review/Applications/__tests__/Applications.test.tsx
Labels: bug

#1795 Header/Footer components refactored to be able to generate custom links based on externally defined objects/lists
  src/App/Footer/Footer.tsx
  src/App/Footer/Links.tsx
  src/App/Footer/Socials.tsx
  src/App/Header/DesktopNav.tsx
  src/App/Header/MobileNav/Menu.tsx
  src/App/Header/MobileNav/Opener.tsx
  src/App/Header/index.tsx
  src/App/Layout.tsx
  src/App/constants.ts
  src/App/types.ts
  src/components/APLogo.tsx
  src/components/Logo.tsx
  src/constants/common.ts
  src/pages/Admin/Charity/WidgetConfigurer/WidgetExample/WidgetExample.tsx
  src/pages/DonateWidget/InnerComponent.tsx
Labels: enhancement

#1781 RC-v1.8: refactor: useScreenResize hook better args name
  src/App/Header/MobileNav/Opener.tsx
  src/hooks/useHandleScreenResize.ts
  src/pages/Registration/Steps/ProgressIndicator.tsx
Labels: enhancement

#1800 Update canius-lite version
  yarn.lock
Labels: dependencies

#1789 RC-v1.8 <-- RC-v1.7.1
  public/index.html
  src/App/Footer/Footer.tsx
  src/App/Footer/Newsletter/Newsletter.tsx
  src/App/__tests__/App.test.tsx
  src/App/constants.ts
  src/assets/images/angelgiving-H-logo-beta-wht.svg
  src/assets/images/angelprotocol-H-logo-beta-wht.svg
  src/assets/images/angelprotocol-beta-horiz-wht.png
  src/assets/images/angelprotocol-beta-horiz-wht.svg
  src/components/ActivityCountries.tsx
  src/components/Selector.tsx
  src/components/Seo.tsx
  src/components/donation/Steps/Result/Success/Share.tsx
  src/constants/chains.ts
  src/constants/common.ts
  src/constants/urls.ts
  src/errors/errors.ts
  src/helpers/registration/handleMutationResult.ts
  src/index.css
  src/pages/Admin/Charity/EditProfile/ActivityCountries.tsx
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Admin/Charity/WidgetConfigurer/createWidgerUrl.ts
  src/pages/Admin/Charity/Withdraws/WithdrawTabs/Withdrawer/Submit.tsx
  src/pages/Admin/Charity/Withdraws/WithdrawTabs/Withdrawer/useLogWithdrawProposal.ts
  src/pages/Admin/Review/Applications/__tests__/Applications.test.tsx
  src/pages/Donate/index.tsx
  src/pages/Gift/Claim/Form.tsx
  src/pages/Gift/Mailer/Form.tsx
  src/pages/Gift/Purchase/Result/Success.tsx
  src/pages/Gift/Purchase/index.tsx
  src/pages/Leaderboard/index.tsx
  src/pages/Marketplace/Cards/Card.tsx
  src/pages/Marketplace/Cards/useCards.ts
  src/pages/Marketplace/Hero.tsx
  src/pages/Profile/Body/Body.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/Details.tsx
  src/pages/Registration/ConfirmEmail.tsx
  src/pages/Registration/Signup/Form.tsx
  src/pages/Registration/Steps/ContactDetails/Form/index.tsx
  src/pages/Registration/Steps/Documentation/Form/index.tsx
  src/pages/Registration/Steps/Documentation/Form/useSubmit.ts
  src/pages/Registration/Steps/Documentation/index.tsx
  src/pages/Registration/Steps/Documentation/schema.ts
  src/pages/Registration/Steps/Documentation/types.ts
  src/pages/Registration/Steps/WalletRegistration/RegisteredWallet.tsx
  src/pages/Registration/Steps/getRegistrationState.ts
  src/pages/Registration/Success.tsx
  src/pages/Registration/VerifiedEmail.tsx
  src/pages/Registration/index.tsx
  src/pages/Registration/types.ts
  src/schemas/string.ts
  src/services/aws/registration/registration.ts
  src/slices/gift/purchase.ts
  src/types/aws/ap/index.ts
  src/types/aws/ap/registration.ts
Labels: duplicate

#1803 Remove widget link
  src/App/Header/MobileNav/Menu/AdminMobileNavPortal.tsx
  src/pages/Admin/Charity/Nav.tsx
Labels: bug

#1809 Fix act country bug v2
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Marketplace/Cards/Card.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/Details.tsx
  src/types/aws/ap/index.ts
Labels: bug

#1805 Last minor fixes v1.7.1
  src/App/Footer/constants.ts
  src/App/Header/DesktopNav.tsx
  src/App/Header/MobileNav/Menu/Links.tsx
  src/App/Header/MobileNav/constants.ts
  src/App/__tests__/App.test.tsx
  src/assets/images/angelgiving-H-logo-beta-wht.svg
  src/assets/images/angelprotocol-H-logo-beta-wht.svg
  src/pages/Admin/Charity/Nav.tsx
Labels: bug

#1810 Address error/suggestion related to PR #1789
  src/pages/Registration/ConfirmEmail.tsx
  src/pages/Registration/Steps/Documentation/Form/useSubmit.ts
Labels: bug

#1818 RC-v1.8 <-- master fixes
  src/assets/images/angelgiving-H-logo-beta-wht.png
  src/constants/common.ts
  src/helpers/admin/getTagPayloads.ts
  src/index.css
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Admin/Charity/Withdraws/WithdrawTabs/index.tsx
  src/pages/Admin/Charity/Withdraws/index.tsx
  src/pages/Marketplace/Cards/Card.tsx
  src/pages/Profile/Body/Body.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/Details.tsx
  src/services/aws/aws.ts
  src/services/juno/account.ts
  src/services/juno/custom.ts
  src/services/juno/queryContract/queryObjects.ts
  src/services/juno/queryContract/types.ts
  src/services/juno/tags.ts
  src/types/aws/ap/index.ts
  src/types/contracts/account.ts
  yarn.lock
Labels: bug, duplicate

#1835 Deps update
  package.json
  yarn.lock
Labels: dependencies

#1838 Sdg selector limit
  src/constants/unsdgs.ts
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Registration/Steps/Documentation/schema.ts
Labels: enhancement, good first issue

#1797 RC-v1.8: query vault balances directly
  src/helpers/admin/getTagPayloads.ts
  src/pages/Admin/Charity/Account/Balances.tsx
  src/pages/Admin/Charity/Account/Positions.tsx
  src/pages/Admin/Charity/Invest/Invesments.tsx
  src/pages/Admin/Charity/Invest/Investor/useSubmit.ts
  src/pages/Admin/Charity/Settings/StrategyEditor/useSubmit.ts
  src/pages/Admin/Charity/common/Balances/Balance.tsx
  src/pages/Admin/Charity/common/Investment/Investor/useSubmit.ts
  src/pages/Admin/Charity/common/Investment/Redeemer/useSubmit.ts
  src/pages/Admin/types.ts
  src/services/juno/account.ts
  src/services/juno/custom/custom.ts
  src/services/juno/custom/helpers/admin-resource.ts
  src/services/juno/custom/helpers/endow-assets.ts
  src/services/juno/custom/index.ts
  src/services/juno/queryContract/queryObjects.ts
  src/services/juno/queryContract/types.ts
  src/services/juno/tags.ts
  src/services/types.ts
Labels: enhancement

#1841 Disable Continue unless agreed to TnC
  src/components/KYC/Form/Controls.tsx
Labels: bug

#1848 Hide intercom at the bottom of the page
  public/index.html
Labels: enhancement

#1851 Display `tokens_on_hand` Balance in Endow Profile Page
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/Balances.tsx
  src/types/aws/ap/index.ts
Labels: bug

#1840 Add transition to backdrop and Dialog
  src/App/Header/Airdrop/Catcher.tsx
  src/App/Header/MobileNav/Menu/index.tsx
  src/components/ImgEditor/ImgCropper.tsx
  src/components/KYC/index.tsx
  src/components/KadoModal.tsx
  src/components/Panel/index.tsx
  src/components/Popup.tsx
  src/components/Prompt/Prompt.tsx
  src/components/WalletSuite/WalletSelectorOpener/WalletModal.tsx
  src/components/donation/Steps/Result/Success/Share.tsx
  src/contexts/ModalContext.tsx
  src/pages/Admin/Proposal/Voter/Form.tsx
  src/pages/Leaderboard/Table/Row/Amount/Summary.tsx
Labels: enhancement

#1804 Move existing Admin pages/components to align with new Sidebar setup
  src/App/Layout.tsx
  src/components/Icon/icons.ts
  src/components/Sidebar/MobileSidebar.tsx
  src/components/Sidebar/createLinkGroupsPlaceholder.ts
  src/components/Sidebar/index.ts
  src/components/Sidebar/useMobileSidebar.ts
  src/constants/common.ts
  src/constants/routes.ts
  src/pages/Admin/Charity/Contributions.tsx
  src/pages/Admin/Charity/Dashboard/index.tsx
  src/pages/Admin/Charity/DonationsTable/DonationsTable.tsx
  src/pages/Admin/Charity/DonationsTable/Table.tsx
  src/pages/Admin/Charity/DonationsTable/index.ts
  src/pages/Admin/Charity/Nav.tsx
  src/pages/Admin/Charity/WidgetConfigurer/WidgetExample/WidgetExample.tsx
  src/pages/Admin/Charity/WidgetConfigurer/WidgetUrlGenerator/EndowmentCombobox/EndowmentCombobox.tsx
  src/pages/Admin/Charity/index.tsx
  src/pages/Admin/Core/Nav.tsx
  src/pages/Admin/Core/index.tsx
  src/pages/Admin/Layout.tsx
  src/pages/Admin/Review/Nav.tsx
  src/pages/Admin/Review/index.tsx
  src/pages/Admin/Sidebar/Header/CharityHeader.tsx
  src/pages/Admin/Sidebar/Header/Header.tsx
  src/pages/Admin/Sidebar/Header/index.ts
  src/pages/Admin/Sidebar/Sidebar.tsx
  src/pages/Admin/Sidebar/SidebarOpener/SidebarOpener.tsx
  src/pages/Admin/Sidebar/SidebarOpener/ToggleableSidebar.tsx
  src/pages/Admin/Sidebar/SidebarOpener/index.ts
  src/pages/Admin/Sidebar/SidebarOpener/useSidebarOpener.ts
  src/pages/Admin/Sidebar/index.ts
  src/pages/Admin/Sidebar/types.ts
  src/pages/Admin/constants.ts
  src/pages/DonateWidget/InnerComponent.tsx
Labels: enhancement

#1847 Admin AP Team - Registrar Config way out of sync with current mainnet contract
  src/constants/contracts.ts
  src/contracts/CW3/CW3Review.ts
  src/pages/Admin/Core/Templates/registrar/Config/Form.tsx
  src/pages/Admin/Core/Templates/registrar/Config/index.tsx
  src/pages/Admin/Core/Templates/registrar/Config/schema.ts
  src/pages/Admin/Core/Templates/registrar/Config/useConfigureRegistrar.ts
  src/services/juno/custom.ts
  src/types/contracts/registrar.ts
Labels: bug, priority

#1853 Rename `Panel -> Modal`, to align with already existing naming convention
  src/App/Header/Airdrop/Catcher.tsx
  src/App/Header/MobileNav/Menu/index.tsx
  src/components/ImgEditor/ImgCropper.tsx
  src/components/KYC/index.tsx
  src/components/KadoModal.tsx
  src/components/Modal.tsx
  src/components/Popup.tsx
  src/components/Prompt/Prompt.tsx
  src/components/WalletSuite/WalletSelectorOpener/WalletModal.tsx
  src/components/donation/Steps/Result/Success/Share.tsx
  src/pages/Admin/Proposal/Voter/Form.tsx
  src/pages/Leaderboard/Table/Row/Amount/Summary.tsx
Labels: enhancement

#1857 Align "My Donations" table styles with new Figma designs
  src/pages/Admin/Charity/Dashboard/Donations/index.tsx
  src/pages/Donations/MobileTable.tsx
  src/pages/Donations/Table.tsx
  src/pages/Donations/index.tsx
  src/services/apes/donations.ts
  src/types/aws/apes/donation.ts
  tailwind.config.js
Labels: enhancement

#1716 Create Sidebar + update admin pages to use it
  src/App/Layout.tsx
  src/components/Icon/icons.ts
  src/components/Logo.tsx
  src/components/Logo/Logo.tsx
  src/components/Logo/LogoPlaceholder.tsx
  src/components/Logo/index.ts
  src/components/LogoPlaceholder.tsx
  src/components/WalletSuite/ConnectedWallet/Details/Favourites/Favourite.tsx
  src/components/WalletSuite/ConnectedWallet/Details/Logo.tsx
  src/components/WalletSuite/ConnectedWallet/Details/MyEndowments/MyEndowments.tsx
  src/constants/common.ts
  src/constants/routes.ts
  src/pages/Admin/Charity/Contributions.tsx
  src/pages/Admin/Charity/Dashboard/index.tsx
  src/pages/Admin/Charity/DonationsTable/DonationsTable.tsx
  src/pages/Admin/Charity/DonationsTable/Table.tsx
  src/pages/Admin/Charity/DonationsTable/index.ts
  src/pages/Admin/Charity/Nav.tsx
  src/pages/Admin/Charity/WidgetConfigurer/WidgetExample/WidgetExample.tsx
  src/pages/Admin/Charity/WidgetConfigurer/WidgetUrlGenerator/EndowmentCombobox/EndowmentCombobox.tsx
  src/pages/Admin/Charity/index.tsx
  src/pages/Admin/Core/Nav.tsx
  src/pages/Admin/Core/index.tsx
  src/pages/Admin/Layout.tsx
  src/pages/Admin/Review/Nav.tsx
  src/pages/Admin/Review/index.tsx
  src/pages/Admin/Sidebar/Header/CharityHeader.tsx
  src/pages/Admin/Sidebar/Header/Header.tsx
  src/pages/Admin/Sidebar/Header/index.ts
  src/pages/Admin/Sidebar/Sidebar.tsx
  src/pages/Admin/Sidebar/SidebarOpener/SidebarOpener.tsx
  src/pages/Admin/Sidebar/SidebarOpener/ToggleableSidebar.tsx
  src/pages/Admin/Sidebar/SidebarOpener/index.ts
  src/pages/Admin/Sidebar/SidebarOpener/useSidebarOpener.ts
  src/pages/Admin/Sidebar/index.ts
  src/pages/Admin/Sidebar/types.ts
  src/pages/Admin/constants.ts
  src/pages/DonateWidget/InnerComponent.tsx
Labels: enhancement

#1869 Revert isPrevDark changes to enable light theme being saved
  src/helpers/theme.ts
Labels: bug

#1860 Hide 'load more' btn on donations table when no items are there to load
  src/pages/Donations/LoadMoreBtn.tsx
  src/pages/Donations/MobileTable.tsx
  src/pages/Donations/Table.tsx
  src/pages/Donations/index.tsx
  src/pages/Donations/types.ts
  src/pages/Donations/useDonations.ts
Labels: enhancement
