Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2023-11, with the labels that each got.

#2455 AP-855: FIX: remove ast case endow designation
  src/pages/Admin/Charity/EditProfile/schema.ts
Labels: bug

#2456 Create reusable `optionType()` schema
  src/components/ActivityCountries.tsx
  src/components/KYC/Form/us-states.ts
  src/components/Selector/MultiSelector.tsx
  src/components/Selector/Selector.tsx
  src/components/Selector/constants.ts
  src/components/Selector/index.ts
  src/components/Selector/types.ts
  src/pages/Admin/Charity/EditProfile/getSDGLabelValuePair.ts
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Admin/Charity/EditProfile/types.ts
  src/pages/Donations/Filter/constants.ts
  src/pages/Donations/Filter/types.ts
  src/pages/Registration/Steps/ContactDetails/constants.ts
  src/pages/Registration/Steps/ContactDetails/index.tsx
  src/pages/Registration/Steps/ContactDetails/schema.ts
  src/pages/Registration/Steps/ContactDetails/types.ts
  src/pages/Registration/Steps/Documentation/schema.ts
  src/pages/Registration/types.ts
  src/schemas/shape.ts
  src/slices/donation/types.ts
  src/types/utils.ts
Labels: refactor

#2439 Towards AP-834: Admin: Banking page posts bank details to AWS endpoint and can show `bank_verified` status on that page
  src/components/Icon/icons.ts
  src/components/Seo.tsx
  src/helpers/admin/flatten.ts
  src/pages/Admin/Charity/Banking/Banking.tsx
  src/pages/Admin/Charity/Banking/CurrencySelector.tsx
  src/pages/Admin/Charity/Banking/RecipientDetails/AccountRequirementsSelector.tsx
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetails.tsx
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetailsForm/Form.tsx
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetailsForm/RequirementField.tsx
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetailsForm/index.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetailsForm/useRecipientDetailsForm/createFieldSchema.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetailsForm/useRecipientDetailsForm/createSchema.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetailsForm/useRecipientDetailsForm/index.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetailsForm/useRecipientDetailsForm/useRecipientDetailsForm.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/dot.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/getDefaultValues.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/index.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/types.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/useRecipientDetails.ts
  src/pages/Admin/Charity/Banking/VerificationStatus.tsx
  src/pages/Admin/Charity/Banking/index.ts
  src/pages/Admin/Charity/Banking/useBanking.ts
  src/pages/Admin/Charity/ProgramEditor/Milestones/Milestone.tsx
  src/pages/Admin/Charity/index.tsx
  src/pages/Admin/constants.ts
  src/pages/Donations/Filter/NetworkDropdown.tsx
  src/schemas/date.ts
  src/services/aws/bankDetails.ts
  src/types/aws/ap/bankDetails.ts
  src/types/aws/ap/index.ts
  src/types/aws/index.ts
Labels: enhancement

#2457 AP-864: Signup T&C text
  src/App/Header/UserMenu/UserMenu.tsx
  src/App/constants.ts
  src/components/Authenticator.tsx
  src/components/KYC/Form/index.tsx
  src/components/KYC/index.tsx
  src/components/KYC/schema.ts
  src/components/donation/Steps/DonateMethods/Stripe.tsx
  src/constants/urls.ts
  src/index.css
  src/pages/Registration/Signup/Form.tsx
  src/pages/Registration/Signup/index.ts
  src/pages/Registration/Signup/index.tsx
  src/pages/Registration/Signup/types.ts
  src/pages/Registration/Signup/useSubmit.ts
  src/pages/Registration/Steps/Documentation/Form/CashEligibleCheckbox.tsx
  src/pages/Registration/Steps/Documentation/Form/index.tsx
  src/pages/Registration/Steps/Documentation/Form/useSubmit.ts
  src/pages/Registration/Steps/Documentation/index.tsx
  src/pages/Registration/Steps/Documentation/schema.ts
  src/pages/Registration/Steps/getRegistrationState.ts
  src/pages/Registration/types.ts
  src/pages/Signin/Signin.tsx
  src/slices/donation/types.ts
Labels: bug, design, refactor

#2465 Small refactor: Move Sidebar/Header/CharityHeader.tsx contents into Sidebar/Header/Header.tsx
  src/pages/Admin/Sidebar/Header/CharityHeader.tsx
  src/pages/Admin/Sidebar/Header/Header.tsx
Labels: refactor

#2446 Closes AP-834, AP-872: Admin bank page UI
  src/components/CountrySelector/index.tsx
  src/components/Divider.tsx
  src/components/KYC/Form/index.tsx
  src/components/LoaderRing.tsx
  src/components/Selector/types.ts
  src/components/form/Field.tsx
  src/helpers/getFilePreviews/getFilePreviews.test.ts
  src/helpers/getFilePreviews/getFilePreviews.ts
  src/helpers/getFilePreviews/index.ts
  src/helpers/index.ts
  src/hooks/useDebounce.ts
  src/pages/Admin/Charity/Banking/Banking.tsx
  src/pages/Admin/Charity/Banking/CurrencySelector.tsx
  src/pages/Admin/Charity/Banking/ExpectedFunds.tsx
  src/pages/Admin/Charity/Banking/RecipientDetails/AccountRequirementsSelector.tsx
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetails.tsx
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetailsForm/Form.tsx
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetailsForm/RequirementField.tsx
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetailsForm/formToCreateRecipientRequest.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetailsForm/useRecipientDetailsForm/createSchema.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/getDefaultValues.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/helpers/dot.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/helpers/index.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/helpers/isCountry.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/helpers/isTextType.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/types.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/useRecipientDetails.ts
  src/pages/Admin/Charity/Banking/UpdateDetailsButton.tsx
  src/pages/Admin/Charity/Banking/VerificationStatus.tsx
  src/pages/Admin/Charity/Banking/useBanking.ts
  src/pages/Admin/Charity/Banking/useCurrencies.ts
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/EditProfile/common/Group.tsx
  src/pages/Admin/Charity/EditProfile/useEditProfile.ts
  src/pages/Admin/Charity/ProgramEditor/Form.tsx
  src/pages/Admin/Charity/ProgramEditor/useSubmit.ts
  src/pages/Admin/Charity/Programs/Program.tsx
  src/pages/Admin/Charity/common/Group.tsx
  src/pages/Admin/Charity/common/index.ts
  src/pages/Admin/Charity/common/useUpdateEndowmentProfile.ts
  src/pages/Registration/Steps/Documentation/Form/index.tsx
  src/pages/Registration/Steps/Documentation/Form/useSubmit.ts
  src/pages/Registration/Steps/Documentation/schema.ts
  src/schemas/file.ts
  src/services/aws/bankDetails.ts
  src/types/aws/ap/index.ts
  tailwind.config.js
Labels: design

#2469 Component types
  src/components/ActivityCountries.tsx
  src/components/CountrySelector/CountrySelector.tsx
  src/components/CountrySelector/Options.tsx
  src/components/CountrySelector/constants.ts
  src/components/CountrySelector/helpers.ts
  src/components/CountrySelector/index.ts
  src/components/FileDropzone/FileDropzone.tsx
  src/components/FileDropzone/helpers.ts
  src/components/FileDropzone/index.ts
  src/components/KYC/Form/us-states.ts
  src/components/Selector/MultiSelector.tsx
  src/components/Selector/Selector.tsx
  src/components/Selector/constants.ts
  src/components/Selector/types.ts
  src/components/registration/index.ts
  src/helpers/getFilePreviews/getFilePreviews.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetailsForm/Form.tsx
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetailsForm/useRecipientDetailsForm/createFieldSchema.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetailsForm/useRecipientDetailsForm/createSchema.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/getDefaultValues.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/types.ts
  src/pages/Admin/Charity/Banking/RecipientDetails/useRecipientDetails.ts
  src/pages/Admin/Charity/EditProfile/getSDGLabelValuePair.ts
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Admin/Charity/EditProfile/types.ts
  src/pages/Donations/Filter/constants.ts
  src/pages/Donations/Filter/types.ts
  src/pages/Registration/Steps/ContactDetails/constants.ts
  src/pages/Registration/Steps/ContactDetails/index.tsx
  src/pages/Registration/Steps/ContactDetails/schema.ts
  src/pages/Registration/Steps/ContactDetails/types.ts
  src/pages/Registration/Steps/Documentation/Form/index.tsx
  src/pages/Registration/Steps/Documentation/index.tsx
  src/pages/Registration/Steps/Documentation/schema.ts
  src/pages/Registration/Steps/getRegistrationState.ts
  src/pages/Registration/types.ts
  src/schemas/file.ts
  src/schemas/shape.ts
  src/slices/donation/types.ts
  src/types/components.ts
  src/types/countries.ts
  src/types/utils.ts
Labels: bug, refactor

#2479 Fix check icon
  src/components/Icon/icons.ts
Labels: bug

#2478 AP-875 Better Giving Re-branding (take 2)
  public/manifest.json
  src/App/Header/MobileNav/Menu.tsx
  src/App/Header/index.tsx
  src/App/Layout.tsx
  src/App/__tests__/App.test.tsx
  src/App/constants.ts
  src/assets/images/bettergiving-logo.svg
  src/aws-exports.js
  src/components/Image/DappLogo.tsx
  src/components/donation/Steps/DonateMethods/Stripe.tsx
  src/components/donation/Steps/Submit/Breakdown/estimateDonation.ts
  src/constants/env.ts
  src/pages/Marketplace/Hero.tsx
  src/pages/Marketplace/Sidebar/common/MultilevelFilter/MultilevelFilter.tsx
  src/pages/Registration/SigningResult/Success.tsx
Labels: enhancement, good first issue, design

#2482 AP-859: Set an actual calculation to get the estimate payout amount when submitting bank details
  src/pages/Admin/Charity/Banking/Banking.tsx
  src/pages/Admin/Charity/Banking/ExpectedFunds.tsx
  src/pages/Admin/Charity/Banking/RecipientDetails/RecipientDetails.tsx
  src/pages/Admin/Charity/Banking/RecipientDetails/useRecipientDetails.ts
  src/pages/Admin/Charity/Banking/UpdateDetailsButton.tsx
Labels: enhancement

#2480 AP-846: New Balances & Metrics in Profile & Admin pages
  src/App/App.tsx
  src/components/Icon/icons.ts
  src/components/Split/Split.tsx
  src/components/admin/FormSkeleton.tsx
  src/pages/Admin/Charity/Dashboard/Balance.tsx
  src/pages/Admin/Charity/Dashboard/Dashboard.tsx
  src/pages/Admin/Charity/Dashboard/index.tsx
  src/pages/Admin/Charity/Widget/Preview/AdvancedOptions.tsx
  src/pages/Admin/Charity/index.tsx
  src/pages/Admin/constants.ts
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/Balances.tsx
  src/services/aws/aws.ts
  src/types/aws/ap/index.ts
Labels: enhancement

#2485 AP-874: errors on signup/signin modal
  src/App/Header/UserMenu/UserMenu.tsx
  src/components/Authenticator.tsx
  src/pages/Signin/Signin.tsx
Labels: bug, refactor

#2483 Remove jwt secrets in favor of CORS
  .env.example
  .github/workflows/javascript.yml
  amplify.yml
  package.json
  src/components/KadoModal.tsx
  src/constants/auth.ts
  src/constants/env.ts
  src/helpers/createAuthToken.ts
  src/helpers/getFilePreviews/getFilePreviews.test.ts
  src/helpers/index.ts
  src/helpers/jwt-token.ts
  src/helpers/uploadFiles.test.ts
  src/helpers/uploadFiles.ts
  src/pages/Gift/Claim/Form.tsx
  src/pages/Gift/Mailer/Form.tsx
  src/pages/OAuthRedirector.tsx
  src/services/apes/donations/donations.ts
  src/services/aws/aws.ts
  src/services/aws/registration/registration.ts
  src/slices/authSlice.ts
  src/slices/donation/sendDonation/index.ts
  src/slices/gift/purchase.ts
  src/store/store.ts
  yarn.lock
Labels: bug

#2486 AP-882 Marketplace Card: bookmark btn removed
  src/pages/Marketplace/Cards/Card.tsx
Labels: bug

#2489 Placeholder Other tab
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
Labels: bug, enhancement

#2491 AP-892: Fix Typo in Admin Dashboard "Payed" >> "Paid"
  src/pages/Admin/Charity/Dashboard/Balance.tsx
Labels: bug

#2490 AP-893: Fix UpdateDetailsButton logic that enables updating form
  src/components/BankDetails/BankDetails.tsx
Labels: bug

#2503 AP-895: Non-Profit Status registration step
  src/pages/Registration/Steps/ProgressIndicator.tsx
Labels: refactor

#2504 RC-v1.9: deps update
  package.json
  yarn.lock
Labels: dependencies

#2505 AP-901 Copy tweaks: Banking Details + Reg step
  src/components/BankDetails/ExpectedFunds.tsx
  src/pages/Registration/Steps/FSAInquiry/FSAInquiry.tsx
Labels: bug

#2506 Closes AP-899,AP-900: bank details form fixes
  src/components/BankDetails/RecipientDetails/RecipientDetails.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/formToCreateRecipientRequest.ts
  src/components/BankDetails/RecipientDetails/getDefaultValues.ts
  src/components/BankDetails/RecipientDetails/helpers/getDefaultValues.ts
  src/components/BankDetails/RecipientDetails/helpers/index.ts
  src/components/BankDetails/RecipientDetails/useRecipientDetails.ts
  src/pages/Registration/Resume/useSubmit.ts
  src/pages/Registration/SigningResult/Success.tsx
  src/pages/Registration/Steps/Banking/Banking.tsx
  src/pages/Registration/Steps/Banking/useSubmit.ts
  src/pages/Registration/Steps/getRegistrationState.ts
  src/pages/Registration/Steps/index.tsx
  src/services/aws/bankDetails.ts
  src/services/aws/registration/registration.ts
  src/types/aws/ap/bankDetails.ts
  src/types/aws/ap/registration.ts
Labels: bug

#2508 AP-905 No dark theme
  src/index.tsx
Labels: bug

#2509 AP-908 Fix Dashboard balances NaN
  src/pages/Admin/Charity/Dashboard/Balance.tsx
  src/pages/Admin/Charity/Dashboard/Dashboard.tsx
Labels: bug, enhancement

#2492 AP-878: Donations: "Other" tab
  public/dafdirect-widget.html
  src/components/Group.tsx
  src/components/IFrame.tsx
  src/components/donation/Steps/DonateMethods/BuildEmailForm.tsx
  src/components/donation/Steps/DonateMethods/DAFDirect.tsx
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
  src/components/donation/Steps/DonateMethods/Stocks.tsx
  src/pages/Admin/Charity/Banking/Banking.tsx
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/ProgramEditor/Form.tsx
  src/pages/Admin/Charity/common/index.ts
Labels: enhancement

#2510 AP-907 Protected user donations page & POC user header menu
  src/App/App.tsx
  src/App/Header/UserMenu/Menu.tsx
  src/pages/Donations/Filter/Form.tsx
  src/pages/Donations/NoDonations.tsx
  src/pages/Donations/index.tsx
Labels: bug, enhancement

#2512 Make DonateMethods tabs appear in 2 rows on mobile
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
Labels: design

#2513 AP-911: Admin: Edit Profile page wiring
  src/helpers/admin/getPayloadDiff.ts
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Admin/Charity/EditProfile/update.ts
  src/pages/Admin/Charity/EditProfile/useEditProfile.ts
  src/pages/Admin/Charity/ProgramEditor/useSubmit.ts
  src/pages/Admin/Charity/Programs/Program.tsx
  src/pages/Admin/Charity/common/useUpdateEndowmentProfile.ts
  src/services/aws/aws.ts
  src/services/types.ts
  src/types/aws/ap/index.ts
Labels: enhancement, priority

#2511 AP-904: Page authorization
  .yarnrc.yml
  package.json
  src/App/App.tsx
  src/App/Header/UserMenu/Menu.tsx
  src/App/Header/UserMenu/UserMenu.tsx
  src/App/Protected.tsx
  src/App/__tests__/App.test.tsx
  src/components/LoaderRing.tsx
  src/contexts/Auth.tsx
  src/helpers/jwt-token.ts
  src/index.tsx
  src/pages/Admin/index.tsx
  src/pages/Application/Application.tsx
  src/pages/Applications/Applications.tsx
  src/pages/Donations/index.tsx
  src/pages/OAuthRedirector.tsx
  src/pages/Registration/Signup/useSubmit.ts
  src/pages/Registration/Steps/ContactDetails/Form/useSubmit.ts
  src/pages/Registration/Steps/Documentation/FSA/Form/useSubmit.ts
  src/pages/Registration/index.tsx
  src/pages/Signin/Signin.tsx
  src/services/aws/aws.ts
  src/slices/auth.ts
  src/store/store.ts
  yarn.lock
Labels: good first issue, refactor

#2514 AP-896: multiselect focus
  src/components/Selector/MultiSelector.tsx
  src/components/Selector/Selector.tsx
  src/components/Selector/constants.ts
Labels: bug, enhancement

#2515 Registration: prefill contact names with auth attributes
  src/pages/Registration/Steps/ContactDetails/index.tsx
  src/slices/auth.ts
Labels: enhancement

#2516 Minor refactors
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/useRecipientDetailsForm/createFieldSchema.ts
  src/components/CountrySelector/Options.tsx
  src/components/FileDropzone/FileDropzone.tsx
  src/components/Selector/MultiSelector.tsx
  src/components/TokenField/TokenOptions.tsx
  src/contexts/ModalContext.tsx
  src/contexts/WalletContext/useInjectedProvider.ts
  src/contexts/WalletContext/wallet-connect/useEVMWC.ts
  src/helpers/admin/flatten.ts
  src/helpers/cleanObject.ts
  src/helpers/getFilePreviews/getFilePreviews.ts
  src/helpers/uploadFiles.ts
  src/pages/Admin/Charity/EditProfile/useEditProfile.ts
  src/pages/Admin/Charity/ProgramEditor/Milestones/Milestones.tsx
  src/pages/Admin/Charity/ProgramEditor/useSubmit.ts
  src/pages/Profile/Body/GeneralInfo/GeneralInfo.tsx
  src/pages/Profile/Body/Program/Milestones.tsx
  src/pages/Profile/ProfileContext.ts
  src/pages/Registration/Steps/ProgressIndicator.tsx
  src/pages/Registration/Steps/StepGuard.tsx
  src/schemas/file.ts
  src/slices/auth.ts
Labels: refactor

#2517 AP-886: Scrolling up/down over expected monthly donations input field should not be changing the input value
  src/components/BankDetails/ExpectedFunds.tsx
Labels: bug

#2519 AP-906: User menu
  src/App/Header/UserMenu/EndowmentLink.tsx
  src/App/Header/UserMenu/Menu.tsx
  src/App/Header/UserMenu/UserMenu.tsx
  src/components/Icon/icons.ts
  src/pages/Donations/Filter/index.tsx
  src/pages/Donations/index.tsx
  src/services/apes/donations/usePaginatedDonations.ts
Labels: design, refactor

#2518 Authorization update: use `cognito:groups` claim instead of custom claim
  src/App/Header/UserMenu/EndowmentLink.tsx
  src/App/Header/UserMenu/Menu.tsx
  src/App/Header/UserMenu/UserMenu.tsx
  src/components/Icon/icons.ts
  src/constants/auth.ts
  src/contexts/Auth.tsx
  src/pages/Application/Application.tsx
  src/pages/Applications/Applications.tsx
  src/pages/Donations/Filter/index.tsx
  src/pages/Donations/index.tsx
  src/services/apes/donations/usePaginatedDonations.ts
  src/services/aws/aws.ts
  src/slices/auth.ts
  src/types/auth.ts
Labels: refactor

#2521 Chng endow to nonprofit
  src/App/Header/UserMenu/Menu.tsx
  src/pages/Admin/Charity/Dashboard/Dashboard.tsx
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/Widget/Configurer/Form.tsx
  src/pages/Admin/Charity/Widget/Preview/Preview.tsx
  src/pages/Admin/Charity/Widget/Widget.tsx
  src/pages/Application/Loaded.tsx
  src/pages/Donate/index.tsx
  src/pages/DonateFiatThanks/index.tsx
  src/pages/DonateWidget/DonateWidget.tsx
  src/pages/Marketplace/Cards/Card.tsx
  src/pages/Marketplace/Cards/index.tsx
  src/pages/Profile/PageError.tsx
  src/pages/Profile/Unpublished.tsx
  src/pages/Registration/Signup/Form.tsx
  src/pages/Registration/Steps/Dashboard/EndowmentStatus.tsx
  src/pages/Registration/Steps/OrgDetails/Form/index.tsx
  src/pages/Registration/Success.tsx
  src/pages/Registration/Welcome.tsx
  src/slices/widget.ts
Labels: bug

#2523 AP-889: Bank Details: Disable form while submission operations are running
  src/components/BankDetails/RecipientDetails/RecipientDetails.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/Form.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
Labels: bug

#2524 AP-915: Hide bank details component when "Update Bank Details" button is displayed
  src/components/BankDetails/BankDetails.tsx
Labels: design

#2525 Endow-auth
  .env.example
  src/pages/Admin/Context.tsx
  src/pages/Admin/index.tsx
  src/slices/auth.ts
Labels: bug, enhancement

#2527 Closes AP-917: general BankDetails layout updates
  src/components/BankDetails/BankDetails.tsx
  src/components/BankDetails/CurrencySelector.tsx
  src/components/BankDetails/ExpectedFunds.tsx
  src/components/BankDetails/UpdateDetailsButton.tsx
  src/components/Group.tsx
  src/pages/Admin/Charity/Banking/Banking.tsx
  src/pages/Registration/Steps/Banking/Banking.tsx
Labels: design

#2535 AP-871: Ext link hover
  src/components/donation/Steps/DonateMethods/Stripe.tsx
  src/pages/Admin/Charity/Donations/Table.tsx
  src/pages/Donations/Table.tsx
  src/pages/Registration/Steps/OrgDetails/Form/index.tsx
Labels: bug, design

#2538 Align (fix) BankDetails > ExpectedFunds width on Desktop
  src/components/BankDetails/BankDetails.tsx
  src/components/BankDetails/ExpectedFunds.tsx
  src/pages/Admin/Charity/Banking/VerificationStatus.tsx
Labels: design

#2540 AP-919: Correct Registration step should be displayed on mobile
  src/pages/Registration/Steps/ProgressIndicator.tsx
  src/pages/Registration/Steps/index.tsx
Labels: design

#2539 Prod user pool config
  src/App/__tests__/App.test.tsx
  src/store/amplify-config.ts
  src/store/store.ts
Labels: good first issue

#2541 AP-926 Menu link fixes
  src/App/constants.ts
Labels: bug

#2542 Fix: donate button disabled
  src/pages/Profile/Body/DonateButton.tsx
Labels: bug

#2536 AP-795: Modal filter
  src/components/Icon/icons.ts
  src/pages/Admin/Charity/Widget/Configurer/EndowmentSelector/Options.tsx
  src/pages/Marketplace/ActiveFilters.tsx
  src/pages/Marketplace/Cards/useCards.ts
  src/pages/Marketplace/Filter/Countries.tsx
  src/pages/Marketplace/Filter/Designations.tsx
  src/pages/Marketplace/Filter/Filter.tsx
  src/pages/Marketplace/Filter/KYCFilter.tsx
  src/pages/Marketplace/Filter/SDGs.tsx
  src/pages/Marketplace/Filter/common/FlatFilter.tsx
  src/pages/Marketplace/Filter/common/index.ts
  src/pages/Marketplace/Filter/common/types.ts
  src/pages/Marketplace/Filter/index.ts
  src/pages/Marketplace/Sidebar/Regions.tsx
  src/pages/Marketplace/Sidebar/SDGGroups.tsx
  src/pages/Marketplace/Sidebar/common/Drawer.tsx
  src/pages/Marketplace/Sidebar/common/FlatFilter.tsx
  src/pages/Marketplace/Sidebar/common/MultilevelFilter/Group.tsx
  src/pages/Marketplace/Sidebar/common/MultilevelFilter/MultilevelFilter.tsx
  src/pages/Marketplace/Sidebar/common/MultilevelFilter/index.ts
  src/pages/Marketplace/Sidebar/common/index.ts
  src/pages/Marketplace/Sidebar/index.tsx
  src/pages/Marketplace/Toolbar/index.tsx
  src/pages/Marketplace/index.tsx
  src/slices/components/marketFilter/constants.ts
  src/slices/components/marketFilter/index.ts
  src/slices/components/marketFilter/marketFilter.ts
  src/slices/components/marketFilter/types.ts
  src/types/aws/ap/index.ts
Labels: design, refactor

#2545 AP-930: Cherry-pick modal filter
  src/components/Icon/icons.ts
  src/pages/Admin/Charity/Widget/Configurer/EndowmentSelector/Options.tsx
  src/pages/Marketplace/ActiveFilters.tsx
  src/pages/Marketplace/Cards/useCards.ts
  src/pages/Marketplace/Filter/Countries.tsx
  src/pages/Marketplace/Filter/Designations.tsx
  src/pages/Marketplace/Filter/Filter.tsx
  src/pages/Marketplace/Filter/KYCFilter.tsx
  src/pages/Marketplace/Filter/SDGs.tsx
  src/pages/Marketplace/Filter/common/FlatFilter.tsx
  src/pages/Marketplace/Filter/common/index.ts
  src/pages/Marketplace/Filter/common/types.ts
  src/pages/Marketplace/Filter/index.ts
  src/pages/Marketplace/Sidebar/Regions.tsx
  src/pages/Marketplace/Sidebar/SDGGroups.tsx
  src/pages/Marketplace/Sidebar/common/Drawer.tsx
  src/pages/Marketplace/Sidebar/common/FlatFilter.tsx
  src/pages/Marketplace/Sidebar/common/MultilevelFilter/Group.tsx
  src/pages/Marketplace/Sidebar/common/MultilevelFilter/MultilevelFilter.tsx
  src/pages/Marketplace/Sidebar/common/MultilevelFilter/index.ts
  src/pages/Marketplace/Sidebar/common/index.ts
  src/pages/Marketplace/Sidebar/index.tsx
  src/pages/Marketplace/Toolbar/index.tsx
  src/pages/Marketplace/index.tsx
  src/slices/components/marketFilter/constants.ts
  src/slices/components/marketFilter/index.ts
  src/slices/components/marketFilter/marketFilter.ts
  src/slices/components/marketFilter/types.ts
  src/types/aws/ap/index.ts
Labels: duplicate

#2543 AP-925: Show "Back" and "Continue" buttons on Bank Details registration step
  src/components/BankDetails/BankDetails.tsx
  src/components/BankDetails/RecipientDetails/AccountRequirementsSelector.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetails.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/Form.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
  src/components/BankDetails/RecipientDetails/useRecipientDetails.ts
  src/components/BankDetails/types.ts
  src/components/Group.tsx
  src/pages/Admin/Charity/Banking/Banking.tsx
  src/pages/Admin/Charity/Banking/FormButtons.tsx
  src/pages/Registration/Steps/Banking/Banking.tsx
  src/pages/Registration/Steps/Banking/FormButtons.tsx
  src/pages/Registration/Steps/ProgressIndicator.tsx
Labels: enhancement, design, refactor

#2544 Fix: edit profile selected file preview not showing
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/Form.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/constants.ts
  src/components/FileDropzone/FileDropzone.tsx
  src/components/ImgEditor/ImgEditor.tsx
  src/components/ImgEditor/types.ts
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Admin/Charity/ProgramEditor/schema.ts
  src/pages/Registration/Steps/Documentation/FSA/Form/index.tsx
  src/pages/Registration/Steps/Documentation/FSA/schema.ts
  src/schemas/file.ts
  src/types/lists.ts
Labels: bug, refactor

#2548 AP-934: Marketplace cards layout
  src/pages/Marketplace/Cards/index.tsx
Labels: bug, design

#2549 AP-914: `FileDropzone` should not open "Select File" window when disabled
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/Form.tsx
  src/components/FileDropzone/FileDropzone.tsx
Labels: bug

#2551 File dropzone refactor
  src/components/FileDropzone/DropzoneText.tsx
  src/components/FileDropzone/FileDropzone.tsx
  src/index.css
Labels: bug, refactor
