Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2023-08, with the labels that each got.

#2286 Admin donations pagination
  src/components/HeaderButton.tsx
  src/hooks/useSort/index.ts
  src/hooks/useSort/types.ts
  src/hooks/useSort/useSort.ts
  src/pages/Admin/Charity/Dashboard/Donations/Table.tsx
  src/pages/Admin/Charity/Dashboard/Donations/index.tsx
  src/pages/Donations/MobileTable.tsx
  src/pages/Donations/Table.tsx
  src/pages/Donations/index.tsx
  src/pages/Donations/types.ts
  src/services/apes/donations/donations.ts
  src/services/apes/donations/index.ts
  src/services/apes/donations/usePaginatedDonations.ts
  src/services/apes/donations/useSortDonations.ts
  src/types/aws/apes/donation.ts
  src/types/aws/common.ts
Labels: enhancement

#2273 Subgraph integration
  src/components/admin/Status.tsx
  src/contracts/createTx/txs.ts
  src/contracts/evm/multisig/index.ts
  src/contracts/evm/multisig/queries.json
  src/helpers/__tests__/idParamToNum.test.ts
  src/helpers/admin/block-time.ts
  src/helpers/admin/getTagPayloads.ts
  src/helpers/idParamToNum.ts
  src/pages/Admin/AdminWallet/Members/Members.tsx
  src/pages/Admin/Charity/Dashboard/Table.tsx
  src/pages/Admin/Charity/Dashboard/index.tsx
  src/pages/Admin/Charity/Withdraws/Transactions/Status.tsx
  src/pages/Admin/Context.tsx
  src/pages/Admin/Proposal/Content/Preview/MultisigMember.tsx
  src/pages/Admin/Proposal/Content/index.tsx
  src/pages/Admin/Proposal/PollAction.tsx
  src/pages/Admin/Proposal/Stats.tsx
  src/pages/Admin/Proposal/Votes/index.tsx
  src/pages/Admin/Proposal/index.tsx
  src/pages/Admin/Proposals/Table.tsx
  src/pages/Admin/Proposals/Toolbar/StatusSelector.tsx
  src/pages/Admin/Proposals/index.tsx
  src/services/constants.ts
  src/services/juno/custom/constants.ts
  src/services/juno/custom/custom.ts
  src/services/juno/custom/helpers/admin-resource.ts
  src/services/juno/custom/index.ts
  src/services/juno/queryContract/queryObjects.ts
  src/services/juno/queryContract/types.ts
  src/services/juno/tags.ts
  src/services/subgraph/index.ts
  src/services/subgraph/subgraph.ts
  src/services/subgraph/tags.ts
  src/services/subgraph/types.ts
  src/services/types.ts
  src/slices/admin/proposals.ts
  src/slices/admin/types.ts
  src/store/store.ts
  src/types/contracts/multisig.ts
  src/types/lists.ts
  src/types/subgraph.ts
  src/types/tx.ts
Labels: enhancement, good first issue

#2294 Donation KYC changes
  src/components/KYC/Form/Controls.tsx
  src/components/KYC/index.tsx
  src/components/TokenField/TokenField.tsx
  src/components/donation/Steps/CurrentStep.tsx
  src/components/donation/Steps/Donater/Form/index.tsx
  src/components/donation/Steps/Donater/index.tsx
  src/components/donation/Steps/Progress.tsx
  src/components/donation/Steps/Result/Err.tsx
  src/components/donation/Steps/Submit/index.tsx
  src/components/donation/Steps/index.tsx
  src/pages/Admin/Charity/WidgetConfigurer/WidgetExample/Donater.tsx
  src/pages/Donate/Content.tsx
  src/slices/donation/donation.ts
  src/slices/donation/sendDonation/index.ts
  src/slices/donation/types.ts
Labels: enhancement

#2295 [Bug Fix] Added validation check for `Website` field in Documentation Form
  src/pages/Registration/Steps/Documentation/schema.ts
Labels: bug

#2297 Rename leadeboard
  src/pages/Leaderboard/index.tsx
Labels: enhancement

#2296 RC-v1.8: updates from prod
  package.json
  src/components/HeaderButton.tsx
  src/components/KYC/Form/Controls.tsx
  src/components/KYC/index.tsx
  src/components/TokenField/TokenField.tsx
  src/components/donation/Steps/CurrentStep.tsx
  src/components/donation/Steps/Donater/Form/index.tsx
  src/components/donation/Steps/Donater/index.tsx
  src/components/donation/Steps/Progress.tsx
  src/components/donation/Steps/Result/Err.tsx
  src/components/donation/Steps/Submit/index.tsx
  src/components/donation/Steps/index.tsx
  src/pages/Admin/Charity/Deposits/index.tsx
  src/pages/Admin/Charity/DonationsTable/DonationsTable.tsx
  src/pages/Admin/Charity/DonationsTable/Table.tsx
  src/pages/Admin/Charity/WidgetConfigurer/WidgetExample/Donater.tsx
  src/pages/Donate/Content.tsx
  src/pages/Donate/index.tsx
  src/pages/DonateWidget/DonateWidget.tsx
  src/pages/DonateWidget/InnerComponent.tsx
  src/pages/Donations/index.tsx
  src/pages/Donations/types.ts
  src/services/apes/donations/donations.ts
  src/services/apes/donations/index.ts
  src/services/apes/donations/usePaginatedDonations.ts
  src/slices/donation/donation.ts
  src/slices/donation/sendDonation/index.ts
  src/slices/donation/types.ts
  src/types/aws/apes/donation.ts
  src/types/aws/common.ts
  yarn.lock
Labels: duplicate

#2298 Update deps
  .prettierrc.json
  package.json
  prettier.config.js
  src/App/Footer/Newsletter/schema.ts
  src/components/ActivityCountries.tsx
  src/components/CountrySelector/index.tsx
  src/components/KYC/schema.ts
  src/components/Selector.tsx
  src/components/Split/Split.tsx
  src/components/donation/Steps/Donater/schema.ts
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Admin/Charity/Templates/account/EndowmentStatus/schema.ts
  src/pages/Admin/Charity/Withdraws/WithdrawTabs/Withdrawer/schema.ts
  src/pages/Admin/Core/Templates/index-fund/Alliance/schema.ts
  src/pages/Admin/Core/Templates/index-fund/Config/schema.ts
  src/pages/Admin/Core/Templates/index-fund/CreateFund/schema.ts
  src/pages/Admin/Core/Templates/index-fund/IndexFundOwner/schema.ts
  src/pages/Admin/Core/Templates/index-fund/Members/schema.ts
  src/pages/Admin/Core/Templates/index-fund/RemoveFund/schema.ts
  src/pages/Admin/Core/Templates/registrar/Config/schema.ts
  src/pages/Admin/Core/Templates/registrar/Owner/schema.ts
  src/pages/Admin/Proposal/Voter/schema.ts
  src/pages/Admin/Review/Templates/ReviewCW3Configurer/schema.ts
  src/pages/Admin/templates/cw3/Config/schema.ts
  src/pages/Admin/templates/cw3/FundSender/schema.ts
  src/pages/Admin/templates/cw4/Members/schema.ts
  src/pages/Donations/Filter/schema.ts
  src/pages/Gift/Claim/index.tsx
  src/pages/Gift/Mailer/schema.ts
  src/pages/Gift/Purchase/Purchaser/schema.ts
  src/pages/Registration/Resume/index.tsx
  src/pages/Registration/Signup/index.tsx
  src/pages/Registration/Steps/ContactDetails/schema.ts
  src/pages/Registration/Steps/Documentation/schema.ts
  src/schemas/shape.ts
  src/schemas/types.ts
  src/services/juno/tags.ts
  yarn.lock
Labels: dependencies

#2299 RC-v1.8: updates from prod
  .prettierrc.json
  package.json
  prettier.config.js
  src/App/Footer/Newsletter/SubscriptionForm.tsx
  src/App/Footer/Newsletter/schema.ts
  src/components/ActivityCountries.tsx
  src/components/Addresses/AddForm.tsx
  src/components/CountrySelector/index.tsx
  src/components/KYC/schema.ts
  src/components/KadoModal.tsx
  src/components/Selector.tsx
  src/components/Split/Split.tsx
  src/components/donation/Steps/Donater/schema.ts
  src/pages/Admin/AdminWallet/Members/AddForm.tsx
  src/pages/Admin/AdminWallet/Settings/DurationForm.tsx
  src/pages/Admin/AdminWallet/Settings/ThresholdForm.tsx
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Admin/Charity/Invest/Investor/schema.ts
  src/pages/Admin/Charity/Maturity/Maturity.tsx
  src/pages/Admin/Charity/OtherSettings/Fees/index.tsx
  src/pages/Admin/Charity/Permissions/schema.ts
  src/pages/Admin/Charity/ProgramEditor/schema.ts
  src/pages/Admin/Charity/Templates/account/CloseEndowment/schema.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/schema.ts
  src/pages/Admin/Charity/common/Investment/Redeemer/schema.ts
  src/pages/Admin/Core/Templates/index-fund/Config/schema.ts
  src/pages/Admin/Core/Templates/index-fund/CreateFund/schema.ts
  src/pages/Admin/Core/Templates/index-fund/Members/schema.ts
  src/pages/Admin/Core/Templates/index-fund/RemoveFund/schema.ts
  src/pages/Admin/Core/Templates/registrar/ConfigExtension/schema.ts
  src/pages/Admin/Core/Templates/registrar/Owner/schema.ts
  src/pages/Admin/Core/Templates/registrar/Token/schema.ts
  src/pages/Admin/templates/cw3/FundSender/schema.ts
  src/pages/Donations/Filter/schema.ts
  src/pages/Gift/Claim/index.tsx
  src/pages/Gift/Mailer/schema.ts
  src/pages/Gift/Purchase/Purchaser/schema.ts
  src/pages/Launchpad/About/index.tsx
  src/pages/Launchpad/Fees/index.tsx
  src/pages/Launchpad/Management/DurationForm.tsx
  src/pages/Launchpad/Management/MemberForm.tsx
  src/pages/Launchpad/Management/ThresholdForm.tsx
  src/pages/Launchpad/Maturity/Form/AddForm.tsx
  src/pages/Launchpad/Maturity/index.tsx
  src/pages/Leaderboard/index.tsx
  src/pages/Registration/Resume/index.tsx
  src/pages/Registration/Signup/index.tsx
  src/pages/Registration/Steps/ContactDetails/schema.ts
  src/pages/Registration/Steps/Documentation/schema.ts
  src/schemas/shape.ts
  src/schemas/types.ts
  src/services/apes/tags.ts
  src/services/juno/tags.ts
  src/services/subgraph/tags.ts
  src/types/contracts/indexfund.ts
  yarn.lock
Labels: duplicate

#2302 Prod fix: amount input not accepting values
  src/components/TokenField/TokenField.tsx
  src/components/donation/Steps/Donater/index.tsx
Labels: bug

#2306 Fix maturity query
  package.json
  src/errors/errors.ts
  src/services/juno/index.ts
  yarn.lock
Labels: bug, dependencies

#2307 AP 667: Sentry - basic error logging/capture setup
  amplify.yml
  package.json
  src/App/App.tsx
  src/errors/ErrorHandler.tsx
  src/index.tsx
  yarn.lock
Labels: enhancement

#2303 ap-666: RC-v1.8 Registration changes
  src/App/Header/DesktopNav.tsx
  src/components/form/CheckField.tsx
  src/pages/Admin/Review/Application/Summary/Summary.tsx
  src/pages/Admin/Review/Applications/__tests__/Applications.test.tsx
  src/pages/Registration/ConfirmEmail.tsx
  src/pages/Registration/Resume/useSubmit.ts
  src/pages/Registration/SignNotice.tsx
  src/pages/Registration/SigningResult/ErrorPage.tsx
  src/pages/Registration/SigningResult/SigningResult.tsx
  src/pages/Registration/SigningResult/Success.tsx
  src/pages/Registration/SigningResult/index.ts
  src/pages/Registration/SigningResult/types.ts
  src/pages/Registration/Signup/useSubmit.ts
  src/pages/Registration/Steps/ContactDetails/Form/index.tsx
  src/pages/Registration/Steps/ContactDetails/Form/useSubmit.ts
  src/pages/Registration/Steps/ContactDetails/constants.ts
  src/pages/Registration/Steps/ContactDetails/schema.ts
  src/pages/Registration/Steps/Dashboard/index.tsx
  src/pages/Registration/Steps/Documentation/Form/Level/index.tsx
  src/pages/Registration/Steps/Documentation/Form/Level/useIsDoneLevel.ts
  src/pages/Registration/Steps/Documentation/Form/Radio.tsx
  src/pages/Registration/Steps/Documentation/Form/index.tsx
  src/pages/Registration/Steps/Documentation/Form/useSubmit.ts
  src/pages/Registration/Steps/Documentation/index.tsx
  src/pages/Registration/Steps/Documentation/schema.ts
  src/pages/Registration/Steps/getRegistrationState.ts
  src/pages/Registration/VerifiedEmail.tsx
  src/pages/Registration/Welcome.tsx
  src/pages/Registration/index.tsx
  src/pages/Registration/routes.ts
  src/pages/Registration/types.ts
  src/services/aws/registration/registration.ts
  src/services/types.ts
  src/types/aws/ap/registration.ts
Labels: enhancement, good first issue, design

#2313 RC-v1.8: fix registration redirect url
  src/services/aws/registration/registration.ts
Labels: bug

#2314 RC-v1.8 - fix redirect url
  src/services/aws/registration/registration.ts
Labels: bug

#2316 ap-681: UI changes in allowlists
  src/components/Addresses/Addresses.tsx
  src/contracts/createTx/txs.ts
  src/contracts/evm/Account/abi/txs/txs.json
  src/helpers/admin/getTagPayloads.ts
  src/pages/Admin/Charity/Maturity/Maturity.tsx
  src/pages/Admin/Charity/Maturity/MaturityDate/Form.tsx
  src/pages/Admin/Charity/Maturity/MaturityDate/MaturityDate.tsx
  src/pages/Admin/Charity/Maturity/MaturityDate/index.ts
  src/pages/Admin/Charity/Maturity/MaturityDate/types.ts
  src/pages/Admin/Charity/Permissions/Permissions.tsx
  src/pages/Admin/Charity/Permissions/PermissionsTable.tsx
  src/pages/Admin/Charity/Permissions/helpers/controllerUpdate.ts
  src/pages/Admin/Charity/Permissions/schema.ts
  src/pages/Admin/Charity/Permissions/types.ts
  src/pages/Admin/Charity/Whitelists/Form.tsx
  src/pages/Admin/Charity/Whitelists/Whitelists.tsx
  src/pages/Admin/Charity/Whitelists/constants.ts
  src/pages/Admin/Charity/Whitelists/types.ts
  src/pages/Admin/Charity/common/Allowlist/Allowlist.tsx
  src/pages/Admin/Charity/common/Allowlist/Form.tsx
  src/pages/Admin/Charity/common/Allowlist/index.ts
  src/pages/Admin/Charity/common/Allowlist/types.ts
  src/pages/Admin/Charity/common/Allowlist/useSubmit.ts
  src/pages/Admin/Charity/index.tsx
  src/pages/Launchpad/Whitelists/Form.tsx
  src/services/constants.ts
  src/types/contracts/account.ts
  src/types/tx.ts
Labels: enhancement, refactor

#2317 Softlaunch fixes
  src/pages/Registration/Steps/Dashboard/index.tsx
  src/pages/Registration/Steps/Documentation/Form/index.tsx
  src/pages/Registration/Steps/WalletRegistration/ChooseWallet/index.tsx
  src/pages/Registration/Steps/WalletRegistration/WalletSubmission.tsx
Labels: refactor

#2318 AP-703: Add search in multiselector
  src/components/ActivityCountries.tsx
  src/components/KYC/Form/index.tsx
  src/components/Selector.tsx
  src/components/Selector/FocusableInput.tsx
  src/components/Selector/MultiSelector.tsx
  src/components/Selector/Selector.tsx
  src/components/Selector/constants.ts
  src/components/Selector/index.ts
  src/components/Selector/types.ts
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/WidgetConfigurer/WidgetUrlGenerator/DenomSelector.tsx
  src/pages/Donations/Filter/CurrencyDropdown.tsx
  src/pages/Donations/Filter/DonationStatusDropdown.tsx
  src/pages/Donations/Filter/NetworkDropdown.tsx
  src/pages/Registration/Steps/ContactDetails/Form/index.tsx
  src/pages/Registration/Steps/Documentation/Form/index.tsx
Labels: refactor

#2319 Applications multisig queries move to subgraph
  src/helpers/admin/getTagPayloads.ts
  src/pages/Admin/Review/Application/Summary/Proposal.tsx
  src/services/juno/custom/custom.ts
  src/services/juno/queryContract/queryObjects.ts
  src/services/juno/queryContract/types.ts
  src/services/juno/tags.ts
  src/services/subgraph/index.ts
  src/services/subgraph/subgraph.ts
  src/services/subgraph/tags.ts
  src/services/types.ts
  src/types/contracts/multisig.ts
  src/types/subgraph.ts
  src/types/typechain-types/custom.ts
Labels: bug, enhancement

#2320 ap-679: update endpoint versions
  src/pages/Leaderboard/DonationMetrics.tsx
  src/services/apes/apes.ts
  src/services/aws/leaderboard.ts
Labels: enhancement

#2328 Legacy: deps update
  package.json
  yarn.lock
Labels: dependencies

#2329 RC-v1.8: demo fixes
  src/contexts/ErrorContext/ErrorContext.tsx
  src/pages/Admin/Charity/index.tsx
  src/pages/Registration/Steps/ContactDetails/constants.ts
Labels: bug
