Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2023-10, with the labels that each got.

#2402 AP-754: Withdraw source
  src/pages/Admin/Charity/Templates/account/CloseEndowment/Beneficiary.tsx
  src/pages/Admin/Charity/Widget/Configurer/EndowmentSelector/EndowmentSelector.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/Context.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/Tabs.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Amounts.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Beneficiary/Beneficiary.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Beneficiary/EndowmentOptions.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Beneficiary/EndowmentSelector.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Form.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Network.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/SourceEndow.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Submit/Submit.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/index.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/types.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/useWithdraw.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/index.tsx
  src/services/juno/custom/custom.ts
  src/services/juno/queryContract/queryObjects.ts
  src/services/types.ts
  src/types/contracts/account.ts
  src/types/subgraph.ts
Labels: enhancement, good first issue

#2406 AP-811: HOT FIX: usdc balance not showing on mainnet
  src/constants/tokens.ts
  src/services/juno/custom/custom.ts
Labels: bug, priority

#2405 AP-812 Tweaks to Endowment "Published" status handling
  src/pages/Profile/index.tsx
  src/slices/components/marketFilter/constants.ts
  src/slices/components/marketFilter/types.ts
Labels: bug, enhancement

#2413 AP-816 HOT FIX: invest account details
  src/pages/Admin/Charity/Account/Balances.tsx
Labels: bug, priority

#2414 AP-819: HOT FIX: withdraw fee not showing
  src/constants/urls.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/Tabs.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Breakdown.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Form.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/helpers.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/index.tsx
Labels: bug, enhancement, priority, design

#2415 RC-v1.9: updates from master
  package.json
  src/App/App.tsx
  src/App/Header/DesktopNav.tsx
  src/App/Header/MobileNav/Menu.tsx
  src/App/constants.ts
  src/App/types.ts
  src/constants/tokens.ts
  src/constants/urls.ts
  src/helpers/__tests__/cleanObject.test.ts
  src/helpers/cleanObject.ts
  src/index.tsx
  src/pages/Admin/Charity/Account/Balances.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/Tabs.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Breakdown.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Form.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/helpers.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/index.tsx
  src/pages/Marketplace/Cards/Card.tsx
  src/pages/Profile/index.tsx
  src/pages/Registration/Steps/Documentation/Form/index.tsx
  src/pages/Registration/Steps/Documentation/schema.ts
  src/services/juno/custom/custom.ts
  src/slices/components/marketFilter/constants.ts
  src/slices/components/marketFilter/types.ts
  yarn.lock
Labels: duplicate

#2425 Remove remaining AST
  public/index.html
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/services/aws/aws.ts
  src/types/aws/ap/index.ts
Labels: refactor

#2426 Remove `ethers`
  .env.example
  amplify.yml
  package.json
  src/constants/urls.ts
  src/services/apes/helpers/fetchBalances.ts
  yarn.lock
Labels: dependencies

#2429 Remove empty string `className/classes` props
  src/components/TokenField/TokenSelector.tsx
  src/pages/Admin/Charity/Widget/Configurer/Configurer.tsx
  src/pages/Admin/Charity/Widget/Widget.tsx
  src/pages/Registration/Steps/ProgressIndicator.tsx
Labels: refactor

#2430 Remove random semicolon (`;`) from pages/Admin/index
  src/pages/Admin/index.tsx
Labels: bug

#2431 Donate form wallet
  src/components/WalletSuite/ConnectedWallet/Details/Address.tsx
  src/components/WalletSuite/ConnectedWallet/Details/Balances/Balances.tsx
  src/components/WalletSuite/ConnectedWallet/Details/Balances/CoinBalances.tsx
  src/components/WalletSuite/ConnectedWallet/Details/Balances/KadoOpener.tsx
  src/components/WalletSuite/ConnectedWallet/Details/Balances/index.ts
  src/components/WalletSuite/ConnectedWallet/Details/Favourites/Favourite.tsx
  src/components/WalletSuite/ConnectedWallet/Details/Favourites/index.tsx
  src/components/WalletSuite/ConnectedWallet/Details/MobileTitle.tsx
  src/components/WalletSuite/ConnectedWallet/Details/MyEndowments/Links.tsx
  src/components/WalletSuite/ConnectedWallet/Details/MyEndowments/MyEndowments.tsx
  src/components/WalletSuite/ConnectedWallet/Details/MyEndowments/index.ts
  src/components/WalletSuite/ConnectedWallet/Details/index.tsx
  src/components/WalletSuite/ConnectedWallet/index.tsx
  src/components/WalletSuite/WalletSelectorOpener/index.tsx
  src/components/WalletSuite/constants.ts
  src/components/WalletSuite/index.tsx
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
  src/components/donation/Steps/DonateMethods/WalletModal/Connector.tsx
  src/components/donation/Steps/DonateMethods/WalletModal/WalletModal.tsx
  src/components/donation/Steps/DonateMethods/WalletModal/index.ts
  src/components/donation/Steps/Donater/Form/ChainSelector.tsx
  src/components/donation/Steps/Donater/Form/index.tsx
  src/components/donation/Steps/Donater/index.tsx
  src/pages/DonateWidget/Content.tsx
Labels: design, refactor

#2427 AP-824, AP-821: Amplify Auth integration
  .gitignore
  amplify.yml
  amplify/.config/project-config.json
  amplify/cli.json
  amplify/team-provider-info.json
  package.json
  public/index.html
  src/App/App.tsx
  src/App/Header/UserMenu/Menu.tsx
  src/App/Header/UserMenu/UserMenu.tsx
  src/App/Header/UserMenu/index.ts
  src/App/Header/index.tsx
  src/App/Protected.tsx
  src/App/__tests__/App.test.tsx
  src/aws-exports.js
  src/components/WalletSuite/ConnectedWallet/Details/Address.tsx
  src/components/WalletSuite/ConnectedWallet/Details/Balances/Balances.tsx
  src/components/WalletSuite/ConnectedWallet/Details/Balances/CoinBalances.tsx
  src/components/WalletSuite/ConnectedWallet/Details/Balances/KadoOpener.tsx
  src/components/WalletSuite/ConnectedWallet/Details/Balances/index.ts
  src/components/WalletSuite/ConnectedWallet/Details/Favourites/Favourite.tsx
  src/components/WalletSuite/ConnectedWallet/Details/Favourites/index.tsx
  src/components/WalletSuite/ConnectedWallet/Details/MobileTitle.tsx
  src/components/WalletSuite/ConnectedWallet/Details/MyEndowments/Links.tsx
  src/components/WalletSuite/ConnectedWallet/Details/MyEndowments/MyEndowments.tsx
  src/components/WalletSuite/ConnectedWallet/Details/MyEndowments/index.ts
  src/components/WalletSuite/ConnectedWallet/Details/index.tsx
  src/components/WalletSuite/ConnectedWallet/index.tsx
  src/components/WalletSuite/WalletSelectorOpener/index.tsx
  src/components/WalletSuite/constants.ts
  src/components/WalletSuite/index.tsx
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
  src/components/donation/Steps/DonateMethods/WalletModal/Connector.tsx
  src/components/donation/Steps/DonateMethods/WalletModal/WalletModal.tsx
  src/components/donation/Steps/DonateMethods/WalletModal/index.ts
  src/components/donation/Steps/Donater/Form/ChainSelector.tsx
  src/components/donation/Steps/Donater/Form/index.tsx
  src/components/donation/Steps/Donater/index.tsx
  src/constants/routes.ts
  src/index.css
  src/index.tsx
  src/pages/DonateWidget/Content.tsx
  src/pages/Signin/Signin.tsx
  src/pages/Signin/index.ts
  yarn.lock
Labels: good first issue, design

#2437 AP-830: remove envs
  .env.example
  amplify.yml
  src/App/Header/MobileNav/Menu.tsx
  src/App/Header/MobileNav/Opener.tsx
  src/App/Header/index.tsx
  src/App/Layout.tsx
  src/assets/images/angelgiving-H-logo-wht.svg
  src/components/Image/DappLogo.tsx
  src/components/Image/index.ts
  src/constants/chainOptions.ts
  src/constants/chains.ts
  src/constants/common.ts
  src/constants/env.ts
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/EditProfile/getEndowDesignationLabelValuePair.ts
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Admin/Charity/EditProfile/types.ts
  src/pages/Admin/Charity/Widget/Preview/Preview.tsx
  src/pages/DonateWidget/DonateWidget.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/EndowDesignationTag.tsx
  src/pages/Registration/Steps/Documentation/Form/index.tsx
  src/types/aws/ap/index.ts
  src/types/aws/apes/index.ts
  src/types/lists.ts
Labels: refactor

#2445 Update registration submit
  src/pages/Registration/Steps/Dashboard/index.tsx
  src/services/aws/registration/registration.ts
Labels: refactor

#2444 Master: update deps
  package.json
  yarn.lock
Labels: dependencies

#2454 OAuth manual redirect
  src/App/App.tsx
  src/App/Header/UserMenu/UserMenu.tsx
  src/App/Header/index.tsx
  src/constants/o-auth.ts
  src/constants/routes.ts
  src/index.tsx
  src/pages/OAuthRedirector.tsx
  src/pages/Signin/Signin.tsx
Labels: bug
