Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2023-03, with the labels that each got.

#1886 Update testnet contracts
  src/constants/contracts.ts
Labels: enhancement

#1849 move Logo component to common components
  src/App/Header/Logo.tsx
  src/components/APLogo.tsx
  src/components/Image/Image.tsx
  src/components/Image/ImagePlaceholder.tsx
  src/components/Image/index.ts
  src/components/WalletSuite/ConnectedWallet/Details/Favourites/Favourite.tsx
  src/components/WalletSuite/ConnectedWallet/Details/Logo.tsx
  src/components/WalletSuite/ConnectedWallet/Details/MyEndowments/MyEndowments.tsx
  src/components/WalletSuite/WalletSelectorOpener/Connector.tsx
  src/pages/Profile/Logo.tsx
  src/pages/Profile/index.tsx
Labels: enhancement, good first issue

#1879 RC-v1.8: Invest sections mobile layout
  package.json
  src/pages/Admin/Charity/Account/Balances.tsx
  src/pages/Admin/Charity/Account/index.tsx
  src/pages/Admin/Charity/Invest/index.tsx
  src/pages/Admin/Charity/Settings/StrategyEditor/Fields/Field.tsx
  src/pages/Admin/Charity/Settings/StrategyEditor/Form.tsx
  src/pages/Admin/Charity/Settings/index.tsx
  src/pages/Admin/Charity/common/Balances/Balance.tsx
  src/pages/Admin/Charity/common/Balances/index.tsx
  src/pages/Admin/Charity/common/Investment/index.tsx
  src/pages/Admin/Layout.tsx
  tailwind.config.js
  yarn.lock
Labels: enhancement

#1872 Help in Registration Link Added
  src/pages/Registration/Signup/Form.tsx
Labels: enhancement

#1862 RC-v1.8 <-- master updates
  public/index.html
  src/App/Header/Airdrop/Catcher.tsx
  src/assets/images/angelgiving-H-logo-beta-wht.png
  src/assets/images/angelgiving-H-logo-beta-wht.svg
  src/components/ImgEditor/ImgCropper.tsx
  src/components/KYC/Form/Controls.tsx
  src/components/KYC/index.tsx
  src/components/KadoModal.tsx
  src/components/Modal.tsx
  src/components/Popup.tsx
  src/components/Prompt/Prompt.tsx
  src/components/WalletSuite/ConnectedWallet/Details/Favourites/index.tsx
  src/components/WalletSuite/ConnectedWallet/Details/index.tsx
  src/components/WalletSuite/WalletSelectorOpener/WalletModal.tsx
  src/components/donation/Steps/Result/Success/Share.tsx
  src/constants/common.ts
  src/constants/contracts.ts
  src/constants/unsdgs.ts
  src/contexts/ModalContext.tsx
  src/contracts/CW3/CW3Review.ts
  src/pages/Admin/Charity/DonationsTable/DonationsTable.tsx
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Admin/Charity/Withdraws/WithdrawTabs/Withdrawer/Network.tsx
  src/pages/Admin/Core/Templates/registrar/Config/Form.tsx
  src/pages/Admin/Core/Templates/registrar/Config/index.tsx
  src/pages/Admin/Core/Templates/registrar/Config/schema.ts
  src/pages/Admin/Core/Templates/registrar/Config/useConfigureRegistrar.ts
  src/pages/Admin/Proposal/Voter/Form.tsx
  src/pages/Donations/MobileTable.tsx
  src/pages/Donations/Table.tsx
  src/pages/Donations/index.tsx
  src/pages/Leaderboard/Table/Row/Amount/Summary.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/Balances.tsx
  src/pages/Registration/Steps/Documentation/schema.ts
  src/services/apes/donations.ts
  src/services/juno/custom/helpers/admin-resource.ts
  src/types/aws/ap/index.ts
  src/types/aws/apes/donation.ts
  src/types/contracts/registrar.ts
Labels: duplicate

#1893 Launchpad submit success
  src/pages/Launchpad/Start.tsx
  src/pages/Launchpad/Success.tsx
  src/pages/Launchpad/Summary/index.tsx
  src/pages/Launchpad/index.tsx
  src/slices/launchpad/launchpad.ts
Labels: good first issue

#1892 Fix image flicker with `Image` component
  src/components/Image/Image.tsx
Labels: bug

#1891 Launchpad submit
  src/contracts/Account.ts
  src/pages/Launchpad/Start.tsx
  src/pages/Launchpad/Success.tsx
  src/pages/Launchpad/Summary/index.tsx
  src/pages/Launchpad/index.tsx
  src/services/aws/aws.ts
  src/slices/launchpad/launchpad.ts
  src/types/aws/ap/index.ts
  src/types/contracts/account.ts
  src/types/contracts/common.ts
  src/types/contracts/registrar.ts
Labels: good first issue

#1871 Giftcard fixes
  src/helpers/richTextToHtml.ts
  src/index.css
  src/pages/Gift/Mailer/Form.tsx
  src/pages/Gift/Mailer/Success.tsx
  src/pages/Gift/Purchase/Result/Success.tsx
Labels: bug

#1876 Withdraw funds page
  src/components/HeaderButton.tsx
  src/components/Icon/icons.ts
  src/components/Logo/Logo.tsx
  src/hooks/useSort.ts
  src/pages/Admin/Charity/DonationsTable/Table.tsx
  src/pages/Admin/Charity/Permissions/types.ts
  src/pages/Admin/Charity/Withdraws/OpenRequestsInfo.tsx
  src/pages/Admin/Charity/Withdraws/Transactions/Actions.tsx
  src/pages/Admin/Charity/Withdraws/Transactions/List/Log.tsx
  src/pages/Admin/Charity/Withdraws/Transactions/List/index.tsx
  src/pages/Admin/Charity/Withdraws/Transactions/LoadMoreBtn.tsx
  src/pages/Admin/Charity/Withdraws/Transactions/MobileTable/MobileTable.tsx
  src/pages/Admin/Charity/Withdraws/Transactions/MobileTable/TableRow.tsx
  src/pages/Admin/Charity/Withdraws/Transactions/MobileTable/index.ts
  src/pages/Admin/Charity/Withdraws/Transactions/Status.tsx
  src/pages/Admin/Charity/Withdraws/Transactions/Table/LogRow.tsx
  src/pages/Admin/Charity/Withdraws/Transactions/Table/index.tsx
  src/pages/Admin/Charity/Withdraws/Transactions/index.tsx
  src/pages/Admin/Charity/Withdraws/Transactions/types.ts
  src/pages/Admin/Charity/Withdraws/WithdrawTabs/Withdrawer/Network.tsx
  src/pages/Admin/Charity/Withdraws/WithdrawTabs/Withdrawer/Submit.tsx
  src/pages/Admin/Charity/Withdraws/WithdrawTabs/index.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Amounts.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Beneficiary.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Form.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Network.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Submit/Submit.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Submit/SubmitLocked.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Submit/WithdrawButton.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Submit/index.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Warning.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/index.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/schema.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/types.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/useLogWithdrawProposal.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/useWithdraw.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/index.tsx
  src/pages/Admin/Charity/Withdraws/index.tsx
  src/pages/Admin/Charity/Withdraws/useGetWithdrawLogs.ts
  src/pages/Admin/Charity/constants.ts
  src/pages/Donations/MobileTable.tsx
  src/pages/Donations/Table.tsx
  src/services/apes/apes.ts
  src/types/aws/apes/index.ts
Labels: enhancement

#1895 Fix withdraw table prop link
  src/components/Icon/icons.ts
  src/pages/Admin/Charity/Withdraws/Transactions/Actions.tsx
  src/pages/Admin/Charity/Withdraws/Transactions/Table/LogRow.tsx
Labels: bug

#1898 [Hot Fix] Increase Minimum Ethereum Withdraw Amount from 20 to 40 USDC
  src/pages/Admin/Charity/Withdraws/WithdrawTabs/Withdrawer/Form.tsx
  src/pages/Admin/Charity/Withdraws/WithdrawTabs/Withdrawer/schema.ts
Labels: priority

#1900 Invest dashboard: strategy cards UI
  package.json
  src/index.css
  src/pages/Admin/Charity/Invest/Invesments.tsx
  src/pages/Admin/Charity/Invest/Investment.tsx
  src/pages/Admin/Charity/Invest/Strategy.tsx
  src/pages/Admin/Charity/Invest/index.tsx
  src/pages/Admin/Charity/Invest/strats.ts
  tailwind.config.js
  yarn.lock
Labels: enhancement

#1919 gtag & socials fixes
  public/index.html
  src/App/Footer/constants.ts
  src/components/donation/Steps/Result/Success/Share.tsx
Labels: bug

#1897 Remove unncessary evm packages ( low priority )
  .yarnrc.yml
  config-overrides.js
  package.json
  src/components/donation/Steps/Submit/estimateDonation.ts
  src/constants/ethereum.ts
  src/constants/evm.ts
  src/contexts/WalletContext/WalletContext.tsx
  src/contexts/WalletContext/helpers/checkXdefiPriority.ts
  src/contexts/WalletContext/hooks/useAddEthereumChain.ts
  src/contexts/WalletContext/types.ts
  src/contexts/WalletContext/useInjectedProvider.ts
  src/contexts/WalletContext/useKeplr/useKeplr.ts
  src/contexts/WalletContext/useTerra.ts
  src/contexts/WalletContext/wallet-connect/types.ts
  src/contexts/WalletContext/wallet-connect/useEVMWC.ts
  src/contracts/ERC20/abi.json
  src/contracts/ERC20/index.ts
  src/helpers/evm.ts
  src/helpers/keplr.ts
  src/services/apes/apes.ts
  src/services/apes/helpers/fetchBalances.ts
  src/services/apes/helpers/getERC20Holdings.ts
  src/services/types.ts
  src/slices/donation/sendDonation/index.ts
  src/slices/donation/types.ts
  src/types/ethereum.ts
  src/types/evm.ts
  src/types/lists.ts
  src/types/window.ts
  yarn.lock
Labels: enhancement, dependencies

#1936 Lowercase 'Balance' -> 'balance' when querying giftcard balances
  src/services/juno/queryContract/queryObjects.ts
Labels: bug

#1939 Fix: Removing rounded borders on connector icons
  src/components/WalletSuite/WalletSelectorOpener/Connector.tsx
Labels: bug

#1940 Fix: error creating new endowment
  src/pages/Launchpad/Summary/index.tsx
  src/types/contracts/account.ts
Labels: bug

#1943 Update CheckField input to be a controlled component
  src/components/form/CheckField.tsx
Labels: bug

#1944 Bug: not authorized error when executing passed poll
  package.json
  src/pages/Admin/Proposal/PollAction.tsx
  yarn.lock
Labels: bug, dependencies

#1947 Fix `getPayloadDiff` bug: update `isNaN` uses to `Number.isNaN`
  src/helpers/admin/getPayloadDiff.test.ts
  src/helpers/admin/getPayloadDiff.ts
Labels: bug, priority

#1946 schema update to add required endowment type
  src/pages/Admin/Charity/EditProfile/getEndowDesignationLabelValuePair.ts
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Admin/Review/Applications/__tests__/Applications.test.tsx
  src/pages/Registration/Steps/Documentation/schema.ts
Labels: bug

#1948 Fix: update country list source
  src/assets/countries/all.json
  src/assets/countries/regions.json
  src/assets/icons/unknown-flag.jpeg
  src/components/ActivityCountries.tsx
  src/components/CountrySelector/Options.tsx
  src/components/CountrySelector/index.tsx
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Admin/Charity/EditProfile/types.ts
  src/pages/Marketplace/Sidebar/Regions.tsx
  src/pages/Registration/Steps/Documentation/schema.ts
  src/pages/Registration/types.ts
  src/services/countries.ts
  src/services/types.ts
  src/slices/donation/types.ts
  src/store/store.ts
  src/types/countries.ts
Labels: bug

#1949 Add polygon in launchpad flow
  README.md
  src/assets/icons/currencies/matic.svg
  src/pages/Launchpad/Fees/index.tsx
  src/pages/Launchpad/Layout.tsx
  src/pages/Launchpad/Management/MemberForm.tsx
  src/pages/Launchpad/Maturity/Form/AddForm.tsx
  src/pages/Launchpad/New.tsx
  src/pages/Launchpad/Progress.tsx
  src/pages/Launchpad/Start.tsx
  src/pages/Launchpad/Summary/index.tsx
  src/pages/Launchpad/Whitelists/AddressForm.tsx
  src/pages/Launchpad/common/NetworkIcon.tsx
  src/pages/Launchpad/constants.ts
  src/pages/Launchpad/index.tsx
  src/schemas/string.ts
  src/slices/launchpad/launchpad.ts
  src/slices/launchpad/types.ts
Labels: good first issue

#1951 HOT FIX: Endow Designations & Marketplace Filters
  src/pages/Marketplace/Sidebar/Designations.tsx
  src/pages/Marketplace/Sidebar/index.tsx
  src/slices/components/marketFilter/constants.ts
  src/types/aws/ap/index.ts
Labels: bug

#1958 Register link added to Header menu
  src/App/Header/DesktopNav.tsx
  src/App/Header/MobileNav/Menu/Links.tsx
Labels: enhancement

#1960 Update deps
  package.json
  yarn.lock
Labels: dependencies

#1961 FIX: redundant max buttons on token-field (gift-purchase)
  src/components/TokenField/Steps.tsx
Labels: bug

#1885 Create AIF Permissions page
  src/components/TableSection.tsx
  src/constants/routes.ts
  src/contracts/SettingsController.ts
  src/helpers/admin/getPayloadDiff.test.ts
  src/helpers/admin/getPayloadDiff.ts
  src/helpers/admin/getTagPayloads.ts
  src/helpers/getTypedKeys.ts
  src/helpers/index.ts
  src/index.css
  src/pages/Admin/Charity/Permissions/Form.tsx
  src/pages/Admin/Charity/Permissions/LockButton.tsx
  src/pages/Admin/Charity/Permissions/MobileTable.tsx
  src/pages/Admin/Charity/Permissions/Permissions.tsx
  src/pages/Admin/Charity/Permissions/Table.tsx
  src/pages/Admin/Charity/Permissions/createUpdateEndowmentControllerMsg.ts
  src/pages/Admin/Charity/Permissions/index.ts
  src/pages/Admin/Charity/Permissions/schema.ts
  src/pages/Admin/Charity/Permissions/types.ts
  src/pages/Admin/Charity/Permissions/useSubmit.ts
  src/pages/Admin/Charity/Permissions/useTableData.ts
  src/pages/Admin/Charity/Permissions/useUserAuthorization.ts
  src/pages/Admin/Charity/index.tsx
  src/pages/Admin/constants.ts
  src/pages/Admin/types.ts
  src/services/juno/queryContract/queryObjects.ts
  src/services/juno/queryContract/types.ts
  src/services/juno/settingsController.ts
  src/services/juno/tags.ts
  src/types/contracts/index.ts
  src/types/contracts/settingsController.ts
Labels: enhancement

#1959 FIX: NPO Type changes
  src/pages/Marketplace/Cards/Card.tsx
  src/pages/Marketplace/Sidebar/Designations.tsx
  src/pages/Profile/Body/Body.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/EndowDesignationTag.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/Tags.tsx
  src/slices/components/marketFilter/constants.ts
  src/types/aws/ap/index.ts
Labels: bug, enhancement

#1963 Rename `Documentation.level` to `tier` to align with other types
  src/pages/Registration/Steps/Dashboard/index.tsx
  src/pages/Registration/Steps/Documentation/index.tsx
  src/pages/Registration/Steps/Documentation/types.ts
  src/pages/Registration/Steps/getRegistrationState.ts
  src/pages/Registration/types.ts
  src/types/aws/ap/index.ts
Labels: refactor

#1968 wallet admin list should be scrollable
  src/components/WalletSuite/ConnectedWallet/Details/MyEndowments/MyEndowments.tsx
Labels: bug, good first issue, design

#1976 Footer header link fixes
  src/App/Footer/constants.ts
  src/App/Header/DesktopNav.tsx
  src/App/Header/MobileNav/Menu/Links.tsx
Labels: bug, enhancement

#1967 Update/refactor Register Signup page layout to match Figma
  src/pages/Registration/Signup/Form.tsx
Labels: design, refactor

#1964 Set appropriate `endow_designation` fields' types to `EndowDesignation`
  src/constants/common.ts
  src/pages/Admin/Charity/EditProfile/getEndowDesignationLabelValuePair.ts
  src/pages/Marketplace/Sidebar/Designations.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/EndowDesignationTag.tsx
  src/types/aws/ap/index.ts
Labels: refactor

#1979 Fix img size bug
  src/components/ImgEditor/ImgCropper.tsx
  src/components/ImgEditor/ImgEditor.tsx
  src/components/ImgEditor/useImgEditor.ts
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Registration/Steps/Documentation/schema.ts
  src/schemas/file.ts
Labels: bug

#1980 Create generic `useTxSender`
  src/App/Header/Airdrop/useClaimAirdrop.ts
  src/helpers/tx/index.ts
  src/helpers/tx/sendTx/getWasmAttribute.ts
  src/helpers/tx/sendTx/sendCosmosTx.ts
  src/hooks/useTxSender.ts
  src/pages/Admin/Charity/EditProfile/useEditProfile.ts
  src/pages/Admin/Charity/Invest/Investor/useSubmit.ts
  src/pages/Admin/Charity/Templates/account/EndowmentStatus/useUpdateStatus.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/useLogWithdrawProposal.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/useWithdraw.ts
  src/pages/Admin/Charity/common/Investment/Investor/useSubmit.ts
  src/pages/Admin/Charity/common/Investment/Redeemer/useSubmit.ts
  src/pages/Admin/Core/Templates/index-fund/Alliance/useEditAlliance.ts
  src/pages/Admin/Core/Templates/index-fund/Config/useConfigureFund.ts
  src/pages/Admin/Core/Templates/index-fund/CreateFund/useCreateFund.ts
  src/pages/Admin/Core/Templates/index-fund/IndexFundOwner/useUpdateOwner.ts
  src/pages/Admin/Core/Templates/index-fund/Members/useUpdateFund.ts
  src/pages/Admin/Core/Templates/index-fund/RemoveFund/useDestroyFund.ts
  src/pages/Admin/Core/Templates/registrar/ConfigExtension/useConfigureRegistrar.ts
  src/pages/Admin/Core/Templates/registrar/Owner/useUpdateOwner.ts
  src/pages/Admin/Proposal/PollAction.tsx
  src/pages/Admin/Proposal/Voter/useVote.ts
  src/pages/Admin/Review/Templates/ReviewCW3Configurer/useCreateProposal.ts
  src/pages/Admin/templates/cw3/Config/useCreateProposal.ts
  src/pages/Admin/templates/cw3/FundSender/Form/useTransferFunds.ts
  src/pages/Admin/templates/cw4/Members/useUpdateMembers.ts
  src/pages/Launchpad/Summary/useSubmit/index.ts
  src/types/tx.ts
Labels: enhancement

#1953 fix Ui changes as per figma design
  src/App/Header/Airdrop/Catcher.tsx
  src/components/KadoModal.tsx
  src/components/Prompt/Prompt.tsx
  src/components/WalletSuite/ConnectedWallet/Details/AdminLinks.tsx
  src/components/WalletSuite/ConnectedWallet/Details/Favourites/index.tsx
  src/components/WalletSuite/ConnectedWallet/Details/MobileTitle.tsx
  src/components/WalletSuite/ConnectedWallet/Details/MyEndowments/MyEndowments.tsx
  src/components/WalletSuite/WalletSelectorOpener/WalletModal.tsx
  src/components/donation/Steps/Donater/Form/index.tsx
  src/components/donation/Steps/Result/Err.tsx
  src/components/donation/Steps/Result/Success/index.tsx
  src/contexts/ErrorContext/InstallWalletContent.tsx
  src/index.css
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/WidgetConfigurer/WidgetConfigurer.tsx
  src/pages/Admin/Charity/WidgetConfigurer/WidgetExample/WidgetExample.tsx
  src/pages/Admin/Proposal/index.tsx
  src/pages/Donate/Content.tsx
  src/pages/DonateWidget/InnerComponent.tsx
  src/pages/Donations/Filter/Form.tsx
  src/pages/Donations/NoDonations.tsx
  src/pages/Donations/index.tsx
  src/pages/Gift/Claim/Form.tsx
  src/pages/Gift/Mailer/Form.tsx
  src/pages/Gift/Mailer/Success.tsx
  src/pages/Gift/Purchase/Result/Err.tsx
  src/pages/Gift/Purchase/Result/Success.tsx
  src/pages/Gift/Purchase/index.tsx
  src/pages/Leaderboard/index.tsx
  src/pages/Marketplace/Cards/Card.tsx
  src/pages/Marketplace/Sidebar/index.tsx
  src/pages/Profile/Body/Body.tsx
  src/pages/Registration/ConfirmEmail.tsx
  src/pages/Registration/Resume/Form.tsx
  src/pages/Registration/Signup/Form.tsx
  src/pages/Registration/Steps/ContactDetails/Form/index.tsx
  src/pages/Registration/Steps/Dashboard/index.tsx
  src/pages/Registration/Steps/WalletRegistration/ChooseWallet/index.tsx
  src/pages/Registration/Steps/WalletRegistration/RegisteredWallet.tsx
  src/pages/Registration/Steps/WalletRegistration/WalletSubmission.tsx
  src/pages/Registration/Success.tsx
  src/pages/Registration/VerifiedEmail.tsx
Labels: design

#1986 Update URL scheme to accept any valid http(s) URL
  src/schemas/__tests__/string.test.ts
  src/schemas/string.ts
Labels: bug, enhancement

#1972 Submit polygon AST to AWS
  src/constants/evm.ts
  src/contracts/evm/Account/abi.json
  src/contracts/evm/Account/index.ts
  src/contracts/evm/ERC20/abi.json
  src/contracts/evm/ERC20/index.ts
  src/helpers/tx/estimateTx/estimateCosmosFee.ts
  src/helpers/tx/estimateTx/estimateEVMfee.ts
  src/helpers/tx/estimateTx/estimateTx.ts
  src/helpers/tx/sendTx/sendEVMTx.ts
  src/helpers/tx/sendTx/sendTx.ts
  src/hooks/useTxSender.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/useWithdraw.ts
  src/pages/Gift/Purchase/Submit/estimateTx.ts
  src/pages/Launchpad/Summary/useSubmit/index.ts
  src/slices/gift/purchase.ts
  src/types/evm.ts
  src/types/tx.ts
Labels: enhancement, good first issue

#1988 Verify only uploaded (pre-crop) image size
  src/components/ImgEditor/ImgEditor.tsx
  src/components/ImgEditor/types.ts
  src/components/ImgEditor/useImgEditor.ts
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/EditProfile/schema.ts
Labels: enhancement

#1985 Removed the duplicate "Crop" button
  src/components/ImgEditor/ImgEditor.tsx
Labels: bug

#1998 Fix url validation
  src/schemas/__tests__/string.test.ts
  src/schemas/string.ts
Labels: bug, priority

#1987 add chain type in network error
  src/errors/errors.ts
Labels: bug

#2001 Fix Gift card prompt overflows when message is long
  src/pages/Gift/Purchase/Result/Err.tsx
  src/pages/Gift/Purchase/Result/index.tsx
  src/slices/gift/index.ts
  src/slices/gift/purchase.ts
Labels: bug

#2002 Fx: tx-sender residual error
  src/pages/Admin/Charity/Permissions/useSubmit.ts
Labels: bug

#1997 Fix: sdg limits and select-all + UI fixes
  src/components/Selector.tsx
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/EditProfile/types.ts
  src/pages/Admin/Charity/WidgetConfigurer/WidgetUrlGenerator/DenomSelector.tsx
  src/pages/Registration/Steps/Documentation/Form/index.tsx
  src/pages/Registration/Steps/Documentation/Form/useSubmit.ts
  src/pages/Registration/types.ts
  src/types/aws/ap/registration.ts
Labels: bug

#2009 Popup to prompt
  src/components/BookmarkBtn.tsx
  src/components/ImgEditor/useImgEditor.ts
  src/components/KYC/Form/useSubmit.ts
  src/components/Popup.tsx
  src/hooks/useTxSender.ts
  src/pages/Admin/Charity/Templates/account/EndowmentStatus/useUpdateStatus.ts
  src/pages/Admin/Core/Templates/index-fund/Alliance/useEditAlliance.ts
  src/pages/Admin/Core/Templates/index-fund/Config/useConfigureFund.ts
  src/pages/Admin/Core/Templates/index-fund/IndexFundOwner/useUpdateOwner.ts
  src/pages/Admin/Core/Templates/index-fund/RemoveFund/useDestroyFund.ts
  src/pages/Admin/Core/Templates/registrar/ConfigExtension/useConfigureRegistrar.ts
  src/pages/Admin/Core/Templates/registrar/Owner/useUpdateOwner.ts
  src/pages/Admin/Review/Templates/ReviewCW3Configurer/useCreateProposal.ts
  src/pages/Admin/templates/cw3/Config/useCreateProposal.ts
  src/pages/Admin/templates/cw3/FundSender/Form/useTransferFunds.ts
  src/pages/Admin/templates/cw4/Members/useUpdateMembers.ts
  src/pages/Registration/ConfirmEmail.tsx
  src/pages/Registration/VerifiedEmail.tsx
Labels: enhancement, design

#2011 Add back ChainQueryArgs to services/types
  .github/workflows/javascript.yml
  src/components/ImgEditor/ImgEditor.tsx
  src/services/types.ts
Labels: bug

#2012 disable button hover if button disabled
  src/components/ImgEditor/ImgEditor.tsx
  src/components/donation/BtnOutline.tsx
  src/components/donation/BtnSec.tsx
  src/components/gift/BtnOutline.tsx
  src/components/gift/BtnSec.tsx
  src/components/registration/BtnSec.tsx
  src/index.css
  src/pages/Donations/LoadMoreBtn.tsx
Labels: bug

#2008 Endowment Widget Fixes
  src/App/Header/MobileNav/Menu/AdminMobileNavPortal.tsx
  src/pages/Admin/Charity/Nav.tsx
  src/pages/Admin/Charity/WidgetConfigurer/WidgetUrlGenerator/EndowmentCombobox/Combobox.tsx
Labels: bug

#2015 sync footer links with marketing site
  src/App/Footer/Links.tsx
  src/App/Footer/constants.ts
Labels: bug

#2018 Add Light theme logo to admin sidebar
  src/assets/images/angelgiving-H-logo-beta-blu.svg
  src/constants/common.ts
  src/pages/Admin/Sidebar/Header/Header.tsx
  src/pages/Admin/templates/cw3/Config/useCreateProposal.ts
Labels: bug, design

#2013 Replace `img` uses with `/components/Image` component
  src/App/Header/MobileNav/Menu.tsx
  src/App/Header/index.tsx
  src/components/Image/Image.tsx
  src/components/ImageWrapper.tsx
  src/components/ImgEditor/ImgCropper.tsx
  src/components/LazyImage/Observer.tsx
  src/components/LazyImage/index.tsx
  src/components/TokenField/TokenSelector.tsx
  src/components/WalletSuite/ConnectedWallet/Details/Balances/CoinBalances.tsx
  src/components/WalletSuite/ConnectedWallet/Details/Favourites/Favourite.tsx
  src/components/WalletSuite/ConnectedWallet/Details/MyEndowments/MyEndowments.tsx
  src/components/WalletSuite/WalletSelectorOpener/Connector.tsx
  src/components/donation/Steps/Submit/index.tsx
  src/contexts/ErrorContext/InstallWalletContent.tsx
  src/pages/Admin/Charity/Holdings.tsx
  src/pages/Admin/Charity/WidgetConfigurer/WidgetExample/WidgetExample.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Amounts.tsx
  src/pages/Admin/Core/Templates/index-fund/Alliance/AllianceSelection/Member.tsx
  src/pages/Admin/Proposal/Content/Preview/AllianceUpdate.tsx
  src/pages/Admin/Proposal/Content/Preview/DiffTable.tsx
  src/pages/Admin/Proposal/Content/Preview/Withdraw.tsx
  src/pages/Admin/Sidebar/Header/CharityHeader.tsx
  src/pages/Admin/Sidebar/Header/Header.tsx
  src/pages/Admin/templates/cw3/FundSender/Form/Denom.tsx
  src/pages/DonateWidget/InnerComponent.tsx
  src/pages/Donations/NoDonations.tsx
  src/pages/Gift/Purchase/Submit/index.tsx
  src/pages/Launchpad/common/NetworkIcon.tsx
  src/pages/Leaderboard/Table/Row/index.tsx
  src/pages/Marketplace/Cards/Card.tsx
  src/pages/Marketplace/Hero.tsx
  src/pages/Profile/index.tsx
  src/pages/Registration/Steps/WalletRegistration/ChooseWallet/KeplrConnector.tsx
  src/pages/Registration/Steps/WalletRegistration/WalletSubmission.tsx
Labels: refactor
