Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2023-04, with the labels that each got.

#2026 AST to submit in polygon only
  src/contracts/Account.ts
  src/pages/Admin/Review/Applications/__tests__/Applications.test.tsx
  src/pages/Launchpad/Fees/index.tsx
  src/pages/Launchpad/Layout.tsx
  src/pages/Launchpad/Management/MemberForm.tsx
  src/pages/Launchpad/Maturity/Form/AddForm.tsx
  src/pages/Launchpad/New.tsx
  src/pages/Launchpad/Start.tsx
  src/pages/Launchpad/Summary/index.tsx
  src/pages/Launchpad/Summary/useSubmit/index.ts
  src/pages/Launchpad/Summary/useSubmit/toJunoAIF.ts
  src/pages/Launchpad/Whitelists/AddressForm.tsx
  src/pages/Launchpad/common/NetworkIcon.tsx
  src/pages/Launchpad/constants.ts
  src/pages/Launchpad/index.tsx
  src/slices/launchpad/launchpad.ts
  src/slices/launchpad/types.ts
  src/types/contracts/account.ts
Labels: refactor

#2028 Remove 'locked' tab for normal/AST endows
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/useWithdraw.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/index.tsx
  src/pages/Admin/Charity/common/AccountTabs.tsx
Labels: enhancement

#2033 rebuild yarn.lock; fix build error;
  src/services/juno/tags.ts
  yarn.lock
Labels: bug

#2020 Field error border addition
  src/components/CountrySelector/index.tsx
  src/components/Selector.tsx
  src/components/TokenField/TokenField.tsx
  src/components/form/Field.tsx
  src/components/registration/FileDropzone.tsx
  src/index.css
  src/pages/Admin/Charity/common/Investment/Redeemer/Amount.tsx
Labels: design

#2038 Fix: yarn errors
  .yarnrc.yml
  package.json
  src/services/juno/tags.ts
  yarn.lock
Labels: bug, dependencies

#2040 Multisig member templates aligned to polygon contract functionality
  src/pages/Admin/Proposal/Content/Preview/CWMemberUpdate.tsx
  src/pages/Admin/Proposal/Content/Preview/common/MemberItem.tsx
  src/pages/Admin/Proposal/Content/Preview/index.tsx
  src/pages/Admin/templates/cw4/Members/Adder/index.tsx
  src/pages/Admin/templates/cw4/Members/Adder/schema.ts
  src/pages/Admin/templates/cw4/Members/Adder/types.ts
  src/pages/Admin/templates/cw4/Members/Adder/useAddMember.ts
  src/pages/Admin/templates/cw4/Members/Adder/useUpdateMembers.ts
  src/pages/Admin/templates/cw4/Members/Form.tsx
  src/pages/Admin/templates/cw4/Members/Member.tsx
  src/pages/Admin/templates/cw4/Members/index.ts
  src/pages/Admin/templates/cw4/Members/index.tsx
  src/pages/Admin/templates/cw4/Members/schema.ts
  src/pages/Admin/templates/cw4/Members/useUpdateMembers.ts
  src/pages/Admin/types.ts
  src/schemas/tests.ts
  src/services/juno/custom/custom.ts
  src/services/juno/custom/helpers/admin-resource.ts
  src/services/juno/queryContract/queryObjects.ts
  src/services/juno/queryContract/types.ts
  src/services/types.ts
  src/slices/admin/apCW4Members.ts
  src/slices/admin/index.ts
  src/slices/admin/types.ts
  src/types/contracts/common.ts
Labels: refactor

#2039 Fix: web3-auth bugs and trim deps
  .yarnrc.yml
  package.json
  src/contexts/WalletContext/WalletContext.tsx
  src/contexts/WalletContext/constants.ts
  src/contexts/WalletContext/types.ts
  src/contexts/WalletContext/useWeb3Auth/index.ts
  src/contexts/WalletContext/useWeb3Auth/web3AuthConfigs.ts
  src/contexts/WalletContext/useWeb3Auth/web3AuthSetup.ts
  src/contexts/WalletContext/useWeb3Auth/web3RPC.ts
  src/helpers/evm/evm.ts
  src/pages/Registration/Steps/WalletRegistration/WalletSubmission.tsx
  src/types/lists.ts
  yarn.lock
Labels: bug, dependencies

#2045 Add try/catch + error prompt to WalletSuite > DisconnectBtn
  src/components/WalletSuite/ConnectedWallet/Details/index.tsx
Labels: enhancement, good first issue

#2046 Add margin to privacy note
  src/pages/Registration/Signup/Form.tsx
Labels: bug

#2051 add wording to proof of identity
  src/pages/Registration/Steps/Documentation/Form/index.tsx
Labels: bug

#2056 Is ast route change
  src/App/App.tsx
  src/App/Header/index.tsx
  src/App/Layout.tsx
  src/constants/common.ts
  src/pages/Profile/PageError.tsx
Labels: enhancement

#2059 Remove unused `appRoutes.index`
  src/constants/routes.ts
Labels: refactor

#2047 Align proposal(s) page to polygon functionalities
  src/components/Icon/icons.ts
  src/components/admin/Status.tsx
  src/contracts/createTx/txs.ts
  src/contracts/createTx/types.ts
  src/contracts/evm/multisig/abi.json
  src/helpers/tx/estimateTx/estimateEVMfee.ts
  src/pages/Admin/Charity/Dashboard/Table.tsx
  src/pages/Admin/Charity/Dashboard/index.tsx
  src/pages/Admin/Charity/Withdraws/OpenRequestsInfo.tsx
  src/pages/Admin/Charity/Withdraws/Transactions/Status.tsx
  src/pages/Admin/Proposal/Content/index.tsx
  src/pages/Admin/Proposal/PollAction.tsx
  src/pages/Admin/Proposal/Stats.tsx
  src/pages/Admin/Proposal/Votes/index.tsx
  src/pages/Admin/Proposal/Votes/useVotesList.ts
  src/pages/Admin/Proposal/index.tsx
  src/pages/Admin/Proposals/ProposalCard.tsx
  src/pages/Admin/Proposals/Toolbar/StatusSelector.tsx
  src/pages/Admin/Proposals/Toolbar/index.tsx
  src/pages/Admin/Proposals/index.tsx
  src/pages/Admin/Proposals/useFilteredProposals.ts
  src/services/juno/custom/custom.ts
  src/services/juno/queryContract/index.ts
  src/services/juno/queryContract/placeholders.ts
  src/services/juno/queryContract/queryObjects.ts
  src/services/juno/queryContract/types.ts
  src/services/types.ts
  src/slices/admin/proposals.ts
  src/slices/admin/types.ts
  src/types/contracts/cw3/index.ts
Labels: refactor

#2060 Update headers and footer links for AST
  src/App/Layout.tsx
  src/App/constants.ts
Labels: enhancement

#2061 Registration updates for polygon
  src/pages/Registration/Steps/Dashboard/index.tsx
  src/pages/Registration/Steps/WalletRegistration/useRegisterWallet.ts
  src/pages/Registration/Steps/getRegistrationState.ts
  src/services/aws/registration/registration.ts
  src/types/aws/ap/registration.ts
Labels: bug

#2057 Alliance members edit UI for polygon
  src/contracts/IndexFund.ts
  src/pages/Admin/Core/Templates/index-fund/Alliance/Alliance.tsx
  src/pages/Admin/Core/Templates/index-fund/Alliance/AllianceSelection/Member.tsx
  src/pages/Admin/Core/Templates/index-fund/Alliance/AllianceSelection/Toolbar.tsx
  src/pages/Admin/Core/Templates/index-fund/Alliance/AllianceSelection/index.tsx
  src/pages/Admin/Core/Templates/index-fund/Alliance/AllianceSelection/useAllianceSelection.ts
  src/pages/Admin/Core/Templates/index-fund/Alliance/AllianceSelection/useMember.ts
  src/pages/Admin/Core/Templates/index-fund/Alliance/Editor/index.tsx
  src/pages/Admin/Core/Templates/index-fund/Alliance/Editor/schema.ts
  src/pages/Admin/Core/Templates/index-fund/Alliance/Editor/types.ts
  src/pages/Admin/Core/Templates/index-fund/Alliance/Editor/useUpdateMembers.ts
  src/pages/Admin/Core/Templates/index-fund/Alliance/Form.tsx
  src/pages/Admin/Core/Templates/index-fund/Alliance/Member.tsx
  src/pages/Admin/Core/Templates/index-fund/Alliance/MemberEditor/index.tsx
  src/pages/Admin/Core/Templates/index-fund/Alliance/MemberEditor/useEditMember.ts
  src/pages/Admin/Core/Templates/index-fund/Alliance/index.ts
  src/pages/Admin/Core/Templates/index-fund/Alliance/index.tsx
  src/pages/Admin/Core/Templates/index-fund/Alliance/schema.ts
  src/pages/Admin/Core/Templates/index-fund/Alliance/useEditAlliance.ts
  src/pages/Admin/Proposal/Content/Preview/AllianceUpdate.tsx
  src/pages/Admin/Proposal/Content/Preview/index.tsx
  src/pages/Admin/types.ts
  src/services/juno/queryContract/queryObjects.ts
  src/services/juno/queryContract/types.ts
  src/slices/admin/allianceMembers.ts
  src/slices/admin/index.ts
  src/slices/admin/types.ts
  src/types/contracts/indexfund.ts
Labels: good first issue, refactor

#2070 Admin fixes
  src/pages/Admin/Core/Nav.tsx
  src/pages/Admin/Proposal/Voter/useVote.ts
Labels: bug, priority

#2073 RC-v1.8: cherry fixes
  src/helpers/tx/sendTx/sendEVMTx.ts
  src/pages/Launchpad/Summary/useSubmit/toEVMAIF.ts
Labels: bug, priority

#2075 Replace Image component
  src/pages/Marketplace/Cards/Card.tsx
Labels: bug, design

#2074 Multisig updates
  src/components/admin/Status.tsx
  src/contracts/CW3/CW3Review.ts
  src/contracts/CW3/index.ts
  src/contracts/createTx/txs.ts
  src/contracts/createTx/types.ts
  src/contracts/evm/multisig/index.ts
  src/contracts/evm/multisig/queries.json
  src/contracts/evm/multisig/txs.json
  src/helpers/admin/getTagPayloads.ts
  src/helpers/tx/sendTx/sendEVMTx.ts
  src/pages/Admin/Charity/Dashboard/Table.tsx
  src/pages/Admin/Charity/Withdraws/OpenRequestsInfo.tsx
  src/pages/Admin/Charity/Withdraws/Transactions/Status.tsx
  src/pages/Admin/Proposal/Content/index.tsx
  src/pages/Admin/Proposal/PollAction.tsx
  src/pages/Admin/Proposal/Voter/useVote.ts
  src/pages/Admin/Proposal/Votes/index.tsx
  src/pages/Admin/Proposal/index.tsx
  src/pages/Admin/Proposals/ProposalCard.tsx
  src/pages/Admin/Review/Applications/__tests__/Applications.test.tsx
  src/pages/Admin/Review/Templates/ReviewCW3Configurer/Form.tsx
  src/pages/Admin/Review/Templates/ReviewCW3Configurer/index.tsx
  src/pages/Admin/Review/Templates/ReviewCW3Configurer/schema.ts
  src/pages/Admin/Review/Templates/ReviewCW3Configurer/useCreateProposal.ts
  src/pages/Admin/Review/Templates/index.tsx
  src/pages/Admin/templates/cw3/Config/Form.tsx
  src/pages/Admin/templates/cw3/Config/index.tsx
  src/pages/Admin/templates/cw3/Config/schema.ts
  src/pages/Admin/templates/cw3/Config/types.ts
  src/pages/Admin/templates/cw3/Config/useCreateProposal.ts
  src/pages/Launchpad/Summary/useSubmit/toEVMAIF.ts
  src/schemas/number.ts
  src/services/juno/custom/custom.ts
  src/services/juno/custom/helpers/admin-resource.ts
  src/services/juno/queryContract/decoded-types.ts
  src/services/juno/queryContract/placeholders.ts
  src/services/juno/queryContract/queryObjects.ts
  src/services/juno/queryContract/types.ts
  src/services/juno/tags.ts
  src/services/types.ts
  src/slices/admin/types.ts
  src/types/aws/apes/index.ts
  src/types/contracts/cw3/index.ts
  src/types/contracts/evm/multisig.ts
  src/types/lists.ts
Labels: enhancement, refactor

#2077 Minor fixes from CU
  src/assets/images/angelprotocol-H-logo-beta-wht.svg
  src/components/WalletSuite/ConnectedWallet/Details/MyEndowments/MyEndowments.tsx
  src/constants/env.ts
  src/constants/routes.ts
  src/contracts/createTx/types.ts
  src/pages/Admin/Charity/index.tsx
  src/pages/Admin/constants.ts
  src/pages/Donate/Content.tsx
  src/pages/Donate/index.tsx
  src/pages/Donations/NoDonations.tsx
  src/pages/Donations/index.tsx
  src/pages/Launchpad/About/Form.tsx
  src/pages/Launchpad/Fees/Form.tsx
  src/pages/Launchpad/Management/Form.tsx
  src/pages/Launchpad/Management/Members.tsx
  src/pages/Launchpad/Maturity/Form/index.tsx
  src/pages/Launchpad/Splits/Form/index.tsx
  src/pages/Launchpad/Start.tsx
  src/pages/Launchpad/Success.tsx
  src/pages/Launchpad/Summary/Management.tsx
  src/pages/Launchpad/Summary/Maturity.tsx
  src/pages/Launchpad/Summary/Whitelists.tsx
  src/pages/Launchpad/Summary/index.tsx
  src/pages/Launchpad/Summary/useSubmit/index.ts
  src/pages/Launchpad/Summary/useSubmit/toEVMAST.ts
  src/pages/Launchpad/Whitelists/Form.tsx
  src/services/aws/aws.ts
  src/types/aws/ap/index.ts
  src/types/contracts/evm/account.ts
Labels: bug, enhancement, good first issue

#2078 Show ast profile and edit profile
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Admin/Charity/EditProfile/types.ts
  src/pages/Admin/Charity/EditProfile/useEditProfile.ts
  src/pages/Donate/index.tsx
  src/pages/DonateWidget/DonateWidget.tsx
  src/pages/DonateWidget/EndowmentLoader.tsx
  src/pages/Profile/Body/Body.tsx
  src/pages/Profile/Body/GeneralInfo/Content/Content.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/Details.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/DetailsColumn.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/EndowDesignationTag.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/Socials.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/Tags.tsx
  src/pages/Profile/ProfileContext.ts
  src/pages/Profile/index.tsx
  src/services/aws/aws.ts
  src/services/types.ts
  src/types/aws/ap/index.ts
Labels: good first issue, refactor

#2079 More payment wording fixes
  public/index.html
  src/components/donation/Steps/CurrentStep.tsx
  src/components/donation/Steps/Donater/Form/AdvancedOptions.tsx
  src/components/donation/Steps/Progress.tsx
  src/components/donation/Steps/Result/Success/Share.tsx
  src/components/donation/Steps/Result/Success/index.tsx
  src/constants/env.ts
  src/pages/Admin/Charity/WidgetConfigurer/WidgetConfigurer.tsx
  src/pages/Admin/Charity/WidgetConfigurer/WidgetExample/WidgetExample.tsx
  src/pages/DonateFiat/index.tsx
  src/pages/DonateWidget/InnerComponent.tsx
  src/pages/Profile/Body/DonateButton.tsx
Labels: bug

#2080 Evm edit profile
  src/contexts/WalletContext/useInjectedProvider.ts
  src/contexts/WalletContext/useWeb3Auth/index.ts
  src/contexts/WalletContext/wallet-connect/useEVMWC.ts
  src/pages/Admin/Charity/EditProfile/createADR36Payload.ts
  src/pages/Admin/Charity/EditProfile/useEditProfile.ts
  src/services/aws/aws.ts
  src/types/aws/ap/index.ts
  src/types/utils.ts
Labels: bug, refactor

#2081 Mor fixes pt3
  public/index.html
  src/App/Footer/Footer.tsx
  src/components/WalletSuite/ConnectedWallet/Details/index.tsx
  src/pages/Admin/Charity/Dashboard/index.tsx
  src/pages/Donate/Content.tsx
  src/pages/DonateFiat/Content.tsx
  src/pages/Profile/Body/Body.tsx
Labels: bug

#2082 Charity application proposal save to AWS
  src/contracts/evm/multisig/events.json
  src/contracts/evm/multisig/index.ts
  src/pages/Admin/Review/Application/Summary/Proposer.tsx
  src/pages/Admin/Review/Application/Summary/Summary.tsx
  src/types/aws/ap/registration.ts
Labels: refactor

#2087 Permissions: Hide governance column
  src/pages/Admin/Charity/Permissions/MobileTable.tsx
  src/pages/Admin/Charity/Permissions/Table.tsx
Labels: enhancement

#2083 Charity registration fixes in v1.8
  src/pages/Registration/Steps/Documentation/Form/index.tsx
  src/pages/Registration/Steps/WalletRegistration/ChooseWallet/WalletConnector.tsx
  src/pages/Registration/Steps/WalletRegistration/ChooseWallet/index.tsx
Labels: bug

#2084 AST investments placeholder
  src/pages/Admin/Charity/Invest/Strategy.tsx
  src/pages/Admin/Charity/Invest/strats.ts
Labels: bug

#2086 AST temp header nav
  src/App/constants.ts
  src/constants/common.ts
Labels: bug, enhancement

#2092 Add Polygon to Kado modal buy options
  src/components/KadoModal.tsx
Labels: enhancement

#2093 Set `angelprotocol-rounded-logo.png` as placeholder logo for new ASTs
  src/pages/Launchpad/Summary/useSubmit/toEVMAST.ts
  src/types/contracts/evm/account.ts
Labels: enhancement

#2089 Wallet Modal Ordering
  src/contexts/WalletContext/WalletContext.tsx
Labels: design

#2090 Adjust permissions rules
  src/pages/Admin/Charity/Permissions/Form.tsx
  src/pages/Admin/Charity/Permissions/MobileTable.tsx
  src/pages/Admin/Charity/Permissions/Table.tsx
  src/pages/Admin/Charity/Permissions/helpers/createUpdateEndowmentControllerMsg.ts
  src/pages/Admin/Charity/Permissions/helpers/getFieldErrorName.ts
  src/pages/Admin/Charity/Permissions/helpers/index.ts
  src/pages/Admin/Charity/Permissions/schema.ts
  src/pages/Admin/Charity/Permissions/useSubmit.ts
Labels: enhancement

#2101 AST unpublished & Bookmarks - RC-v1.8 cherry-pick
  src/components/BookmarkBtn.tsx
  src/pages/Profile/Unpublished.tsx
  src/pages/Profile/index.tsx
Labels: duplicate

#2102 V1.8 followup bugs
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/App/Header/DesktopNav.tsx
  src/App/Header/MobileNav/Menu.tsx
  src/pages/Admin/Charity/Invest/strats.ts
Labels: bug

#2106 Follow-up fixes: AST maturity optional
  src/components/form/constants.ts
  src/components/form/index.ts
  src/pages/Launchpad/Maturity/Form/index.tsx
  src/pages/Launchpad/Maturity/index.tsx
  src/pages/Launchpad/Summary/Maturity.tsx
  src/pages/Launchpad/Summary/useSubmit/toEVMAST.ts
  src/slices/launchpad/types.ts
Labels: bug, design

#2107 cleanup
  src/components/donation/Steps/CurrentStep.tsx
  src/components/donation/Steps/Donater/Form/index.tsx
  src/components/donation/Steps/Donater/index.tsx
  src/components/donation/Steps/Donater/schema.ts
  src/components/donation/Steps/FiatOnlyDonater/Form/AdvancedOptions.tsx
  src/components/donation/Steps/FiatOnlyDonater/Form/index.tsx
  src/components/donation/Steps/FiatOnlyDonater/index.tsx
  src/components/donation/Steps/FiatOnlyDonater/schema.ts
  src/components/donation/Steps/FiatOnlyDonater/types.ts
  src/components/donation/Steps/FiatSubmit/Form/PaymentOption.tsx
  src/components/donation/Steps/FiatSubmit/Form/getBreakdown.ts
  src/components/donation/Steps/FiatSubmit/Form/index.tsx
  src/components/donation/Steps/FiatSubmit/index.tsx
  src/components/donation/Steps/FiatSubmit/schema.ts
  src/components/donation/Steps/FiatSubmit/types.ts
  src/components/donation/Steps/Submit/estimateDonation.ts
  src/components/donation/Steps/Submit/index.tsx
  src/constants/fiatTransactions.ts
  src/constants/tokens.ts
  src/helpers/getFiatWidgetUrl.ts
  src/slices/donation/constants.ts
  src/slices/donation/index.ts
  src/slices/donation/sendDonation/index.ts
  src/slices/donation/types.ts
  src/types/aws/apes/index.ts
  src/types/slices.ts
Labels: refactor

#2108 V1.8 strategies - preliminary work & balances placeholders
  src/pages/Admin/Charity/Invest/Investor/AccountOptions.tsx
  src/pages/Admin/Charity/Invest/Investor/Form.tsx
  src/pages/Admin/Charity/Invest/Investor/index.tsx
  src/pages/Admin/Charity/Invest/Strategy.tsx
  src/pages/Admin/Charity/Invest/index.tsx
  src/pages/Admin/Charity/Invest/strats.ts
  src/types/aws/ap/index.ts
Labels: enhancement

#2105 Donate refactor v1.8
  src/App/App.tsx
  src/App/Header/index.tsx
  src/components/donation/Steps/CurrentStep.tsx
  src/components/donation/Steps/Donater/Form/index.tsx
  src/components/donation/Steps/Donater/index.tsx
  src/components/donation/Steps/Donater/schema.ts
  src/components/donation/Steps/Submit/estimateDonation.ts
  src/components/donation/Steps/Submit/index.tsx
  src/components/donation/Steps/index.tsx
  src/components/donationFiat/Steps/CurrentStep.tsx
  src/components/donationFiat/Steps/Donater/Form/AdvancedOptions.tsx
  src/components/donationFiat/Steps/Donater/Form/index.tsx
  src/components/donationFiat/Steps/Donater/index.tsx
  src/components/donationFiat/Steps/Donater/schema.ts
  src/components/donationFiat/Steps/Donater/types.ts
  src/components/donationFiat/Steps/FiatSubmit/Form/PaymentOption.tsx
  src/components/donationFiat/Steps/FiatSubmit/Form/getBreakdown.ts
  src/components/donationFiat/Steps/FiatSubmit/Form/index.tsx
  src/components/donationFiat/Steps/FiatSubmit/index.tsx
  src/components/donationFiat/Steps/FiatSubmit/schema.ts
  src/components/donationFiat/Steps/FiatSubmit/types.ts
  src/components/donationFiat/Steps/Progress.tsx
  src/components/donationFiat/Steps/index.tsx
  src/components/donationFiat/index.ts
  src/constants/fiatTransactions.ts
  src/constants/routes.ts
  src/constants/tokens.ts
  src/helpers/getFiatWidgetUrl.ts
  src/pages/Donate/Content.tsx
  src/pages/DonateFiat/Content.tsx
  src/pages/DonateFiat/index.tsx
  src/slices/donation/constants.ts
  src/slices/donation/index.ts
  src/slices/donation/sendDonation/index.ts
  src/slices/donation/types.ts
  src/types/aws/apes/index.ts
  src/types/slices.ts
Labels: bug, refactor

#2110 Admin ast switch button display ASTs Toggle
  src/pages/Admin/Sidebar/Header/CharityHeader.tsx
  src/pages/Admin/Sidebar/Header/MyEndowments.tsx
Labels: enhancement

#2109 Create "Other settings" page in AST admin
  src/components/KYC/Form/Tooltip.tsx
  src/components/form/Radio.tsx
  src/components/form/index.ts
  src/constants/routes.ts
  src/helpers/index.ts
  src/helpers/isEVM.ts
  src/hooks/useUpdateEndowmentProfile.ts
  src/index.css
  src/pages/Admin/Charity/ContributorVerification/ChangeSettingsPrompt.tsx
  src/pages/Admin/Charity/ContributorVerification/ContributorVerification.tsx
  src/pages/Admin/Charity/ContributorVerification/Message.tsx
  src/pages/Admin/Charity/ContributorVerification/index.ts
  src/pages/Admin/Charity/ContributorVerification/types.ts
  src/pages/Admin/Charity/EditProfile/types.ts
  src/pages/Admin/Charity/EditProfile/useEditProfile.ts
  src/pages/Admin/Charity/index.tsx
  src/pages/Admin/constants.ts
  src/pages/Marketplace/Sidebar/KYCFilter.tsx
  src/services/aws/aws.ts
  src/types/aws/ap/index.ts
  tailwind.config.js
Labels: enhancement, design, refactor

#2114 Launchpad summary raw message
  src/pages/Launchpad/Summary/Message.tsx
  src/pages/Launchpad/Summary/index.tsx
  src/pages/Launchpad/Summary/toEVMAST.ts
  src/pages/Launchpad/Summary/useSubmit.ts
Labels: good first issue, design

#2111 Query donations - v1.8
  src/pages/Admin/Charity/DonationsTable/DonationsTable.tsx
  src/pages/Donations/Filter/index.tsx
  src/pages/Donations/useDonations.ts
  src/services/apes/donations.ts
  src/slices/donation/sendDonation/logFiatDonation.ts
  src/types/aws/apes/donation.ts
Labels: bug, help wanted

#2113 Donate: Skip donation KYC step completely if required
  src/components/donation/Steps/Progress.tsx
  src/pages/Admin/Charity/Deposits/index.tsx
  src/pages/Donate/index.tsx
  src/pages/DonateWidget/DonateWidget.tsx
  src/pages/DonateWidget/InnerComponent.tsx
  src/slices/donation/donation.ts
  src/slices/donation/types.ts
Labels: enhancement

#2116 More fiddling with SmartLook
  public/index.html
Labels: bug

#2119 AST fixes
  src/pages/Admin/Charity/Permissions/schema.ts
  src/pages/Launchpad/Summary/toEVMAST.ts
Labels: bug

#2121 Edit Profile: Fix AST profile page description saying 'charity'
  src/pages/Admin/Charity/EditProfile/Form.tsx
Labels: bug, design

#2120 Custom Titles added for Admin pages
  src/constants/routes.ts
  src/pages/Admin/Charity/Account/index.tsx
  src/pages/Admin/Charity/Contributions.tsx
  src/pages/Admin/Charity/ContributorVerification/ContributorVerification.tsx
  src/pages/Admin/Charity/Dashboard/index.tsx
  src/pages/Admin/Charity/Deposits/index.tsx
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Admin/Charity/Invest/index.tsx
  src/pages/Admin/Charity/Permissions/Permissions.tsx
  src/pages/Admin/Charity/Seo.tsx
  src/pages/Admin/Charity/Templates/index.tsx
  src/pages/Admin/Charity/WidgetConfigurer/WidgetConfigurer.tsx
  src/pages/Admin/Charity/WidgetConfigurer/useWidgetConfigurer.ts
  src/pages/Admin/Charity/Withdraws/index.tsx
  src/pages/Admin/Core/Templates/index.tsx
  src/pages/Admin/Proposal/index.tsx
  src/pages/Admin/Proposals/index.tsx
  src/pages/Admin/Review/Application/Summary/Summary.tsx
  src/pages/Admin/Review/Applications/Table/AppRow.tsx
  src/pages/Admin/Review/Templates/index.tsx
  src/pages/Admin/Review/index.tsx
  src/pages/Admin/constants.ts
  src/pages/DonateWidget/DonateWidget.tsx
  src/pages/Launchpad/index.tsx
Labels: enhancement

#2122 Permissions fix
  src/pages/Admin/Charity/Permissions/helpers/createUpdateEndowmentControllerMsg.ts
Labels: bug
