Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2023-05, with the labels that each got.

#2123 CW3 cleanup
  src/contracts/CW3.ts
  src/contracts/CW3/CW3Review.ts
  src/contracts/createTx/types.ts
  src/pages/Admin/Charity/Dashboard/Table.tsx
  src/pages/Admin/Proposal/Content/index.tsx
  src/pages/Admin/Proposal/Voter/Form.tsx
  src/pages/Admin/Proposal/Voter/Reason.tsx
  src/pages/Admin/Proposal/Voter/VoteOption.tsx
  src/pages/Admin/Proposal/Voter/index.tsx
  src/pages/Admin/Proposal/Voter/schema.ts
  src/pages/Admin/Proposal/Voter/types.ts
  src/pages/Admin/Proposal/Voter/useVote.ts
  src/pages/Admin/Proposals/ProposalCard.tsx
  src/services/juno/custom/custom.ts
  src/services/juno/queryContract/types.ts
  src/services/types.ts
  src/types/contracts/cw3/endowment.ts
  src/types/contracts/cw3/index.ts
  src/types/contracts/cw3/review.ts
  src/types/contracts/index.ts
  src/types/contracts/multisig.ts
Labels: refactor

#2115 Add referral ID field
  src/pages/Launchpad/Fees/Fee.tsx
  src/pages/Launchpad/Fees/Form.tsx
  src/pages/Launchpad/Fees/index.tsx
  src/pages/Launchpad/Summary/Fees.tsx
  src/pages/Launchpad/Summary/index.tsx
  src/pages/Launchpad/Summary/toEVMAST.ts
  src/slices/launchpad/types.ts
  src/types/contracts/evm/account.ts
Labels: enhancement

#2126 Admin registrar owner template
  src/contracts/Registrar.ts
  src/contracts/createTx/txs.ts
  src/contracts/createTx/types.ts
  src/contracts/evm/registrar/abi/txs.json
  src/contracts/evm/registrar/index.ts
  src/pages/Admin/Core/Templates/registrar/Owner/schema.ts
  src/pages/Admin/Core/Templates/registrar/Owner/useUpdateOwner.ts
Labels: refactor

#2131 Fix: temp disable `referral_id`
  src/pages/Launchpad/Summary/toEVMAST.ts
  src/types/contracts/evm/account.ts
Labels: bug

#2135 Enable account details
  src/pages/Admin/Charity/common/Balances/Balance.tsx
Labels: refactor

#2133 Disable admin controll in permissions
  src/pages/Admin/Charity/Permissions/MobileTable.tsx
  src/pages/Admin/Charity/Permissions/Table.tsx
Labels: refactor

#2128 Charity Application bug fixes
  package.json
  src/constants/contracts.ts
  src/contracts/Registrar.ts
  src/contracts/createTx/txs.ts
  src/contracts/createTx/types.ts
  src/contracts/evm/registrar/abi/txs.json
  src/helpers/admin/getTagPayloads.ts
  src/pages/Admin/Charity/Permissions/helpers/createUpdateEndowmentControllerMsg.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/constructTx.test.ts
  src/pages/Admin/Core/Templates/registrar/ConfigExtension/Form.tsx
  src/pages/Admin/Core/Templates/registrar/ConfigExtension/index.tsx
  src/pages/Admin/Core/Templates/registrar/ConfigExtension/schema.ts
  src/pages/Admin/Core/Templates/registrar/ConfigExtension/types.ts
  src/pages/Admin/Core/Templates/registrar/ConfigExtension/useConfigureRegistrar.ts
  src/pages/Admin/Review/Application/Summary/Proposer.tsx
  src/pages/Admin/types.ts
  src/pages/Registration/Steps/Documentation/Form/index.tsx
  src/pages/Registration/Steps/WalletRegistration/WalletSubmission.tsx
  src/services/juno/queryContract/decoded-types.ts
  src/services/juno/queryContract/placeholders.ts
  src/services/juno/queryContract/queryObjects.ts
  src/services/juno/queryContract/types.ts
  src/services/juno/tags.ts
  src/types/contracts/account.ts
  src/types/contracts/common.ts
  src/types/contracts/multisig.ts
  src/types/contracts/registrar.ts
  src/types/utils.ts
  yarn.lock
Labels: bug, refactor

#2136 Multisig wallet transfer funds
  src/components/TokenField/TokenField.tsx
  src/components/TokenField/types.ts
  src/components/donation/Steps/Donater/Form/index.tsx
  src/components/donation/Steps/Donater/schema.ts
  src/helpers/admin/getTagPayloads.ts
  src/pages/Admin/Charity/Invest/Investor/Form.tsx
  src/pages/Admin/Charity/Invest/Investor/schema.ts
  src/pages/Admin/Charity/common/Investment/Investor/Form.tsx
  src/pages/Admin/Charity/common/Investment/Investor/schema.ts
  src/pages/Admin/Charity/common/Investment/Redeemer/schema.ts
  src/pages/Admin/templates/cw3/FundSender/Form/Amount.tsx
  src/pages/Admin/templates/cw3/FundSender/Form/Balance.tsx
  src/pages/Admin/templates/cw3/FundSender/Form/Denom.tsx
  src/pages/Admin/templates/cw3/FundSender/Form/index.tsx
  src/pages/Admin/templates/cw3/FundSender/Form/useTransferFunds.ts
  src/pages/Admin/templates/cw3/FundSender/index.tsx
  src/pages/Admin/templates/cw3/FundSender/schema.ts
  src/pages/Admin/templates/cw3/FundSender/types.ts
  src/pages/Gift/Purchase/Purchaser/Form/index.tsx
  src/pages/Gift/Purchase/Purchaser/schema.ts
  src/schemas/shape.ts
  src/services/apes/apes.ts
  src/services/apes/tags.ts
Labels: enhancement, refactor

#2138 Fix error parsing registration
  src/helpers/registration/handleMutationResult.ts
Labels: bug

#2139 Balances may be absent for new ASTs
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/Balances.tsx
  src/types/aws/ap/index.ts
Labels: bug

#2140 AST launchpad Split fixes
  src/pages/Launchpad/Splits/Form/index.tsx
  src/pages/Launchpad/Splits/index.tsx
  src/pages/Launchpad/Summary/toEVMAST.ts
  src/pages/Launchpad/common/Toggle.tsx
Labels: bug

#2127 Hardcoded chainid fix for AWS queries
  src/pages/Admin/Charity/DonationsTable/DonationsTable.tsx
  src/pages/Donations/useDonations.ts
Labels: bug

#2134 Fix Contibutions UI wording
  src/components/Split/Split.tsx
  src/components/donation/Steps/Donater/Form/AdvancedOptions.tsx
  src/components/donation/Steps/Donater/Form/index.tsx
  src/components/donation/Steps/Donater/index.tsx
  src/components/donation/Steps/index.tsx
  src/pages/Admin/Charity/ContributorVerification/ContributorVerification.tsx
  src/pages/Admin/Charity/DonationsTable/DonationsTable.tsx
  src/pages/DonateFiatThanks/index.tsx
  src/types/contracts/multisig.ts
Labels: bug, design

#2144 Minor admin UI fixes
  src/pages/Admin/Charity/ContributorVerification/ContributorVerification.tsx
Labels: bug, design

#2146 RC-v1.8: remove unused code
  .github/workflows/javascript.yml
  README.md
  src/App/constants.ts
  src/components/ExtLink.tsx
  src/components/KYC/types.ts
  src/components/WalletSuite/WalletPrompt.tsx
  src/components/WalletSuite/Warning.tsx
  src/components/admin/Status.tsx
  src/constants/env.ts
  src/constants/evm.ts
  src/constants/routes.ts
  src/constants/tokens.ts
  src/constants/urls.ts
  src/constants/wallet-connect.ts
  src/errors/errors.ts
  src/helpers/getAddressUrl.ts
  src/helpers/index.ts
  src/helpers/keplr.ts
  src/helpers/registration/registrationReference.ts
  src/helpers/theme.ts
  src/hooks/useHorizontalScroll.ts
  src/hooks/useTypeWriter.ts
  src/pages/Admin/Charity/EditProfile/optimizeImage.ts
  src/pages/Launchpad/ConnectWallet/WalletSubmission.tsx
  src/pages/Launchpad/Splits/Form/useSubmit.ts
  src/pages/Leaderboard/Table/Row/projectFunds.ts
  src/pages/Registration/Steps/Documentation/Form/CashEligibleCheckbox.tsx
  src/pages/Registration/Steps/WalletRegistration/ChooseWallet/KeplrConnector.tsx
  src/pages/Registration/Steps/WalletRegistration/WalletSubmission.tsx
  src/pages/Registration/types.ts
  src/schemas/number.ts
  src/schemas/string.ts
  src/schemas/tests.ts
  src/services/apes/donations.ts
  src/services/aws/auth.ts
  src/services/aws/leaderboard.ts
  src/services/aws/tags.ts
  src/services/types.ts
  src/slices/authSlice.ts
  src/slices/userSlice.ts
  src/types/aws/apes/donation.ts
  src/types/aws/apes/index.ts
  src/types/contracts/account.ts
  src/types/contracts/common.ts
  src/types/contracts/multisig.ts
  src/types/countries.ts
  src/types/evm.ts
  src/types/third-party/redux.ts
  src/types/tx.ts
  src/types/utils.ts
Labels: refactor

#2145 Create index fund: single type for form and tx-submission
  src/contracts/createTx/types.ts
  src/pages/Admin/Core/Templates/index-fund/CreateFund/Form.tsx
  src/pages/Admin/Core/Templates/index-fund/CreateFund/index.tsx
  src/pages/Admin/Core/Templates/index-fund/CreateFund/schema.ts
  src/pages/Admin/Core/Templates/index-fund/CreateFund/types.ts
  src/pages/Admin/Core/Templates/index-fund/CreateFund/useCreateFund.ts
  src/types/contracts/indexfund.ts
Labels: refactor

#2147 RC-v1.8: donation fixes
  src/pages/Donate/Content.tsx
  src/slices/donation/donation.ts
  src/slices/donation/sendDonation/index.ts
  src/types/aws/apes/donation.ts
Labels: bug

#2142 make launchpad steps clicakble
  src/pages/Launchpad/ConnectWallet/ChooseWallet/index.tsx
  src/pages/Launchpad/ConnectWallet/WalletSubmission.tsx
  src/pages/Launchpad/Layout.tsx
  src/pages/Launchpad/Progress.tsx
  src/pages/Launchpad/Summary/index.tsx
  src/pages/Launchpad/constants.ts
  src/pages/Launchpad/index.tsx
Labels: enhancement

#2149 Migrate future txs
  src/contracts/Account.ts
  src/contracts/CW3.ts
  src/contracts/Contract.ts
  src/contracts/createCosmosMsg/createCosmosMsg.ts
  src/contracts/createCosmosMsg/types.ts
  src/contracts/createTx/txs.ts
  src/contracts/createTx/types.ts
  src/pages/Admin/Charity/Invest/Investor/useSubmit.ts
  src/pages/Admin/Charity/Templates/account/EndowmentStatus/Beneficiary.tsx
  src/pages/Admin/Charity/Templates/account/EndowmentStatus/Form.tsx
  src/pages/Admin/Charity/Templates/account/EndowmentStatus/StatusOptions.tsx
  src/pages/Admin/Charity/Templates/account/EndowmentStatus/index.tsx
  src/pages/Admin/Charity/Templates/account/EndowmentStatus/schema.ts
  src/pages/Admin/Charity/Templates/account/EndowmentStatus/types.ts
  src/pages/Admin/Charity/Templates/account/EndowmentStatus/useUpdateStatus.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/types.ts
  src/pages/Admin/Charity/common/Investment/Investor/Form.tsx
  src/pages/Admin/Charity/common/Investment/Investor/index.tsx
  src/pages/Admin/Charity/common/Investment/Investor/schema.ts
  src/pages/Admin/Charity/common/Investment/Investor/types.ts
  src/pages/Admin/Charity/common/Investment/Investor/useSubmit.ts
  src/pages/Admin/Charity/common/Investment/Redeemer/useSubmit.ts
  src/pages/Admin/Charity/common/Investment/index.tsx
  src/pages/Admin/Charity/index.tsx
  src/pages/Admin/Proposal/Content/Preview/EndowmentStatusUpdate.tsx
  src/pages/Admin/templates/cw3/Config/useCreateProposal.ts
  src/pages/Admin/types.ts
  src/pages/Marketplace/Sidebar/Types.tsx
  src/services/juno/queryContract/decoded-types.ts
  src/slices/components/marketFilter/marketFilter.ts
  src/slices/components/marketFilter/types.ts
  src/types/aws/ap/index.ts
  src/types/contracts/account.ts
  src/types/contracts/common.ts
  src/types/contracts/evm/account.ts
  src/types/lists.ts
Labels: refactor

#2170 Bug fixes
  src/components/donation/Steps/Result/Err.tsx
  src/pages/Admin/Charity/index.tsx
  src/pages/Launchpad/Progress.tsx
  src/pages/Marketplace/Cards/useCards.ts
Labels: bug

#2171 Fix marketplace filter
  src/pages/Marketplace/Cards/useCards.ts
Labels: bug

#2169 Migrate giftcard
  src/assets/icons/currencies/gift.svg
  src/components/TokenField/Balance.tsx
  src/components/TokenField/TokenField.tsx
  src/components/TokenField/TokenSelector.tsx
  src/components/WalletSuite/ConnectedWallet/Details/Balances/CoinBalances.tsx
  src/components/donation/Steps/Submit/estimateDonation.ts
  src/components/donation/Steps/Submit/getBreakdown.test.ts
  src/components/donation/Steps/Submit/getBreakdown.ts
  src/components/donation/Steps/Submit/index.tsx
  src/constants/contracts.ts
  src/contexts/WalletContext/WalletContext.tsx
  src/contexts/WalletContext/constants.ts
  src/contexts/WalletContext/hooks/useVerifyChain.ts
  src/contracts/Contract.ts
  src/contracts/GiftCard.ts
  src/contracts/createTx/createTx.ts
  src/contracts/createTx/txs.ts
  src/contracts/createTx/types.ts
  src/contracts/evm/ERC20/abi.json
  src/contracts/evm/gift-card/balance.json
  src/contracts/evm/gift-card/index.ts
  src/contracts/evm/gift-card/txs.json
  src/errors/errors.ts
  src/pages/Admin/Charity/Holdings.tsx
  src/pages/Admin/Charity/Templates/account/EndowmentStatus/useUpdateStatus.ts
  src/pages/Admin/Proposal/Content/Preview/Withdraw.tsx
  src/pages/Admin/templates/cw3/FundSender/Form/index.tsx
  src/pages/Admin/templates/cw3/FundSender/index.tsx
  src/pages/Gift/Purchase/Purchaser/Form/Recipient.tsx
  src/pages/Gift/Purchase/Purchaser/Form/index.tsx
  src/pages/Gift/Purchase/Purchaser/schema.ts
  src/pages/Gift/Purchase/Submit/CompleteBtn.tsx
  src/pages/Gift/Purchase/Submit/estimateTx.ts
  src/pages/Gift/Purchase/Submit/index.tsx
  src/pages/Gift/Purchase/Submit/types.ts
  src/pages/Gift/Purchase/index.tsx
  src/schemas/shape.ts
  src/services/apes/apes.ts
  src/services/apes/helpers/fetchBalances.ts
  src/services/juno/index.ts
  src/services/juno/queryContract/decoded-types.ts
  src/services/juno/queryContract/index.ts
  src/services/juno/queryContract/placeholders.ts
  src/services/juno/queryContract/queryObjects.ts
  src/services/juno/queryContract/types.ts
  src/slices/gift/purchase.ts
  src/types/aws/apes/index.ts
  src/types/contracts/account.ts
  src/types/contracts/common.ts
  src/types/contracts/gift-card.ts
  src/types/contracts/index.ts
  src/types/evm.ts
  src/types/slices.ts
  src/types/tx.ts
  src/types/utils.ts
Labels: refactor

#2173 Refetch profile data on update
  src/components/WalletSuite/ConnectedWallet/Details/index.tsx
  src/services/aws/aws.ts
Labels: bug

#2182 Polygon chainId check
  src/pages/Admin/Charity/Invest/Investor/useSubmit.ts
  src/pages/Admin/Charity/Permissions/useSubmit.ts
  src/pages/Admin/Charity/Templates/account/EndowmentStatus/useUpdateStatus.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/useWithdraw.ts
  src/pages/Admin/Charity/common/Investment/Redeemer/useSubmit.ts
  src/pages/Admin/Core/Templates/index-fund/Alliance/Editor/useUpdateMembers.ts
  src/pages/Admin/Core/Templates/index-fund/Config/useConfigureFund.ts
  src/pages/Admin/Core/Templates/index-fund/CreateFund/useCreateFund.ts
  src/pages/Admin/Core/Templates/index-fund/IndexFundOwner/useUpdateOwner.ts
  src/pages/Admin/Core/Templates/index-fund/Members/useUpdateFund.ts
  src/pages/Admin/Core/Templates/index-fund/RemoveFund/useDestroyFund.ts
  src/pages/Admin/Core/Templates/registrar/ConfigExtension/useConfigureRegistrar.ts
  src/pages/Admin/Core/Templates/registrar/Owner/useUpdateOwner.ts
  src/pages/Admin/Guard.tsx
  src/pages/Admin/Proposal/PollAction.tsx
  src/pages/Admin/Review/Application/Summary/Proposer.tsx
  src/pages/Admin/templates/cw3/Config/useCreateProposal.ts
  src/pages/Admin/templates/cw3/FundSender/Form/useTransferFunds.ts
  src/pages/Admin/templates/cw4/Members/Adder/useUpdateMembers.ts
Labels: bug

#2185 Twitter tracking script
  public/index.html
Labels: enhancement

#2184 App Type drives SideMenu & Dashboard title wording
  src/pages/Admin/Charity/Dashboard/index.tsx
  src/pages/Admin/constants.ts
Labels: bug

#2187 add tracking script to head & reg submission ping;
  public/index.html
  src/pages/Registration/Steps/Dashboard/index.tsx
Labels: enhancement

#2188 Linkedin tracker - v1.8
  public/index.html
  src/pages/Registration/Steps/Dashboard/index.tsx
Labels: enhancement

#2192 Documentation upload error
  src/pages/Registration/Steps/Dashboard/index.tsx
  src/services/aws/registration/registration.ts
Labels: bug

#2193 Fix splits
  src/pages/Launchpad/Splits/Form/index.tsx
  src/pages/Launchpad/Splits/types.ts
  src/pages/Launchpad/Summary/Splits.tsx
  src/pages/Launchpad/Summary/toEVMAST.ts
  src/pages/Registration/Steps/Dashboard/index.tsx
Labels: bug

#2204 Master: deps update
  package.json
  src/contexts/WalletContext/useKeplr/chains.ts
  yarn.lock
Labels: dependencies
