Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2023-12, with the labels that each got.

#2546 AP-920: Add back widget in admin
  src/assets/images/DAFDirect.png
  src/pages/Admin/Charity/Widget/Configurer/EndowmentSelector/EndowmentSelector.tsx
  src/pages/Admin/Charity/Widget/Configurer/EndowmentSelector/Options.tsx
  src/pages/Admin/Charity/Widget/Preview/DonateMethods/AdvancedOptions.tsx
  src/pages/Admin/Charity/Widget/Preview/DonateMethods/DAFSample.tsx
  src/pages/Admin/Charity/Widget/Preview/DonateMethods/DonateMethods.tsx
  src/pages/Admin/Charity/Widget/Preview/DonateMethods/DonaterSample.tsx
  src/pages/Admin/Charity/Widget/Preview/DonateMethods/StocksSample.tsx
  src/pages/Admin/Charity/Widget/Preview/DonateMethods/StripeSample.tsx
  src/pages/Admin/Charity/Widget/Preview/DonateMethods/index.ts
  src/pages/Admin/Charity/Widget/Preview/Preview.tsx
  src/pages/Admin/Charity/index.tsx
Labels: design, refactor

#2550 RC-v1.9.1: updates from `rc-to-master-v2`
  src/App/__tests__/App.test.tsx
  src/App/constants.ts
  src/components/BankDetails/BankDetails.tsx
  src/components/BankDetails/RecipientDetails/AccountRequirementsSelector.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetails.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/Form.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/constants.ts
  src/components/BankDetails/RecipientDetails/useRecipientDetails.ts
  src/components/BankDetails/types.ts
  src/components/FileDropzone/FileDropzone.tsx
  src/components/Group.tsx
  src/components/ImgEditor/ImgEditor.tsx
  src/components/ImgEditor/types.ts
  src/pages/Admin/Charity/Banking/Banking.tsx
  src/pages/Admin/Charity/Banking/FormButtons.tsx
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Admin/Charity/ProgramEditor/schema.ts
  src/pages/Profile/Body/DonateButton.tsx
  src/pages/Registration/Steps/Banking/Banking.tsx
  src/pages/Registration/Steps/Banking/FormButtons.tsx
  src/pages/Registration/Steps/Documentation/FSA/Form/index.tsx
  src/pages/Registration/Steps/Documentation/FSA/schema.ts
  src/pages/Registration/Steps/ProgressIndicator.tsx
  src/pages/Registration/Steps/index.tsx
  src/schemas/file.ts
  src/store/amplify-config.ts
  src/store/store.ts
  src/types/lists.ts
Labels: duplicate

#2553 AP-939: Admin donations changes
  src/components/Icon/icons.ts
  src/pages/Admin/Charity/Donations/Donations.tsx
  src/pages/Admin/Charity/Donations/DonationsTable.tsx
  src/pages/Admin/Charity/Donations/Table.tsx
  src/types/aws/apes/donation.ts
Labels: enhancement, design, refactor

#2566 OAuth error: trial fix, use config straight from amplify prod
  amplify/.config/project-config.json
  amplify/team-provider-info.json
  src/aws-exports.js
  src/store/amplify-config.ts
  src/store/store.ts
Labels: bug

#2565 AP-953: stripe doesn't work on widget
  src/components/donation/Steps/DonateMethods/Stripe.tsx
Labels: bug

#2570 AP-960: Bank Details: remove USA as country options when requirements type is SWIFT and target currency is USD
  src/components/BankDetails/BankDetails.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetails.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/Form.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RequirementField.tsx
  src/components/BankDetails/RecipientDetails/useRecipientDetails/getDefaultValues.ts
  src/components/BankDetails/RecipientDetails/useRecipientDetails/mergeRequirements.ts
  src/components/BankDetails/RecipientDetails/useRecipientDetails/useRecipientDetails.ts
  src/components/BankDetails/RecipientDetails/useRecipientDetails/useStateReducer.ts
Labels: bug

#2569 AP-952: wording changes
  src/App/constants.ts
  src/helpers/getPossessiveForm.ts
  src/helpers/index.ts
  src/pages/Admin/Charity/Dashboard/Dashboard.tsx
  src/pages/Admin/Charity/Widget/Preview/DonateMethods/StocksSample.tsx
  src/pages/Admin/Charity/Widget/Preview/Preview.tsx
  src/pages/Application/Loaded.tsx
  src/pages/Applications/Table.tsx
  src/pages/DonateWidget/Content.tsx
  src/pages/Leaderboard/Table/Row/Amount/Summary.tsx
  src/pages/Registration/Steps/ProgressIndicator.tsx
Labels: bug, refactor

#2573 RC-v1.9.1: use config from `amplify-pull` directly
  amplify/.config/project-config.json
  src/store/amplify-config.ts
  src/store/store.ts
Labels: enhancement

#2579 Prod: pull config from new backend-environment: `master`
  src/aws-exports.js
  src/pages/Gift/Purchase/Submit/index.tsx
Labels: bug

#2568 AP-922: Invalid but focused input fields, (Multi)Selectors, Comboboxes etc. should have a box shadow to indicate focus
  src/components/FileDropzone/FileDropzone.tsx
  src/components/ImgEditor/ImgEditor.tsx
  src/components/RichText/RichText.tsx
  src/components/RichText/RichTextEditor.tsx
  src/components/RichText/types.ts
  src/components/Selector/FocusableInput.tsx
  src/components/Selector/MultiSelector.tsx
  src/components/Selector/Selector.tsx
  src/components/form/CheckField.tsx
  src/index.css
  tailwind.config.js
Labels: design

#2567 AP-942: After clicking "Check Requirements", non-selected requirement type forms should not be in error state
  src/components/BankDetails/RecipientDetails/RecipientDetails.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/Form.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
  src/components/BankDetails/RecipientDetails/useRecipientDetails/useRecipientDetails.ts
  src/components/BankDetails/RecipientDetails/useRecipientDetails/useStateReducer.ts
Labels: enhancement, refactor

#2577 Remove 'tickets' section from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: refactor

#2582 AP-962: User should be able to click anywhere within CountrySelector to focus the field
  src/components/CountrySelector/CountrySelector.tsx
Labels: bug, enhancement

#2575 AP-885: Prefill the "expected monthly donations" amount field so that the form is loaded on page load
  src/components/BankDetails/BankDetails.tsx
  src/components/BankDetails/ExpectedFunds.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetails.tsx
  src/hooks/useDebounce.ts
Labels: enhancement, refactor

#2585 BG-983 Reg rejection reason
  src/pages/Application/Loaded.tsx
  src/types/aws/ap/registration.ts
Labels: bug

#2593 BG-994: Remove other organization
  src/pages/Admin/Sidebar/Header/Header.tsx
Labels: bug, design

#2592 BG-998 BG-989 UI text tweaks
  src/components/BankDetails/UpdateDetailsButton.tsx
  src/components/Split/Portion.tsx
  src/pages/Registration/Steps/Banking/FormButtons.tsx
Labels: bug

#2587 BG-954: Registration Flow changes
  src/constants/routes.ts
  src/contexts/Auth.tsx
  src/pages/Registration/Resume/useSubmit.ts
  src/pages/Registration/SigningResult/ErrorPage.tsx
  src/pages/Registration/SigningResult/Success.tsx
  src/pages/Registration/Signup/Form.tsx
  src/pages/Registration/Signup/useSubmit.ts
  src/pages/Registration/Steps/Dashboard/index.tsx
  src/pages/Registration/Welcome.tsx
  src/pages/Registration/index.tsx
  src/pages/Registration/routes.ts
  src/pages/Signin/Signin.tsx
  src/types/routeStates.ts
Labels: enhancement

#2594 Fix: wise recipient id should be number
  src/types/aws/ap/index.ts
Labels: bug

#2595 FIX: reg summary/dashboard not disabled after submission
  src/pages/Registration/Steps/getRegistrationState.ts
  src/types/aws/ap/registration.ts
Labels: bug, priority

#2597 BG-1002: update network param `testnet | mainnet` to `staging | production`
  src/constants/env.ts
  src/errors/errors.ts
  src/services/apes/apes.ts
  src/services/aws/aws.ts
  src/services/aws/leaderboard.ts
  src/services/constants.ts
  src/slices/donation/sendDonation/index.ts
  src/types/aws/ap/index.ts
  src/types/lists.ts
Labels: bug

#2596 Fix: edge case - handle unfinished FSA
  src/pages/Registration/Steps/getRegistrationState.ts
  src/types/aws/ap/registration.ts
Labels: bug, enhancement

#2599 BG-1009 update footer social links
  src/App/constants.ts
Labels: bug

#2600 BG-1011: download url in success page
  src/pages/Registration/SigningResult/SigningResult.tsx
  src/pages/Registration/SigningResult/Success.tsx
  src/pages/Registration/SigningResult/types.ts
Labels: bug

#2581 BG-947,BG-999: Banking applications
  src/App/App.tsx
  src/App/Header/UserMenu/Menu.tsx
  src/constants/routes.ts
  src/pages/Admin/Charity/Banking/Banking.tsx
  src/pages/Admin/Charity/Banking/FormButtons.tsx
  src/pages/Admin/Charity/Banking/PayoutMethod/DeletePrompt.tsx
  src/pages/Admin/Charity/Banking/PayoutMethod/Loaded.tsx
  src/pages/Admin/Charity/Banking/PayoutMethod/PayoutMethod.tsx
  src/pages/Admin/Charity/Banking/PayoutMethod/Prompt.tsx
  src/pages/Admin/Charity/Banking/PayoutMethod/index.ts
  src/pages/Admin/Charity/Banking/PayoutMethods/PayoutMethods.tsx
  src/pages/Admin/Charity/Banking/PayoutMethods/Table.tsx
  src/pages/Admin/Charity/Banking/PayoutMethods/index.ts
  src/pages/Admin/Charity/Banking/VerificationStatus.tsx
  src/pages/Admin/Charity/Banking/index.ts
  src/pages/Admin/Charity/index.tsx
  src/pages/BankingApplication/BankingApplication.tsx
  src/pages/BankingApplication/Loaded.tsx
  src/pages/BankingApplication/Prompt.tsx
  src/pages/BankingApplication/index.ts
  src/pages/BankingApplications/BankingApplications.tsx
  src/pages/BankingApplications/Filter/Form.tsx
  src/pages/BankingApplications/Filter/StatusDropdown.tsx
  src/pages/BankingApplications/Filter/constants.ts
  src/pages/BankingApplications/Filter/index.tsx
  src/pages/BankingApplications/Filter/schema.ts
  src/pages/BankingApplications/Filter/types.ts
  src/pages/BankingApplications/LoadMoreBtn.tsx
  src/pages/BankingApplications/Prompt.tsx
  src/pages/BankingApplications/Table.tsx
  src/pages/BankingApplications/index.ts
  src/pages/BankingApplications/types.ts
  src/pages/BankingApplications/usePagination.ts
  src/services/aws/aws.ts
  src/services/aws/banking-applications.ts
  src/services/aws/wise.ts
  src/services/types.ts
  src/slices/auth.ts
  src/types/aws/ap/applications.ts
  src/types/aws/ap/bankDetails.ts
Labels: good first issue

#2604 FIX: remove placeholde reject reason
  src/pages/Admin/Charity/Banking/PayoutMethod/Loaded.tsx
Labels: bug, priority

#2605 FIX: payout method `set-default` enabled even `under-review`
  src/pages/Admin/Charity/Banking/PayoutMethod/Loaded.tsx
Labels: bug, priority

#2606 FIX: handle fiat chain id
  src/pages/Admin/Charity/Donations/Table.tsx
  src/pages/Donations/Table.tsx
  src/types/aws/apes/donation.ts
Labels: bug, priority

#2608 BG-1007: Fix errors caused by third party scripts
  public/index.html
  public/scripts/gtag-init.js
  public/scripts/hotjar-tracking.js
  public/scripts/intercom.js
  public/scripts/linkedin-tracking.js
  public/scripts/meta-pixel.js
  public/scripts/twitter-conversion-tracking.js
  src/App/Footer/Footer.tsx
  src/App/__tests__/App.test.tsx
Labels: bug, enhancement

#2609 Fix: receipt modal transparent
  src/components/KYC/index.tsx
Labels: bug, design

#2610 Fix state.from in UserMenu > Link.state
  src/App/Header/UserMenu/UserMenu.tsx
Labels: bug
