Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2023-09, with the labels that each got.

#2330 ap-748: Disable fiat when not AST
  src/components/KYC/Form/index.tsx
  src/components/donation/Steps/CurrentStep.tsx
  src/components/donation/Steps/Donater/Form/index.tsx
  src/components/donation/Steps/Donater/index.tsx
  src/components/donation/Steps/index.tsx
  src/constants/contracts.ts
  src/services/constants.ts
Labels: bug, refactor

#2336 Legacy: update deps
  package.json
  src/pages/Registration/Steps/Documentation/Form/useSubmit.ts
  src/pages/Registration/Steps/Documentation/types.ts
  yarn.lock
Labels: dependencies

#2337 Legacy: continue button disabled
  src/components/donation/Steps/Donater/Form/index.tsx
Labels: bug

#2338 RC-v1.8: cherry picks from legacy
  package.json
  src/components/donation/Steps/Donater/Form/index.tsx
  src/pages/Admin/AdminWallet/Settings/DurationForm.tsx
  src/pages/Launchpad/Management/DurationForm.tsx
  tailwind.config.js
  yarn.lock
Labels: bug, duplicate, dependencies

#2331 AP-756: Donate fees
  src/components/TokenField/TokenField.tsx
  src/components/donation/Steps/Donater/index.tsx
  src/components/donation/Steps/Submit/estimateDonation.ts
  src/components/donation/Steps/Submit/index.tsx
  src/contexts/WalletContext/constants.ts
  src/helpers/coin-gecko.ts
  src/helpers/tx/estimateTx/estimateCosmosFee.ts
  src/helpers/tx/estimateTx/estimateEVMfee.ts
  src/helpers/tx/estimateTx/estimateTerraFee.ts
  src/pages/Admin/Charity/Deposits/index.tsx
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Admin/Charity/EditProfile/update.ts
  src/pages/Admin/Charity/Invest/Investor/index.tsx
  src/pages/Admin/Charity/common/Investment/Redeemer/index.tsx
  src/pages/Admin/Charity/index.tsx
  src/pages/Donate/Content.tsx
  src/pages/Donate/index.tsx
  src/pages/DonateWidget/DonateWidget.tsx
  src/pages/DonateWidget/InnerComponent.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/DetailsColumn.tsx
  src/services/aws/aws.ts
  src/services/types.ts
  src/slices/donation/types.ts
  src/types/aws/ap/index.ts
  src/types/aws/apes/index.ts
  src/types/tx.ts
Labels: good first issue, refactor

#2342 RC-v1.8: fixes
  src/pages/Registration/Signup/useSubmit.ts
  src/services/constants.ts
Labels: bug, priority

#2344 ap-776: Selector blank initial vlaue
  src/components/Selector/Selector.tsx
  src/pages/Registration/Steps/ContactDetails/constants.ts
  src/pages/Registration/Steps/ContactDetails/index.tsx
  src/pages/Registration/Steps/ContactDetails/schema.ts
  src/types/aws/ap/registration.ts
Labels: refactor

#2348 Mainnet staging: fixes
  src/components/WalletSuite/ConnectedWallet/Details/AdminLinks.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Beneficiary.tsx
  src/pages/Admin/Charity/index.tsx
  src/pages/Admin/Context.tsx
Labels: bug

#2349 RC-v1.8: fixes
  src/components/WalletSuite/ConnectedWallet/Details/AdminLinks.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Beneficiary.tsx
  src/pages/Admin/Charity/index.tsx
  src/pages/Admin/Context.tsx
Labels: bug

#2352 Misc prod fixes
  .env.example
  amplify.yml
  src/constants/urls.ts
  src/pages/Registration/Steps/Documentation/Form/index.tsx
  src/services/constants.ts
  src/services/juno/custom/custom.ts
  src/services/subgraph/subgraph.ts
Labels: bug, enhancement

#2353 RC-v1.8: fixes
  package.json
  public/index.html
  src/contexts/WalletContext/wallet-connect/useKeplrWC.ts
  src/helpers/tx/estimateTx/estimateCosmosFee.ts
  src/types/third-party/wc-qrcode-modal.d.ts
  yarn.lock
Labels: bug, duplicate

#2355 RC-v1.8: fixes
  src/constants/contracts.ts
  src/constants/env.ts
  src/constants/urls.ts
  src/pages/Registration/Steps/Documentation/Form/index.tsx
  src/pages/Registration/Steps/Documentation/Form/useSubmit.ts
  src/pages/Registration/Steps/Documentation/index.tsx
  src/pages/Registration/Steps/getRegistrationState.ts
  src/pages/Registration/types.ts
Labels: bug

#2357 AP-785: execption rendering wallet option
  src/contexts/WalletContext/WalletContext.tsx
  src/contexts/WalletContext/types.ts
  src/contexts/WalletContext/useInjectedProvider.ts
  src/contexts/WalletContext/useKeplr/useKeplr.ts
  src/contexts/WalletContext/useTerra.ts
  src/contexts/WalletContext/useWeb3Auth/index.ts
  src/contexts/WalletContext/wallet-connect/useEVMWC.ts
  src/contexts/WalletContext/wallet-connect/useKeplrWC.ts
  src/pages/Launchpad/ConnectWallet/ChooseWallet/WalletConnector.tsx
  src/pages/Launchpad/ConnectWallet/ChooseWallet/index.tsx
  src/pages/Registration/Steps/WalletRegistration/ChooseWallet/WalletConnector.tsx
  src/pages/Registration/Steps/WalletRegistration/ChooseWallet/index.tsx
Labels: bug

#2356 RC-v1.8: fixes
  src/contexts/WalletContext/constants.ts
  src/pages/Admin/Core/Templates/Nav.tsx
  src/pages/Admin/Proposals/index.tsx
Labels: enhancement

#2364 AP-787:changes in reg documentation
  src/pages/Admin/Review/Applications/__tests__/Applications.test.tsx
  src/pages/Registration/Steps/Documentation/Form/index.tsx
  src/pages/Registration/Steps/Documentation/Form/useSubmit.ts
  src/pages/Registration/Steps/Documentation/index.tsx
  src/pages/Registration/Steps/Documentation/schema.ts
  src/pages/Registration/Steps/getRegistrationState.ts
  src/pages/Registration/types.ts
  src/types/aws/ap/registration.ts
Labels: refactor

#2365 Web3Auth: AWS env vars setup
  .env.example
  amplify.yml
  src/constants/env.ts
  src/contexts/WalletContext/useWeb3Auth/web3AuthConfigs.ts
  src/contexts/WalletContext/useWeb3Auth/web3AuthSetup.ts
Labels: enhancement

#2366 RC-v1.8: Legal entity back to input text
  src/pages/Admin/Review/Applications/__tests__/Applications.test.tsx
  src/pages/Registration/SignNotice.tsx
  src/pages/Registration/Steps/Documentation/Form/index.tsx
  src/pages/Registration/Steps/Documentation/Form/useSubmit.ts
  src/pages/Registration/Steps/Documentation/index.tsx
  src/pages/Registration/Steps/Documentation/schema.ts
  src/pages/Registration/Steps/getRegistrationState.ts
  src/pages/Registration/types.ts
  src/services/types.ts
  src/types/aws/ap/registration.ts
Labels: enhancement, refactor

#2369 Contributions table
  src/pages/Admin/Charity/DonationsTable/Table.tsx
Labels: bug, enhancement

#2370 admin word/title tweaks
  src/pages/Admin/Charity/Account/index.tsx
  src/pages/Admin/Charity/Contributions.tsx
  src/pages/Admin/Charity/WidgetConfigurer/WidgetExample/WidgetExample.tsx
Labels: bug

#2383 HOT FIX: update edit profile endpoint
  src/services/apes/helpers/fetchBalances.ts
  src/services/aws/aws.ts
Labels: bug, priority

#2387 Prod: enable zoom on cropper
  src/components/ImgEditor/ImgCropper.tsx
Labels: enhancement

#2386 FIX: applications table
  src/pages/Admin/Review/Applications/Table/StatusSelector.tsx
  src/pages/Admin/Review/Applications/Table/index.tsx
  src/pages/Admin/Review/Applications/index.ts
  src/pages/Admin/Review/Applications/index.tsx
  src/services/aws/registration/registration.ts
  src/slices/admin/types.ts
  src/types/aws/ap/registration.ts
Labels: bug, design

#2389 AP-798 v1.9: Marketplace cards use logo instead of image
  src/constants/common.ts
  src/pages/Marketplace/Cards/Card.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/Tags.tsx
  src/services/aws/aws.ts
  src/types/aws/ap/index.ts
Labels: design

#2388 temp legacy notice banner
  src/App/Header/index.tsx
  src/App/Layout.tsx
Labels: priority

#2391 Fix: marketplace link active
  src/App/App.tsx
  src/App/Header/DesktopNav.tsx
  src/App/Header/MobileNav/Menu.tsx
  src/App/constants.ts
  src/App/types.ts
  src/index.tsx
Labels: bug

#2390 RC-v1.9: fixes from master
  src/App/Header/index.tsx
  src/App/Layout.tsx
  src/components/ImgEditor/ImgCropper.tsx
  src/pages/Admin/Review/Applications/Table/StatusSelector.tsx
  src/pages/Admin/Review/Applications/Table/index.tsx
  src/pages/Admin/Review/Applications/index.ts
  src/pages/Admin/Review/Applications/index.tsx
  src/services/apes/helpers/fetchBalances.ts
  src/services/aws/aws.ts
  src/services/aws/registration/registration.ts
  src/slices/admin/types.ts
  src/types/aws/ap/registration.ts
Labels: duplicate

#2393 RC-v1.9: update subgraph endpoint
  src/constants/urls.ts
Labels: bug

#2399 Prod: deps update
  package.json
  yarn.lock
Labels: dependencies

#2401 RC-v1.9: update subgraph version
  src/constants/urls.ts
Labels: enhancement

#2403 HOT-FIX: program page not showing
  src/App/App.tsx
Labels: bug, priority

#2382 AP-754: Withdraw beneficiary dropdown from subgraph
  src/pages/Admin/Charity/Templates/account/CloseEndowment/Beneficiary.tsx
  src/pages/Admin/Charity/Widget/Snippet/createWidgerUrl.ts.example
  src/pages/Admin/Charity/Widget/useWidgetConfigurer.example
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Amounts.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Beneficiary/Beneficiary.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Beneficiary/EndowmentOptions.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Beneficiary/EndowmentSelector.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Beneficiary/index.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/Form.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/helpers.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/index.tsx
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/schema.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/types.ts
  src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/useWithdraw.ts
  src/services/aws/aws.ts
  src/services/subgraph/index.ts
  src/services/subgraph/subgraph.ts
  src/services/types.ts
  src/types/subgraph.ts
Labels: enhancement
