Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2024-07, with the labels that each got.

#3107 BG-1399: Stripe status handling for manual bank verification
  src/pages/DonateThanks.tsx
  src/pages/StripePaymentStatus.tsx
  src/pages/UserDashboard/Donations/MobileTable.tsx
  src/pages/UserDashboard/Donations/Table.tsx
  src/services/apes/apes.ts
  src/types/aws/ap/donations.ts
Labels: bug

#3090 Add wordpress assets to post page
  public/wordpress/animate.min.css
  public/wordpress/bootstrap.min.css
  public/wordpress/bootstrap.rtl.min.css
  public/wordpress/custom-animation.css
  public/wordpress/fontawesome.min.css
  public/wordpress/gainioz-core.css
  public/wordpress/gainioz-custom.css
  public/wordpress/gainioz-unit.css
  public/wordpress/magnific-popup.css
  public/wordpress/meanmenu.css
  public/wordpress/nice-select.css
  public/wordpress/swiper-bundle.css
  src/App/Footer/Footer.tsx
  src/App/Footer/FooterV2.tsx
  src/App/Footer/index.tsx
  src/App/Header/index.tsx
  src/App/Layout.tsx
  src/index.css
  src/pages/Blog/Post.tsx
  src/styles/components.css
Labels: design

#3111 Stripe form integration test
  src/components/CurrencySelector/CurrencySelector.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Form.test.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Frequency.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Incrementers.tsx
  src/components/donation/Steps/DonateMethods/Stripe/types.ts
  src/components/donation/Steps/DonateMethods/Stripe/useRhf.ts
  src/components/donation/Steps/common/constants.ts
  src/components/form/Field.tsx
Labels: enhancement, refactor

#3113 Node proxies
  src/components/donation/Steps/Submit/Crypto/TxSubmit/tokenBalance.ts
  src/constants/chainOptions.ts
  src/constants/chains.ts
  src/constants/urls.ts
  src/contexts/WalletContext/useInjectedProvider.ts
  src/helpers/tx/estimateTx/estimateCosmosFee.ts
  src/helpers/tx/estimateTx/estimateEVMfee.ts
  src/helpers/tx/estimateTx/estimateTerraFee.ts
  src/helpers/tx/sendTx/sendCosmosTx.ts
  src/types/chain.ts
Labels: enhancement, refactor

#3121 Add 'ukGiftAid' field in fiat donation payload
  src/components/donation/Steps/common/constants.ts
  src/types/aws/apes/donation.ts
Labels: enhancement

#3112 Cover processing fee UI
  package.json
  src/components/donation/Steps/DonateMethods/helpers.ts
  src/components/donation/Steps/Submit/Crypto/Crypto.tsx
  src/components/donation/Steps/Submit/Crypto/DirectMode.tsx
  src/components/donation/Steps/Submit/Crypto/TxSubmit/TxSubmit.tsx
  src/components/donation/Steps/Submit/Crypto/TxSubmit/estimateDonation.ts
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Checkout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/components/donation/Steps/Summary/Summary.tsx
  src/components/donation/Steps/Summary/SummaryForm.tsx
  src/components/donation/Steps/Summary/helpers.ts
  src/components/donation/Steps/common/Summary.tsx
  src/components/donation/Steps/index.tsx
  src/components/donation/Steps/types.ts
  src/constants/chains.ts
  src/constants/common.ts
  src/constants/urls.ts
  src/types/aws/apes/donation.ts
  src/types/chain.ts
  yarn.lock
Labels: good first issue

#3122 BG-1437: Tribute notif UI
  src/components/donation/Steps/Submit/Crypto/DirectMode.tsx
  src/components/donation/Steps/Submit/Crypto/TxSubmit/TxSubmit.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/components/donation/Steps/Summary/Summary.tsx
  src/components/donation/Steps/Summary/SummaryForm.tsx
  src/components/donation/Steps/common/constants.ts
  src/components/donation/Steps/index.tsx
  src/components/donation/Steps/types.ts
  src/components/form/Field.tsx
  src/types/aws/apes/donation.ts
Labels: good first issue

#3124 FIX: header footer styles
  src/App/Footer/FooterV2.tsx
  src/App/Header/index.tsx
  src/App/Layout.tsx
Labels: bug

#3126 Stocks form integration test
  src/components/donation/Steps/DonateMethods/Crypto/Form.test.tsx
  src/components/donation/Steps/DonateMethods/Stocks/Form.test.tsx
  src/components/donation/Steps/DonateMethods/Stocks/Form.tsx
Labels: enhancement

#3123 Async chain
  src/components/donation/Steps/Submit/Crypto/Crypto.tsx
  src/components/donation/Steps/Submit/Crypto/TxSubmit/tokenBalance.ts
  src/constants/chainIds.ts
  src/constants/chainOptions.ts
  src/constants/chains.ts
  src/contexts/WalletContext/useInjectedProvider.ts
  src/helpers/tx/estimateTx/estimateCosmosFee.ts
  src/helpers/tx/estimateTx/estimateEVMfee.ts
  src/helpers/tx/estimateTx/estimateTerraFee.ts
  src/helpers/tx/get-chain.ts
  src/helpers/tx/sendTx/sendCosmosTx.ts
  src/pages/UserDashboard/Donations/Table.tsx
  src/services/terra.ts
  src/store/store.ts
  src/types/aws/apes/index.ts
  src/types/chain.ts
Labels: enhancement, refactor

#3125 New donations table fields
  src/pages/Admin/Charity/Donations/DonationsTable.tsx
  src/pages/Admin/Charity/Donations/Row.tsx
  src/pages/Admin/Charity/Donations/Table.tsx
  src/pages/UserDashboard/Donations/MobileTable.tsx
  src/pages/UserDashboard/Donations/Table.tsx
  src/types/aws/ap/donations.ts
Labels: enhancement

#3128 Donate steps - test skips and resets
  src/components/Copier/Copier.test.tsx
  src/components/donation/Steps/DonateMethods/Crypto/Form.test.tsx
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
  src/components/donation/Steps/Splits/Splits.tsx
  src/components/donation/Steps/Steps.test.tsx
  src/components/donation/Steps/Tip/Tip.tsx
  src/setupTests.ts
Labels: enhancement

#3140 compress images and use webp format
  src/pages/@sections/HeroBottom/HeroBottom.tsx
  src/pages/@sections/HeroBottom/map.png
  src/pages/@sections/HeroBottom/map.webp
  src/pages/Home/Hero/head-illust.webp
Labels: enhancement

#3142 UI updates
  src/components/DonationTerms.tsx
  src/pages/Donate/Content.tsx
  src/pages/DonateWidget/Content.tsx
  src/pages/Widget/Preview.tsx
Labels: refactor

#3145 BG-1452: CC always goes along with DAF
  src/components/DonateMethods.tsx
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
  src/pages/Widget/Widget.tsx
  src/types/components.ts
Labels: refactor

#3146 Summary form integration test
  src/components/Selector/Selector.tsx
  src/components/Selector/index.ts
  src/components/Selector/types.ts
  src/components/donation/Steps/Summary/SummaryForm.test.tsx
  src/components/donation/Steps/Summary/SummaryForm.tsx
  src/components/form/CheckField.tsx
  src/components/form/Field.tsx
  src/components/form/index.ts
  src/helpers/react.ts
Labels: enhancement

#3147 Card lock initially
  src/components/DonateMethods.tsx
Labels: bug

#3144 Update donations tables
  src/helpers/index.ts
  src/helpers/replaceWithEmptyString.ts
  src/pages/Admin/Charity/Donations/DonationsTable.tsx
  src/pages/Admin/Charity/Donations/Table.tsx
  src/pages/UserDashboard/Donations/MobileTable.tsx
  src/pages/UserDashboard/Donations/Table.tsx
  src/pages/UserDashboard/Donations/index.tsx
Labels: bug, enhancement

#3148 Summary step integration test
  src/components/donation/Steps/DonateMethods/Stripe/Form.test.tsx
  src/components/donation/Steps/Summary/Summary.test.tsx
  src/components/donation/Steps/common/Summary.tsx
  src/setupTests.ts
Labels: enhancement

#3149 Alerts opt out
  src/App/Header/UserMenu/Bookmarks.tsx
  src/App/Header/UserMenu/EndowmentLink.tsx
  src/App/Header/UserMenu/Menu.tsx
  src/App/Header/UserMenu/Organizations.tsx
  src/layout/DashboardLayout/Sidebar/SidebarOpener/useSidebarOpener.ts
  src/pages/UserDashboard/Settings/EndowAlertForm.tsx
  src/pages/UserDashboard/Settings/EndowRow.tsx
  src/pages/UserDashboard/Settings/Settings.tsx
  src/pages/UserDashboard/Settings/index.ts
  src/pages/UserDashboard/UserDashboard.tsx
  src/pages/UserDashboard/routes.ts
  src/services/aws/aws.ts
  src/services/aws/users.ts
  src/slices/auth.ts
  src/types/aws/ap/index.ts
Labels: good first issue

#3158 User avatar
  src/App/Header/UserMenu/UserMenu.tsx
  src/components/ImgEditor/ImgCropper.tsx
  src/components/ImgEditor/ImgEditor.tsx
  src/components/ImgEditor/index.ts
  src/components/ImgEditor/types.ts
  src/components/ImgEditor/useImgEditor.ts
  src/helpers/uploadFiles.ts
  src/pages/UserDashboard/EditProfile/Form.tsx
  src/pages/UserDashboard/EditProfile/types.ts
  src/pages/UserDashboard/EditProfile/useRhf.ts
  src/slices/auth.ts
  src/types/auth.ts
  src/types/aws/ap/index.ts
Labels: good first issue

#3159 Admin member names
  src/pages/Admin/Charity/Members/List.tsx
  src/services/aws/endow-admins.ts
  src/types/aws/ap/index.ts
Labels: enhancement

#3160 Terms move from page to checkout
  biome.json
  src/components/Copier/Copier.test.tsx
  src/components/donation/Steps/Submit/Crypto/Crypto.tsx
  src/components/donation/Steps/Submit/Crypto/WalletSelection.tsx
  src/components/donation/Steps/Submit/DAFCheckout/ManualDonation.tsx
  src/components/donation/Steps/Submit/DonationTerms.tsx
  src/components/donation/Steps/Submit/Stocks.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/components/donation/Steps/Summary/SummaryForm.test.tsx
  src/helpers/uploadFiles.test.ts
  src/pages/Donate/Content.tsx
  src/pages/DonateWidget/Content.tsx
  src/pages/Widget/Preview.tsx
Labels: enhancement, refactor

#3161 temp hide UK GiftAid checkbox
  src/components/donation/Steps/Summary/SummaryForm.test.tsx
  src/components/donation/Steps/Summary/SummaryForm.tsx
Labels: bug

#3163 Disable tracking in `/donate-widget`
  src/App/App.tsx
  src/components/Seo.tsx
  src/index.html
  src/pages/DonateThanks.tsx
  src/pages/DonateWidget/DonateWidget.tsx
  src/pages/StripePaymentStatus.tsx
Labels: bug, refactor

#3164 `Login` consistency
  package.json
  src/constants/routes.ts
  src/pages/SignUp/SignupForm/SignupForm.tsx
  src/pages/SignUp/SignupForm/UserTypeSelector.tsx
  yarn.lock
Labels: bug

#3165 Auth redirect
  src/App/App.tsx
  src/components/form/Input.tsx
  src/components/form/PasswordInput.tsx
  src/constants/auth.ts
  src/helpers/determineAuthRedirectPath.ts
  src/helpers/getAuthRedirect.ts
  src/helpers/index.ts
  src/index.tsx
  src/pages/OAuthRedirector.tsx
  src/pages/ResetPassword/InitForm.tsx
  src/pages/ResetPassword/SetPasswordForm.tsx
  src/pages/SignUp/ConfirmForm.tsx
  src/pages/SignUp/SignupForm/SignupForm.tsx
  src/pages/SignUp/SignupForm/UserTypeSelector.tsx
  src/pages/SignUp/Success.tsx
  src/pages/Signin.tsx
  src/store/store.ts
  src/types/auth.ts
Labels: bug, enhancement

#3176 DAF requirements
  src/assets/icons/dafpay.svg
  src/components/DonateMethods/DonateMethods.tsx
  src/components/DonateMethods/helpers.test.ts
  src/components/DonateMethods/helpers.ts
  src/components/DonateMethods/index.ts
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
  src/pages/Admin/Charity/Settings/Form.tsx
  src/pages/Donate/Content.tsx
  src/pages/Widget/Configurer/Configurer.tsx
  src/pages/Widget/Widget.tsx
Labels: enhancement

#3178 Protected redirects to signup
  src/contexts/Auth.tsx
Labels: design / ux

#3177 No edit name
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/services/aws/aws.ts
Labels: enhancement

#3179 Member editing: use `Prompt` instead of `window.alert`
  src/pages/Admin/Charity/Members/List.tsx
Labels: design / ux

#3180 Program info in summary
  src/components/donation/Steps/Submit/Crypto/Crypto.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/components/donation/Steps/Summary/Summary.tsx
  src/components/donation/Steps/common/Summary.tsx
Labels: design / ux

#3183 Bg1489 faqs
  src/App/Footer/FooterV2.tsx
  src/pages/Donate/FAQ.tsx
  src/pages/Registration/Steps/Documentation/FSA/Form/index.tsx
Labels: bug, enhancement

#3182 Fund opt in setting
  src/pages/Admin/Charity/Settings/Form.tsx
  src/pages/Admin/Charity/Settings/Settings.tsx
  src/pages/Admin/Charity/Settings/types.ts
  src/services/aws/aws.ts
  src/services/aws/mock.ts
  src/types/aws/ap/index.ts
Labels: good first issue

#3181 v2.4.2
  package.json
  src/App/App.tsx
  src/App/Footer/FooterV2.tsx
  src/components/Seo.tsx
  src/components/donation/Steps/Submit/Crypto/Crypto.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/components/donation/Steps/Summary/Summary.tsx
  src/components/donation/Steps/common/Summary.tsx
  src/components/form/Input.tsx
  src/components/form/PasswordInput.tsx
  src/constants/auth.ts
  src/constants/routes.ts
  src/contexts/Auth.tsx
  src/helpers/determineAuthRedirectPath.ts
  src/helpers/getAuthRedirect.ts
  src/helpers/index.ts
  src/index.html
  src/index.tsx
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/Members/List.tsx
  src/pages/Donate/FAQ.tsx
  src/pages/DonateThanks.tsx
  src/pages/DonateWidget/Content.tsx
  src/pages/OAuthRedirector.tsx
  src/pages/Registration/Steps/Documentation/FSA/Form/index.tsx
  src/pages/ResetPassword/InitForm.tsx
  src/pages/ResetPassword/SetPasswordForm.tsx
  src/pages/SignUp/ConfirmForm.tsx
  src/pages/SignUp/SignupForm/SignupForm.tsx
  src/pages/SignUp/SignupForm/UserTypeSelector.tsx
  src/pages/SignUp/Success.tsx
  src/pages/Signin.tsx
  src/pages/StripePaymentStatus.tsx
  src/services/aws/aws.ts
  src/store/store.ts
  src/types/auth.ts
  yarn.lock
Labels: duplicate

#3143 DAF Checkout with chariot
  .env.example
  amplify.yml
  package.json
  src/components/donation/Steps/Submit/Crypto/DirectMode.tsx
  src/components/donation/Steps/Submit/DAFCheckout/ChariotCheckout.tsx
  src/components/donation/Steps/Submit/DAFCheckout/DAFCheckout.tsx
  src/components/donation/Steps/Submit/DAFCheckout/ManualDonation.tsx
  src/components/donation/Steps/Submit/DAFCheckout/index.ts
  src/components/donation/Steps/Submit/DAFCheckout/toPlatformValues.test.ts
  src/components/donation/Steps/Submit/DAFCheckout/toPlatformValues.ts
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Checkout.tsx
  src/constants/env.ts
  src/pages/Donate/Content.tsx
  src/pages/Donate/FAQ.tsx
  src/pages/DonateThanks.tsx
  src/pages/StripePaymentStatus.tsx
  src/services/apes/apes.ts
  src/types/pages.ts
  yarn.lock
Labels: enhancement, good first issue

#3191 Update node LTS
  .github/workflows/javascript.yml
  package.json
Labels: dependencies

#3193 Don't load static tokens on unsupported (no infra) chain
  src/components/TokenField/TokenSelector/TokenOptions.tsx
Labels: bug
