Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2024-05, with the labels that each got.

#2940 BG-1253: Pending Payment donation pickup button
  src/App/App.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Frequency.tsx
  src/components/donation/Steps/Submit/Crypto/TxSubmit/TxSubmit.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Checkout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/components/donation/Steps/Summary/Summary.tsx
  src/components/donation/Steps/common/Summary.tsx
  src/pages/Donate/Content.tsx
  src/pages/Donate/index.tsx
  src/pages/DonationLoader.tsx
  src/pages/Donations/MobileTable.tsx
  src/pages/Donations/Table.tsx
  src/services/apes/apes.ts
  src/slices/donation/donation.ts
  src/slices/donation/types.ts
  src/types/aws/apes/donation.ts
Labels: enhancement

#2942 Wise validation display
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
  src/services/aws/wise.ts
Labels: bug

#2941 V3 endowment
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
  src/components/RichText/RichText.tsx
  src/components/RichText/RichTextEditor.tsx
  src/components/RichText/types.ts
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Admin/Charity/EditProfile/update.ts
  src/pages/Admin/Charity/ProgramEditor/Form.tsx
  src/pages/Admin/Charity/ProgramEditor/Milestone/Milestone.tsx
  src/pages/Admin/Charity/ProgramEditor/Milestone/index.ts
  src/pages/Admin/Charity/ProgramEditor/Milestone/schema.ts
  src/pages/Admin/Charity/ProgramEditor/Milestone/types.ts
  src/pages/Admin/Charity/ProgramEditor/Milestone/useMutate.ts
  src/pages/Admin/Charity/ProgramEditor/Milestones.tsx
  src/pages/Admin/Charity/ProgramEditor/Milestones/Milestones.tsx
  src/pages/Admin/Charity/ProgramEditor/Milestones/index.ts
  src/pages/Admin/Charity/ProgramEditor/ProgramEditor.tsx
  src/pages/Admin/Charity/ProgramEditor/ProgramInfo/ProgramInfo.tsx
  src/pages/Admin/Charity/ProgramEditor/ProgramInfo/index.ts
  src/pages/Admin/Charity/ProgramEditor/ProgramInfo/schema.ts
  src/pages/Admin/Charity/ProgramEditor/ProgramInfo/types.ts
  src/pages/Admin/Charity/ProgramEditor/ProgramInfo/useSubmit.ts
  src/pages/Admin/Charity/ProgramEditor/common.ts
  src/pages/Admin/Charity/ProgramEditor/schema.ts
  src/pages/Admin/Charity/ProgramEditor/types.ts
  src/pages/Admin/Charity/ProgramEditor/useSubmit.ts
  src/pages/Admin/Charity/Programs/List.tsx
  src/pages/Admin/Charity/Programs/Program.tsx
  src/pages/Admin/Charity/Programs/Programs.tsx
  src/pages/Admin/Charity/Seo.tsx
  src/pages/Admin/Charity/index.tsx
  src/pages/Donate/index.tsx
  src/pages/DonateWidget/Content.tsx
  src/pages/Home/HeroBottom/Card.tsx
  src/pages/Marketplace/Cards/Card.tsx
  src/pages/Profile/Body/GeneralInfo/GeneralInfo.tsx
  src/pages/Profile/Body/GeneralInfo/Programs.tsx
  src/pages/Profile/Body/Program/Milestones.tsx
  src/pages/Profile/Body/Program/Program.tsx
  src/pages/Profile/index.tsx
  src/pages/Widget/Widget.tsx
  src/services/apes/apes.ts
  src/services/aws/aws.ts
  src/services/aws/milestones.ts
  src/services/aws/programs.ts
  src/services/aws/registration/registration.ts
  src/services/aws/wise.ts
  src/services/types.ts
  src/types/aws/ap/index.ts
  src/types/utils.ts
Labels: good first issue, refactor

#2943 BG-1320 Homepage fixes
  src/App/Layout.tsx
  src/pages/Home/Animation/Animation.tsx
  src/pages/Home/Animation/MobileAnimation.tsx
  src/pages/Home/Animation/StepsCard.tsx
  src/pages/Home/Animation/TabletAnimation.tsx
  src/pages/Home/Animation/images/static-path.png
  src/pages/Home/Animation/mobile.module.css
  src/pages/Home/Animation/tablet.module.css
  src/pages/Home/Animation/types.ts
  src/pages/Home/Brands.tsx
  src/pages/Home/HeroBottom/Card.tsx
  src/pages/Home/Testimonials/TestimonialCard.tsx
  src/pages/Home/Video.tsx
Labels: bug, design

#2944 Rolled back stripe donation endpoint
  src/services/apes/apes.ts
Labels: bug

#2945 Bump prod(future) program delete endpoint
  src/services/aws/programs.ts
Labels: bug

#2947 BG-1323 Testimonials fixes
  src/pages/Home/Testimonials/useGetTestimonials.ts
Labels: bug

#2949 BG-1324 Carousel cards mixed up
  src/pages/Home/Benefits/Path.tsx
Labels: bug

#2946 BG-1307 GDPR Banner
  public/scripts/cookie-consent-notice.js
  src/index.html
Labels: enhancement

#2950 Update crypto intent endpoints to use API stage variables
  src/services/apes/apes.ts
Labels: bug

#2954 Added authorization header to registration update endpoint
  src/services/aws/registration/registration.ts
Labels: bug

#2955 Update endpoints
  src/pages/Admin/Charity/Members/AddForm.tsx
  src/pages/Admin/Charity/Members/List.tsx
  src/services/aws/aws.ts
  src/services/aws/endow-admins.ts
Labels: enhancement, refactor

#2966 BG-1327 Banner fallback
  src/assets/images/fallback-banner.png
  src/pages/Admin/Sidebar/Header/Header.tsx
  src/pages/Profile/index.tsx
Labels: enhancement

#2967 Get user attributes from DB instead of cognito
  src/slices/auth.ts
  src/types/auth.ts
Labels: refactor

#2968 User dashboard
  src/App/App.tsx
  src/App/Header/UserMenu/UserMenu.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/constants/routes.ts
  src/layout/DashboardLayout/Layout.tsx
  src/layout/DashboardLayout/Sidebar/Sidebar.tsx
  src/layout/DashboardLayout/Sidebar/SidebarOpener/SidebarOpener.tsx
  src/layout/DashboardLayout/Sidebar/SidebarOpener/ToggleableSidebar.tsx
  src/layout/DashboardLayout/Sidebar/SidebarOpener/index.ts
  src/layout/DashboardLayout/Sidebar/SidebarOpener/useSidebarOpener.ts
  src/layout/DashboardLayout/Sidebar/index.ts
  src/layout/DashboardLayout/Sidebar/types.ts
  src/layout/DashboardLayout/index.ts
  src/pages/Admin/Charity/index.tsx
  src/pages/Admin/Layout.tsx
  src/pages/Admin/SidebarHeader/Header.tsx
  src/pages/Admin/SidebarHeader/MyEndowments.tsx
  src/pages/Admin/SidebarHeader/index.ts
  src/pages/Admin/constants.ts
  src/pages/UserDashboard/EditProfile/EditProfile.tsx
  src/pages/UserDashboard/EditProfile/Form.tsx
  src/pages/UserDashboard/EditProfile/index.ts
  src/pages/UserDashboard/EditProfile/types.ts
  src/pages/UserDashboard/UserDashboard.tsx
  src/pages/UserDashboard/index.ts
  src/pages/UserDashboard/routes.ts
  src/services/apes/apes.ts
  src/services/aws/aws.ts
  src/services/aws/users.ts
  src/slices/auth.ts
  src/types/aws/ap/index.ts
Labels: good first issue, refactor

#2969 Home page blog section overflow
  src/pages/Home/Blogs/Blogs.tsx
Labels: bug

#2970 BG-1331: Move donate page inside user dashboard
  src/App/App.tsx
  src/App/Header/UserMenu/UserMenu.tsx
  src/pages/UserDashboard/Donations/Filter/CurrencyDropdown.tsx
  src/pages/UserDashboard/Donations/Filter/Form.tsx
  src/pages/UserDashboard/Donations/Filter/NetworkDropdown.tsx
  src/pages/UserDashboard/Donations/Filter/constants.ts
  src/pages/UserDashboard/Donations/Filter/index.tsx
  src/pages/UserDashboard/Donations/Filter/schema.ts
  src/pages/UserDashboard/Donations/Filter/types.ts
  src/pages/UserDashboard/Donations/LoadMoreBtn.tsx
  src/pages/UserDashboard/Donations/MobileTable.tsx
  src/pages/UserDashboard/Donations/NoDonations.tsx
  src/pages/UserDashboard/Donations/StatusTabs.tsx
  src/pages/UserDashboard/Donations/Table.tsx
  src/pages/UserDashboard/Donations/index.tsx
  src/pages/UserDashboard/Donations/types.ts
  src/pages/UserDashboard/Donations/useShowKYCForm.ts
  src/pages/UserDashboard/EditProfile/Form.tsx
  src/pages/UserDashboard/UserDashboard.tsx
  src/pages/UserDashboard/routes.ts
Labels: refactor

#2972 Implement share in stripe success page
  src/components/donation/Steps/Result/Success/index.tsx
  src/components/donation/Steps/Share.tsx
  src/components/donation/index.ts
  src/pages/DonateFiatThanks.tsx
  src/pages/StripePaymentStatus.tsx
  src/services/apes/apes.ts
Labels: enhancement, refactor

#2973 BG-1333 T&C for Widgets
  src/pages/DonateWidget/Content.tsx
  src/pages/Widget/Preview.tsx
Labels: bug

#2975 Endowment link: error marker
  src/App/Header/UserMenu/EndowmentLink.tsx
Labels: bug

#2990 BG-1347: SF flag changes
  src/pages/Admin/Charity/Settings/Form.tsx
Labels: refactor

#2976 BG-1341 Widget adaptations
  src/components/donation/Steps/Submit/DAFCheckout/ManualDonation.tsx
  src/components/donation/Steps/Submit/Stocks.tsx
  src/components/donation/Steps/common/Summary.tsx
  src/slices/donation/donation.ts
Labels: enhancement

#2989 BG-1346 Donation Builder: style fixes and design improvement
  src/pages/Widget/Preview.tsx
  src/pages/Widget/Snippet/Snippet.tsx
  src/pages/Widget/Widget.tsx
Labels: design

#2991 Nonprofits page improvs
  src/assets/images/waving-character.png
  src/assets/laira/laira-happy-jump.png
  src/assets/laira/laira-on-woman-shoulder.png
  src/assets/laira/laira-open-arms.png
  src/assets/laira/laira-sitting.png
  src/assets/laira/laira-standing.png
  src/assets/laira/laira-waiving.png
  src/assets/laira/laira-walking.png
  src/components/donation/Steps/Tip/Tip.tsx
  src/components/donation/Steps/common/Summary.tsx
  src/content/benefits/icons/roadmap1_wb.webp
  src/content/benefits/icons/roadmap2_wb.webp
  src/content/benefits/icons/roadmap3_wb.webp
  src/content/benefits/icons/roadmap4_wb.webp
  src/content/benefits/index.ts
  src/content/benefits/sf-benefits.ts
  src/content/benefits/types.ts
  src/pages/Home/Animation/AnimatedSVG.tsx
  src/pages/Home/Animation/MobileAnimation.tsx
  src/pages/UserDashboard/Donations/NoDonations.tsx
  src/pages/informational/DonorInfo/BottomCta.tsx
  src/pages/informational/NonprofitInfo/BottomCta.tsx
  src/pages/informational/NonprofitInfo/DonationFormInfo.tsx
  src/pages/informational/NonprofitInfo/Hero.tsx
  src/pages/informational/NonprofitInfo/NonprofitInfo.tsx
  src/pages/informational/NonprofitInfo/WhyBG.tsx
  src/pages/informational/NonprofitInfo/images/hero.png
Labels: bug, enhancement

#2992 Fix missing asset
  src/pages/Widget/Preview.tsx
Labels: bug

#2997 Donate form screen short carousel
  src/assets/images/donation-form-mobile.png
  src/assets/images/donation-form.png
  src/components/donation/StepsCarousel.tsx
  src/components/donation/index.ts
  src/components/donation/screenshots/checkout.png
  src/components/donation/screenshots/form.png
  src/components/donation/screenshots/result.png
  src/components/donation/screenshots/split.png
  src/components/donation/screenshots/summary.png
  src/components/donation/screenshots/tip.png
  src/pages/informational/DonorInfo/DonationFormInfo.tsx
  src/pages/informational/NonprofitInfo/DonationFormInfo.tsx
  src/pages/informational/NonprofitInfo/FellowNonProfits.tsx
Labels: enhancement

#2998 Donation Form SF msg bottom padding
  src/components/donation/Steps/common/Summary.tsx
Labels: bug

#3000 FIX: single program not loading
  src/services/aws/programs.ts
Labels: bug, priority

#3004 BG-1296 Incrementors supports all currencies
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Incrementers.tsx
Labels: enhancement

#3005 BG-1350 ComplyDog sans Quill
  public/scripts/complydog-sans-quill.min.js
  public/scripts/cookie-consent-notice.js
Labels: bug, good first issue

#3003 BG-1344: Program donate checkbox
  src/pages/Admin/Charity/EditProfile/update.ts
  src/pages/Admin/Charity/Settings/Form.tsx
  src/pages/Admin/Charity/Settings/HideBGTipCheckbox.tsx
  src/pages/Admin/Charity/Settings/Settings.tsx
  src/pages/Admin/Charity/Settings/types.ts
  src/services/aws/programs.ts
  src/types/aws/ap/index.ts
Labels: good first issue

#3006 BG-1354: new account logins is not proceeding
  src/slices/auth.ts
Labels: bug, priority

#3007 BG-1323 testimonial copy fixes
  src/content/testimonials/index.ts
Labels: bug

#3009 Update donations link
  src/App/Header/UserMenu/Menu.tsx
  src/pages/DonateFiatThanks.tsx
Labels: bug

#3016 Admin Settings: fee corrected & copy updates
  src/pages/Admin/Charity/Settings/Form.tsx
  src/pages/Admin/Charity/Settings/HideBGTipCheckbox.tsx
Labels: bug

#3015 Payout min edit UI
  src/components/form/Field.tsx
  src/pages/Admin/Charity/Settings/Form.tsx
  src/pages/Admin/Charity/Settings/Settings.tsx
  src/pages/Admin/Charity/Settings/types.ts
  src/types/aws/ap/index.ts
Labels: good first issue

#3017 Methods widget config
  package.json
  src/components/Icon/icons.ts
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
  src/components/donation/Steps/DonateMethods/Stocks/Form.tsx
  src/components/donation/Steps/types.ts
  src/pages/DonateWidget/parseConfig.ts
  src/pages/Widget/Configurer/Configurer.tsx
  src/pages/Widget/Configurer/DonateMethods/DonateMethods.tsx
  src/pages/Widget/Configurer/DonateMethods/index.ts
  src/pages/Widget/Configurer/schema.ts
  src/pages/Widget/Preview.tsx
  src/pages/Widget/Snippet/Snippet.tsx
  src/pages/Widget/Widget.tsx
  src/types/lists.ts
  src/types/widget.ts
  tsconfig.json
  yarn.lock
Labels: good first issue

#3018 Donate methods admin setting
  src/App/Header/UserMenu/Menu.tsx
  src/components/CurrencySelector/CurrencySelector.tsx
  src/components/DonateMethods.tsx
  src/components/Selector/MultiSelector.tsx
  src/components/Selector/NativeSelect.tsx
  src/components/Selector/Selector.tsx
  src/components/TokenField/TokenField.tsx
  src/components/donation/Steps/common/Summary.tsx
  src/components/form/CheckField.tsx
  src/components/form/Field.tsx
  src/components/form/Input.tsx
  src/components/form/Radio.tsx
  src/components/form/helpers.ts
  src/helpers/index.ts
  src/helpers/unpack.ts
  src/pages/Admin/Charity/Settings/Form.tsx
  src/pages/Admin/Charity/Settings/Settings.tsx
  src/pages/Admin/Charity/Settings/types.ts
  src/pages/Donate/Content.tsx
  src/pages/DonateFiatThanks.tsx
  src/pages/Home/Benefits/Path.tsx
  src/pages/Widget/Configurer/Configurer.tsx
  src/pages/Widget/Configurer/DonateMethods/index.ts
  src/pages/Widget/Configurer/schema.ts
  src/pages/Widget/Widget.tsx
  src/types/aws/ap/index.ts
  src/types/components.ts
  src/types/widget.ts
Labels: good first issue

#3022 BG-1369, BG-1371: website update
  src/App/Header/index.tsx
  src/App/__tests__/App.test.tsx
  src/App/constants.ts
Labels: refactor

#3020 Add lefthook git hooks
  lefthook.yml
  package.json
  yarn.lock
Labels: dependencies

#3023 BG-1370: copy from path to text
  src/pages/Home/Animation/AnimatedSVG.tsx
Labels: refactor

#3021 Endow videos UI
  package.json
  src/components/Icon/icons.ts
  src/constants/routes.ts
  src/layout/DashboardLayout/Sidebar/Sidebar.tsx
  src/pages/Admin/Charity/Media/FeaturedVideos.tsx
  src/pages/Admin/Charity/Media/Media.tsx
  src/pages/Admin/Charity/Media/VideoEditor.tsx
  src/pages/Admin/Charity/Media/VideoPreview.tsx
  src/pages/Admin/Charity/Media/Videos/List.tsx
  src/pages/Admin/Charity/Media/Videos/Videos.tsx
  src/pages/Admin/Charity/Media/Videos/index.ts
  src/pages/Admin/Charity/Media/index.ts
  src/pages/Admin/Charity/Media/routes.tsx
  src/pages/Admin/Charity/index.tsx
  src/pages/Admin/constants.ts
  src/pages/BankingApplications/usePagination.ts
  src/pages/Profile/Body/GeneralInfo/GeneralInfo.tsx
  src/pages/Profile/Body/GeneralInfo/Media.tsx
  src/services/aws/aws.ts
  src/services/aws/media.ts
  src/services/aws/usePaginatedMedia.ts
  src/styles/components.css
  src/types/aws/ap/index.ts
  yarn.lock
Labels: good first issue, design

#3033 BG-1374: admin settings tweaks
  src/pages/Admin/Charity/Settings/Form.tsx
  src/pages/Admin/Charity/Settings/ReceiptMsg.tsx
Labels: refactor

#3034 BG-1364 Cloudsearch query
  src/services/aws/aws.ts
  src/types/aws/ap/index.ts
Labels: enhancement, good first issue

#3035 Widget custom title and description
  src/components/form/CheckField.tsx
  src/pages/DonateWidget/Content.tsx
  src/pages/DonateWidget/parseConfig.ts
  src/pages/Widget/Configurer/Configurer.tsx
  src/pages/Widget/Configurer/schema.ts
  src/pages/Widget/Preview.tsx
  src/pages/Widget/Snippet/Snippet.tsx
  src/pages/Widget/Widget.tsx
  src/styles/components.css
  src/types/widget.ts
Labels: enhancement, good first issue

#3036 BG-1366: Donation widget accent color
  src/components/CurrencySelector/CurrencyOptions.tsx
  src/components/LoaderRing.tsx
  src/components/Selector/constants.ts
  src/components/TokenField/TokenOptions.tsx
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Frequency.tsx
  src/components/donation/Steps/Result/Err.tsx
  src/components/donation/Steps/Result/Loading.tsx
  src/components/donation/Steps/Result/Success/index.tsx
  src/components/donation/Steps/Share.tsx
  src/components/donation/Steps/Submit/DAFCheckout/ManualDonation.tsx
  src/components/donation/Steps/Submit/Loader.tsx
  src/components/donation/Steps/Submit/Stocks.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Checkout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/components/donation/Steps/Tip/Tip.tsx
  src/components/donation/Steps/common/BackBtn.tsx
  src/components/donation/Steps/common/ContinueBtn.tsx
  src/components/donation/Steps/types.ts
  src/index.css
  src/pages/DonateWidget/Content.tsx
  src/pages/DonateWidget/DonateWidget.tsx
  src/pages/DonateWidget/parseConfig.ts
  src/pages/Widget/Configurer/Configurer.tsx
  src/pages/Widget/Preview.tsx
  src/pages/Widget/Snippet/Snippet.tsx
  src/pages/Widget/Widget.tsx
  src/styles/components.css
  src/types/widget.ts
Labels: good first issue
