Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2024-03, with the labels that each got.

#2755 BG-1179: reduce top padding for DonateFiatThanks
  src/App/App.tsx
  src/pages/DonateFiatThanks.tsx
Labels: design

#2754 Log error on paypal checkout button loading
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Paypal.tsx
  src/contexts/ErrorContext/ErrorContext.tsx
  src/errors/ErrorBoundary.tsx
  src/helpers/logger.ts
Labels: enhancement

#2756 Towards BG-1133: New brand colors included
  src/components/ContentLoader.tsx
  src/components/CurrencySelector/CurrencySelector.tsx
  src/components/Divider.tsx
  src/components/FileDropzone/FileDropzone.tsx
  src/components/ImgEditor/ImgEditor.tsx
  src/components/KYCForm/KYCForm.tsx
  src/components/Prompt/Prompt.tsx
  src/components/donation/Steps/DonateMethods/Stocks/Form.tsx
  src/components/donation/Steps/Submit/DAFCheckout/ManualDonation.tsx
  src/components/donation/Steps/Submit/Stocks.tsx
  src/pages/Admin/Charity/Banking/PayoutMethod/DeletePrompt.tsx
  src/pages/Admin/Charity/Banking/PayoutMethod/Prompt.tsx
  src/pages/Admin/Charity/Donations/Table.tsx
  src/pages/Application/Prompt.tsx
  src/pages/Applications/Applications.tsx
  src/pages/Applications/Filter/index.tsx
  src/pages/Applications/LoadMoreBtn.tsx
  src/pages/BankingApplication/Prompt.tsx
  src/pages/BankingApplications/Filter/index.tsx
  src/pages/BankingApplications/LoadMoreBtn.tsx
  src/pages/BankingApplications/Prompt.tsx
  src/pages/Donations/DonationsSection.tsx
  src/pages/Donations/Filter/index.tsx
  src/pages/Donations/LoadMoreBtn.tsx
  src/pages/Gift/Claim/Form.tsx
  src/pages/Gift/Mailer/Form.tsx
  src/pages/Gift/Purchase/Progress.tsx
  src/pages/Leaderboard/Table/index.tsx
  src/pages/Marketplace/Toolbar/Sorter.tsx
  src/pages/Profile/Body/Program/Milestones.tsx
  src/pages/Registration/Steps/OrgDetails/Form/index.tsx
  src/pages/Registration/Steps/ProgressIndicator.tsx
  src/pages/Widget/Preview/DonateMethods/DonateMethods.tsx
  src/pages/Widget/Preview/DonateMethods/StocksSample.tsx
  src/styles/amplify.css
  src/styles/components.css
  src/styles/utilities.css
  tailwind.config.js
Labels: design, refactor

#2719 Towards BG-1106, Closes BG-1131: Donate to BG step
  src/assets/images/waving-character.png
  src/components/CurrencySelector/CurrencyOptions.tsx
  src/components/CurrencySelector/CurrencySelector.tsx
  src/components/donation/Steps/CurrentStep.tsx
  src/components/donation/Steps/DonateMethods/Daf/Form.tsx
  src/components/donation/Steps/Splits/Splits.tsx
  src/components/donation/Steps/Submit/Crypto/Crypto.tsx
  src/components/donation/Steps/Submit/DAFCheckout/ChariotDonation.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Paypal.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/components/donation/Steps/Summary/Summary.tsx
  src/components/donation/Steps/Tip/Tip.tsx
  src/components/donation/Steps/Tip/index.ts
  src/components/donation/Steps/common/Currency.tsx
  src/components/donation/Steps/common/SplitSummary.tsx
  src/components/donation/Steps/common/Summary.tsx
  src/services/apes/apes.ts
  src/slices/donation/donation.ts
  src/slices/donation/sendDonation/index.ts
  src/slices/donation/types.ts
  src/types/aws/apes/donation.ts
  src/types/components.ts
Labels: good first issue, refactor

#2763 Update deps
  package.json
  src/pages/Marketplace/Toolbar/Search.tsx
  yarn.lock
Labels: dependencies

#2762 Update payloads with recent devops update
  src/components/donation/Steps/Submit/DAFCheckout/ChariotDonation.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Paypal.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/services/apes/apes.ts
  src/slices/donation/sendDonation/index.ts
  src/types/aws/apes/donation.ts
Labels: bug

#2766 Signup page rework
  src/App/App.tsx
  src/App/Header/UserMenu/UserMenu.tsx
  src/App/Header/index.tsx
  src/App/constants.ts
  src/assets/icons/google.svg
  src/components/Icon/icons.ts
  src/components/form/Form.tsx
  src/components/form/Input.tsx
  src/components/form/PasswordInput.tsx
  src/components/form/index.ts
  src/constants/routes.ts
  src/contexts/ErrorContext/ErrorContext.tsx
  src/helpers/determineAuthRedirectPath.ts
  src/helpers/index.ts
  src/hooks/useCounter.ts
  src/pages/Donate/FAQ.tsx
  src/pages/SignUp/ConfirmForm.tsx
  src/pages/SignUp/SignUp.tsx
  src/pages/SignUp/SignupForm/SignupForm.tsx
  src/pages/SignUp/SignupForm/UserTypeSelector.tsx
  src/pages/SignUp/SignupForm/index.ts
  src/pages/SignUp/Success.tsx
  src/pages/SignUp/constants.ts
  src/pages/SignUp/index.ts
  src/pages/SignUp/types.ts
  src/pages/Signin/Signin.tsx
  src/schemas/string.ts
  src/styles/components.css
  src/styles/utilities.css
Labels: design

#2767 Towards BG-1133: update field and button styles
  src/components/CountrySelector/CountrySelector.tsx
  src/components/CountrySelector/Options.tsx
  src/components/CurrencySelector/CurrencyOptions.tsx
  src/components/CurrencySelector/CurrencySelector.tsx
  src/components/FileDropzone/DropzoneText.tsx
  src/components/FileDropzone/FileDropzone.tsx
  src/components/ImgEditor/ImgEditor.tsx
  src/components/RichText/RichText.tsx
  src/components/Selector/MultiSelector.tsx
  src/components/Selector/constants.ts
  src/components/TokenField/TokenField.tsx
  src/components/donation/Steps/Tip/Tip.tsx
  src/components/form/constants.ts
  src/pages/Marketplace/Toolbar/Search.tsx
  src/pages/Widget/Configurer/EndowmentSelector/EndowmentSelector.tsx
  src/pages/Widget/Configurer/Form.tsx
  src/styles/components.css
  src/styles/richtext.css
  tailwind.config.js
Labels: design, refactor

#2770 remove auth UI
  package.json
  src/App/__tests__/App.test.tsx
  src/index.css
  src/index.tsx
  src/styles/amplify.css
  yarn.lock
Labels: dependencies

#2768 Closes BG-1086: stripe recurring
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Frequency.tsx
  src/components/donation/Steps/DonateMethods/Stripe/types.ts
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/components/donation/Steps/common/Summary.tsx
  src/slices/donation/types.ts
Labels: good first issue

#2773 Towards BG-1133: Donate UI style updates
  src/App/Header/NavDropdown.tsx
  src/components/BankDetails/BankDetails.tsx
  src/components/CurrencySelector/CurrencyOptions.tsx
  src/components/CurrencySelector/CurrencySelector.tsx
  src/components/Icon/DrawerIcon.tsx
  src/components/Icon/icons.ts
  src/components/KYCForm/Form/index.tsx
  src/components/Selector/Selector.tsx
  src/components/Selector/constants.ts
  src/components/Selector/types.ts
  src/components/TokenField/TokenField.tsx
  src/components/TokenField/TokenSelector.tsx
  src/components/donation/Steps/DonateMethods/Crypto/Form/index.tsx
  src/components/donation/Steps/DonateMethods/Daf/Form.tsx
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
  src/components/donation/Steps/DonateMethods/Stocks/Form.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Frequency.tsx
  src/components/donation/Steps/Result/Err.tsx
  src/components/donation/Steps/Result/Success/Share.tsx
  src/components/donation/Steps/Splits/Splits.tsx
  src/components/donation/Steps/Submit/Crypto/TxSubmit/TxSubmit.tsx
  src/components/donation/Steps/Submit/DAFCheckout/ManualDonation.tsx
  src/components/donation/Steps/Submit/Stocks.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Checkout.tsx
  src/components/donation/Steps/Summary/DonorForm.tsx
  src/components/donation/Steps/Tip/Tip.tsx
  src/components/donation/Steps/common/BackBtn.tsx
  src/components/donation/Steps/common/ContinueBtn.tsx
  src/components/donation/Steps/common/Summary.tsx
  src/components/donation/Steps/index.tsx
  src/components/form/CheckField.tsx
  src/components/form/Field.tsx
  src/components/form/Label.tsx
  src/components/form/helpers.ts
  src/pages/Admin/Charity/Banking/PayoutMethod/Prompt.tsx
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Sidebar/SidebarOpener/SidebarOpener.tsx
  src/pages/Application/Prompt.tsx
  src/pages/Applications/Filter/RegStatusDropdown.tsx
  src/pages/BankingApplication/Prompt.tsx
  src/pages/BankingApplications/Filter/StatusDropdown.tsx
  src/pages/BankingApplications/Prompt.tsx
  src/pages/Donate/Content.tsx
  src/pages/Donate/FAQ.tsx
  src/pages/Donate/OrgCard.tsx
  src/pages/Donations/Filter/CurrencyDropdown.tsx
  src/pages/Donations/Filter/NetworkDropdown.tsx
  src/pages/Registration/Steps/ContactDetails/Form/index.tsx
  src/pages/Registration/Steps/OrgDetails/Form/index.tsx
  src/pages/StripePaymentStatus.tsx
  src/pages/Widget/Configurer/Form.tsx
  src/pages/Widget/Preview/DonateMethods/StocksSample.tsx
  src/pages/Widget/Preview/DonateMethods/StripeSample.tsx
  src/styles/components.css
Labels: design, refactor

#2772 Prefer package.json formatting to biome formatting
  biome.json
  package.json
Labels: bug

#2781 Update deps
  package.json
  yarn.lock
Labels: dependencies

#2782 Closes BG-1184, related to BG-1172: donate widget page render loop
  biome.json
  public/scripts/intercom.js
Labels: bug

#2783 Donate: currencies loaded as part of dropdown should include those supported by both PayPal and Stripe
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/services/apes/apes.ts
Labels: bug, enhancement

#2786 Make header sticky when scrolling
  src/App/Header/useHeaderClassNames.ts
Labels: enhancement

#2790 Update payload types
  src/components/donation/Steps/Submit/DAFCheckout/ChariotDonation.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Paypal.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/services/apes/apes.ts
  src/slices/donation/sendDonation/index.ts
  src/types/aws/apes/donation.ts
Labels: bug

#2785 BG-1179: Adjust page paddings affected by header positioning
  src/pages/Application/Application.tsx
  src/pages/Applications/Applications.tsx
  src/pages/BankingApplication/BankingApplication.tsx
  src/pages/BankingApplications/BankingApplications.tsx
  src/pages/Donations/index.tsx
  src/pages/Leaderboard/index.tsx
  src/pages/Registration/index.tsx
  src/pages/StripePaymentStatus.tsx
Labels: design

#2791 BG-1190 & BG-1191 Sentry fixes: env & pkg ver
  package.json
  src/helpers/logger.ts
  src/index.tsx
  yarn.lock
Labels: bug

#2795 Closes BG-1194: Incorrect dollar values shown in summary
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/components/donation/Steps/Summary/Summary.tsx
  src/components/donation/Steps/common/Currency.tsx
  src/types/aws/apes/donation.ts
  src/types/components.ts
Labels: bug

#2796 Closes BG-1195: Image size tooltip
  src/components/ImgEditor/ImgEditor.tsx
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/ProgramEditor/Form.tsx
  src/pages/Admin/Charity/ProgramEditor/Milestones/Milestone.tsx
  src/pages/Admin/Charity/ProgramEditor/schema.ts
Labels: bug

#2715 BG-1129: Blog posts from Wordpress
  src/App/App.tsx
  src/App/constants.ts
  src/constants/routes.ts
  src/constants/urls.ts
  src/pages/Blog/Media.tsx
  src/pages/Blog/Post.tsx
  src/pages/Blog/Posts.tsx
  src/pages/Blog/usePagination.ts
  src/services/wordpress/index.ts
  src/store/store.ts
  src/styles/components.css
  src/types/wordpress.ts
Labels: wip, feature-branch

#2797 Closes BG-1193: Endowment slug
  src/App/Header/UserMenu/EndowmentLink.tsx
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/EditProfile/Slug.tsx
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Admin/Charity/EditProfile/update.ts
  src/pages/Admin/Charity/EditProfile/useEditProfile.ts
  src/pages/Admin/Charity/Programs/List.tsx
  src/pages/Admin/Charity/Seo.tsx
  src/pages/Admin/Sidebar/Header/Header.tsx
  src/pages/Donate/index.tsx
  src/pages/DonateWidget/DonateWidget.tsx
  src/pages/Profile/index.tsx
  src/pages/Widget/Widget.tsx
  src/services/aws/aws.ts
  src/services/aws/useEndowment.ts
  src/services/types.ts
  src/types/aws/ap/index.ts
Labels: good first issue

#2800 Towards BG-1201: EIN/reg number validation
  src/pages/Registration/Steps/Documentation/FSA/schema.ts
  src/pages/Registration/Steps/Documentation/NonFSA/NonFSA.tsx
  src/schemas/string.ts
Labels: bug

#2799 BG-1206 Various word changes
  src/components/donation/Steps/Submit/StripeCheckout/Checkout.tsx
  src/pages/Admin/Charity/EditProfile/Slug.tsx
  src/pages/Admin/constants.ts
  src/pages/Donations/NoDonations.tsx
  src/pages/Donations/index.tsx
  src/pages/SignUp/ConfirmForm.tsx
  src/pages/SignUp/SignupForm/SignupForm.tsx
  src/pages/Signin.tsx
  src/pages/Widget/Configurer/Configurer.tsx
Labels: bug

#2801 ein and reg num validation (#2800)
  src/pages/Registration/Steps/Documentation/FSA/schema.ts
  src/pages/Registration/Steps/Documentation/NonFSA/NonFSA.tsx
  src/schemas/string.ts
Labels: duplicate

#2788 BG-1188: registration progress indicator must revert to desktop position
  src/pages/Registration/Steps/ProgressIndicator.tsx
Labels: bug, design

#2798 Towards BG-1192: Settings page + receipt msg
  src/components/Icon/icons.ts
  src/constants/routes.ts
  src/pages/Admin/Charity/EditProfile/update.ts
  src/pages/Admin/Charity/EditProfile/useEditProfile.ts
  src/pages/Admin/Charity/ProgramEditor/useSubmit.ts
  src/pages/Admin/Charity/Settings/Form.tsx
  src/pages/Admin/Charity/Settings/ReceiptMsg.tsx
  src/pages/Admin/Charity/Settings/Settings.tsx
  src/pages/Admin/Charity/Settings/constants.ts
  src/pages/Admin/Charity/Settings/index.ts
  src/pages/Admin/Charity/Settings/types.ts
  src/pages/Admin/Charity/common/index.ts
  src/pages/Admin/Charity/common/useUpdateEndowment.ts
  src/pages/Admin/Charity/index.tsx
  src/pages/Admin/Sidebar/Sidebar.tsx
  src/pages/Admin/constants.ts
  src/services/aws/aws.ts
  src/services/types.ts
  src/types/aws/ap/index.ts
Labels: good first issue

#2803 Registration update
  src/services/aws/registration/registration.ts
Labels: refactor

#2813 BG-1209 BG-1212 Minor fixes reg & nonprofit dash
  src/pages/Admin/Charity/Dashboard/Dashboard.tsx
  src/pages/Registration/Steps/Documentation/FSA/Form/index.tsx
  src/pages/Registration/Steps/Documentation/NonFSA/NonFSA.tsx
Labels: bug

#2815 BG-1203 Header Menus restructuring
  src/App/Footer/Footer.tsx
  src/App/Header/NavDropdown.tsx
  src/App/Header/UserMenu/Menu.tsx
  src/App/Header/UserMenu/UserMenu.tsx
Labels: refactor

#2816 BG-1218 Donation splits slider: swap display ordering
  src/components/donation/Steps/Splits/Splits.tsx
Labels: bug

#2814 Closes BG-1059, BG-1060: Handle new unclaimed endowments
  src/components/Icon/icons.ts
  src/components/Tooltip.tsx
  src/components/VerifiedIcon.tsx
  src/pages/Donate/Content.tsx
  src/pages/Donate/OrgCard.tsx
  src/pages/Marketplace/ActiveFilters.tsx
  src/pages/Marketplace/Cards/Card.tsx
  src/pages/Marketplace/Cards/useCards.ts
  src/pages/Marketplace/Filter/Filter.tsx
  src/pages/Marketplace/Filter/VerificationFilter.tsx
  src/pages/Profile/Body/Body.tsx
  src/pages/Widget/Configurer/EndowmentSelector/Options.tsx
  src/services/aws/aws.ts
  src/slices/components/marketFilter/constants.ts
  src/slices/components/marketFilter/marketFilter.ts
  src/slices/components/marketFilter/types.ts
  src/types/aws/ap/index.ts
  src/types/aws/common.ts
Labels: good first issue, refactor

#2820 Cherry pick #2818 to staging
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/types/aws/ap/registration.ts
Labels: bug, duplicate, priority

#2802 BG-1197: Update dummy widget shown on widget configuration page w/ new donation component.
  src/components/QueryLoader.tsx
  src/components/donation/AdvancedOptions.tsx
  src/components/donation/Steps/CurrentStep.tsx
  src/components/donation/Steps/DonateMethods/Crypto/Crypto.tsx
  src/components/donation/Steps/DonateMethods/Crypto/Form.tsx
  src/components/donation/Steps/DonateMethods/Daf/types.ts
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Frequency.tsx
  src/components/donation/Steps/DonateMethods/Stripe/types.ts
  src/components/donation/Steps/Splits/LockedSplitSlider.tsx
  src/components/donation/Steps/Splits/Splits.tsx
  src/components/donation/Steps/Splits/index.ts
  src/components/donation/Steps/Submit/Crypto/Crypto.tsx
  src/components/donation/Steps/Submit/DAFCheckout/DAFCheckout.tsx
  src/components/donation/Steps/Submit/Err.tsx
  src/components/donation/Steps/Submit/Loader.tsx
  src/components/donation/Steps/Submit/Stocks.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Checkout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/components/donation/Steps/Summary/Summary.tsx
  src/components/donation/Steps/Tip/Tip.tsx
  src/components/donation/Steps/index.tsx
  src/components/donation/Steps/types.ts
  src/components/donation/index.ts
  src/pages/DonateWidget/Content.tsx
  src/pages/DonateWidget/parseConfig.ts
  src/pages/Widget/Configurer/Configurer.tsx
  src/pages/Widget/Configurer/Form.tsx
  src/pages/Widget/Configurer/types.ts
  src/pages/Widget/Preview.tsx
  src/pages/Widget/Preview/DonateMethods/AdvancedOptions.tsx
  src/pages/Widget/Preview/DonateMethods/DAFSample.tsx
  src/pages/Widget/Preview/DonateMethods/DonateMethods.tsx
  src/pages/Widget/Preview/DonateMethods/DonaterSample.tsx
  src/pages/Widget/Preview/DonateMethods/StocksSample.tsx
  src/pages/Widget/Preview/DonateMethods/StripeSample.tsx
  src/pages/Widget/Preview/DonateMethods/index.ts
  src/pages/Widget/Preview/Preview.tsx
  src/pages/Widget/Preview/index.ts
  src/pages/Widget/Snippet/Snippet.tsx
  src/pages/Widget/Widget.tsx
  src/services/aws/aws.ts
  src/slices/auth.ts
  src/slices/donation/types.ts
  src/slices/widget.ts
  src/types/aws/ap/index.ts
  src/types/widget.ts
Labels: enhancement, design

#2821 Remove chariot from the webapp
  .env.example
  amplify.yml
  package.json
  src/components/donation/Steps/DonateMethods/Daf/Form.tsx
  src/components/donation/Steps/Submit/DAFCheckout/ChariotDonation.tsx
  src/components/donation/Steps/Submit/DAFCheckout/DAFCheckout.tsx
  src/constants/env.ts
  src/services/apes/apes.ts
  yarn.lock
Labels: refactor
