Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2024-08, with the labels that each got.

#3198 Chariot prod key requirements
  src/components/donation/Steps/DonateMethods/Daf/Form.test.tsx
  src/components/donation/Steps/DonateMethods/Daf/Form.tsx
  src/components/donation/Steps/DonateMethods/helpers.ts
  src/components/donation/Steps/Splits/Splits.tsx
  src/components/donation/Steps/Submit/DAFCheckout/ChariotCheckout.tsx
  src/components/donation/Steps/Submit/DAFCheckout/toPlatformValues.ts
  src/components/donation/Steps/Tip/Tip.tsx
  src/components/donation/Steps/common/constants.ts
  src/components/donation/Steps/types.ts
  src/constants/common.ts
Labels: enhancement, refactor

#3201 Prefill billing details
  src/components/donation/Steps/Submit/StripeCheckout/Checkout.tsx
Labels: enhancement

#3206 DAF requirements (#3176)
  src/assets/icons/dafpay.svg
  src/components/DonateMethods/DonateMethods.tsx
  src/components/DonateMethods/helpers.test.ts
  src/components/DonateMethods/helpers.ts
  src/components/DonateMethods/index.ts
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
  src/pages/Admin/Charity/Settings/Form.tsx
  src/pages/Donate/Content.tsx
  src/pages/Widget/Configurer/Configurer.tsx
  src/pages/Widget/Widget.tsx
Labels: duplicate

#3207 Unset tribute when disabling honorary
  src/components/donation/Steps/Submit/DAFCheckout/ChariotCheckout.tsx
Labels: bug

#3209 QR display amount should include tip and fee allowance
  src/components/donation/Steps/Submit/Crypto/DirectMode.tsx
Labels: bug

#3214 DAFPay remove min donation amount
  src/components/donation/Steps/DonateMethods/Daf/Form.test.tsx
  src/components/donation/Steps/DonateMethods/Daf/Form.tsx
Labels: bug

#3215 Add tip in total
  src/components/donation/Steps/common/Summary.tsx
Labels: bug

#3216 Point directly to donate page
  src/pages/@sections/HeroBottom/Card.tsx
Labels: design / ux

#3217 Include 30cents processing
  src/components/donation/Steps/Summary/Summary.tsx
  src/components/donation/Steps/Summary/helpers.ts
Labels: bug

#3218 More strict slug validation client side
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Profile/index.tsx
  src/schemas/string.ts
Labels: bug

#3219 Cherry fixes
  package.json
  public/scripts/linkedin-tracking.js
  src/App/App.tsx
  src/components/donation/Steps/DonateMethods/Daf/Form.tsx
  src/components/donation/Steps/Submit/Crypto/DirectMode.tsx
  src/components/donation/Steps/Submit/DAFCheckout/ChariotCheckout.tsx
  src/components/donation/Steps/Summary/Summary.tsx
  src/components/donation/Steps/Summary/helpers.ts
  src/components/donation/Steps/common/Summary.tsx
  src/errors/ErrorBoundary.tsx
  src/index.css
  src/pages/@sections/HeroBottom/Card.tsx
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Profile/index.tsx
  src/schemas/string.ts
  yarn.lock
Labels: duplicate

#3221 Edit profile socials label and order
  src/App/App.tsx
  src/components/Status/Confirmed.tsx
  src/components/Status/index.ts
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/services/aws/aws.ts
  tailwind.config.js
Labels: bug, design / ux

#3222 Update 'Book a demo' button's link to new one
  src/constants/env.ts
  src/pages/informational/NonprofitInfo/BottomCta.tsx
  src/pages/informational/NonprofitInfo/Hero.tsx
Labels: enhancement

#3234 GTM script instead of individual gtag script
  public/scripts/gtag-init.js
  public/scripts/gtm-init.js
  src/components/Seo.tsx
Labels: enhancement

#3236 HOT FIX: app crashes when changing tip
  src/components/donation/Steps/Tip/Tip.tsx
Labels: bug

#3238 v2.4.4
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Incrementers.tsx
  src/components/donation/Steps/types.ts
  src/constants/common.ts
  src/pages/Admin/Charity/Donations/DonationsTable.tsx
  src/pages/Admin/Charity/Donations/Row.tsx
  src/pages/Admin/Charity/Donations/Table.tsx
  src/pages/Donate/Content.tsx
  src/pages/DonateWidget/DonateWidget.tsx
  src/pages/DonateWidget/parseConfig.ts
  src/pages/UserDashboard/Donations/Filter/NetworkDropdown.tsx
  src/pages/UserDashboard/Donations/MobileTable.tsx
  src/pages/UserDashboard/Donations/Table.tsx
  src/pages/UserDashboard/Donations/common.ts
  src/pages/UserDashboard/Donations/index.tsx
  src/pages/UserDashboard/Donations/types.ts
  src/pages/Widget/Configurer/Configurer.tsx
  src/pages/Widget/Configurer/Increments.tsx
  src/pages/Widget/Configurer/schema.ts
  src/pages/Widget/Preview.tsx
  src/pages/Widget/Snippet/Snippet.tsx
  src/pages/Widget/Widget.tsx
  src/services/aws/aws.ts
  src/types/aws/ap/donations.ts
  src/types/widget.ts
  tsconfig.json
Labels: duplicate

#3200 Gold transparency seal
  src/App/Footer/FooterV2.tsx
  src/assets/images/bg-logo-503c.png
  src/components/Image/DappLogo.tsx
Labels: design / ux

#3252 Update search endpoint to v1
  src/pages/Marketplace/Cards/useCards.ts
  src/services/aws/aws.ts
  src/services/aws/mock.ts
  src/types/aws/ap/index.ts
Labels: bug, enhancement

#3251 Social media icons footer donate share
  src/App/Footer/FooterV2.tsx
  src/App/Footer/Socials.tsx
  src/App/Layout.tsx
  src/App/constants.ts
  src/App/types.ts
  src/assets/icons/social/facebook.png
  src/assets/icons/social/instagram.png
  src/assets/icons/social/linkedin.png
  src/assets/icons/social/telegram.png
  src/assets/icons/social/x.png
  src/assets/icons/social/youtube.png
  src/components/donation/Steps/Share.tsx
Labels: design / ux

#3264 NPO profile icons
  src/assets/icons/social/discord.svg
  src/assets/icons/social/tiktok.png
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/Socials.tsx
Labels: design / ux

#3266 Reset password remaining time copy
  src/pages/ResetPassword/SetPasswordForm.tsx
Labels: design / ux

#3267 Fix: user menu can't be scrolled
  src/App/Header/NavDropdown.tsx
  src/App/Header/UserMenu/EndowmentLink.tsx
  src/App/Header/UserMenu/Menu.tsx
Labels: bug, enhancement
