Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2024-01, with the labels that each got.

#2607 BG-980: Speed up loading of some `profile` endpoint
  src/App/Header/UserMenu/EndowmentLink.tsx
  src/components/QueryLoader.tsx
  src/pages/Admin/Charity/Banking/VerificationStatus.tsx
  src/pages/Admin/Charity/Dashboard/Dashboard.tsx
  src/pages/Admin/Charity/Donations/DonationsTable.tsx
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Admin/Charity/EditProfile/update.ts
  src/pages/Admin/Charity/Programs/List.tsx
  src/pages/Admin/Charity/Seo.tsx
  src/pages/Admin/Sidebar/Header/Header.tsx
  src/pages/Applications/Applications.tsx
  src/pages/BankingApplications/BankingApplications.tsx
  src/pages/Donate/index.tsx
  src/pages/DonateWidget/ApiKeyChecker.tsx
  src/pages/DonateWidget/Content.tsx
  src/pages/DonateWidget/DonateWidget.tsx
  src/pages/Donations/index.tsx
  src/pages/Marketplace/Cards/index.tsx
  src/pages/Marketplace/Cards/useCards.ts
  src/pages/Profile/Body/Body.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/Balances.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/DetailsColumn.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/Socials.tsx
  src/pages/Profile/Body/GeneralInfo/GeneralInfo.tsx
  src/pages/Profile/index.tsx
  src/services/apes/apes.ts
  src/services/apes/donations/usePaginatedDonations.ts
  src/services/aws/aws.ts
  src/services/aws/useEndowment.ts
  src/types/aws/ap/index.ts
  src/types/aws/apes/index.ts
  src/types/third-party/redux.ts
Labels: enhancement

#2620 BG-1021: web-app crash after login
  src/App/Header/UserMenu/UserMenu.tsx
Labels: bug, duplicate

#2617 Tooling upgrade to Rsbuild
  .env.example
  .github/workflows/javascript.yml
  .gitignore
  .gitpod.yml
  .node-version
  .prettierignore
  .yarn/releases/yarn-3.3.0.cjs
  .yarn/releases/yarn-4.0.2.cjs
  .yarnrc.yml
  README.md
  amplify.yml
  amplify/.config/project-config.json
  amplify/cli.json
  amplify/team-provider-info.json
  bin/setup
  codecov-report.json
  codecov.yml
  config-overrides.js
  package.json
  prettier.config.js
  public/manifest.json
  public/robots.txt
  rsbuild.config.js
  src/App/App.tsx
  src/App/__tests__/App.test.tsx
  src/assets/favicon.png
  src/aws-exports.js
  src/components/Copier/Copier.test.tsx
  src/components/CsvExporter/__tests__/CsvExporter.test.tsx
  src/components/ImgEditor/ImgCropper.tsx
  src/components/RichText/RichText.tsx
  src/components/RichText/RichTextEditor.tsx
  src/constants/env.ts
  src/env.d.ts
  src/helpers/__tests__/cleanObject.test.ts
  src/helpers/__tests__/idParamToNum.test.ts
  src/helpers/admin/flatten.test.ts
  src/helpers/admin/getPayloadDiff.test.ts
  src/helpers/decimal/decimal.test.ts
  src/helpers/evm/toTuple.test.ts
  src/helpers/getFilePreviews/getFilePreviews.test.ts
  src/helpers/uploadFiles.test.ts
  src/index.css
  src/index.html
  src/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/schemas/__tests__/string.test.ts
  src/setupTests.ts
  src/styles/amplify.css
  src/styles/base.css
  src/styles/components.css
  src/styles/richtext.css
  src/styles/utilities.css
  tailwind.config.js
  vitest.config.ts
  yarn.lock
Labels: enhancement, dependencies

#2622 Updates from `master`
  public/scripts/gtag-init.js
  public/scripts/hotjar-tracking.js
  public/scripts/intercom.js
  public/scripts/linkedin-tracking.js
  public/scripts/meta-pixel.js
  public/scripts/twitter-conversion-tracking.js
  src/App/Footer/Footer.tsx
  src/App/Header/UserMenu/EndowmentLink.tsx
  src/App/__tests__/App.test.tsx
  src/components/KYC/index.tsx
  src/components/QueryLoader.tsx
  src/constants/chains.ts
  src/index.html
  src/pages/Admin/Charity/Banking/PayoutMethod/Loaded.tsx
  src/pages/Admin/Charity/Banking/VerificationStatus.tsx
  src/pages/Admin/Charity/Dashboard/Dashboard.tsx
  src/pages/Admin/Charity/Donations/DonationsTable.tsx
  src/pages/Admin/Charity/Donations/Table.tsx
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Admin/Charity/EditProfile/update.ts
  src/pages/Admin/Charity/Programs/List.tsx
  src/pages/Admin/Charity/Seo.tsx
  src/pages/Admin/Sidebar/Header/Header.tsx
  src/pages/Applications/Applications.tsx
  src/pages/BankingApplications/BankingApplications.tsx
  src/pages/Donate/index.tsx
  src/pages/DonateWidget/ApiKeyChecker.tsx
  src/pages/DonateWidget/Content.tsx
  src/pages/DonateWidget/DonateWidget.tsx
  src/pages/Donations/Table.tsx
  src/pages/Donations/index.tsx
  src/pages/Marketplace/Cards/index.tsx
  src/pages/Marketplace/Cards/useCards.ts
  src/pages/Profile/Body/Body.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/Balances.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/DetailsColumn.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/Socials.tsx
  src/pages/Profile/Body/GeneralInfo/GeneralInfo.tsx
  src/pages/Profile/index.tsx
  src/services/apes/apes.ts
  src/services/apes/donations/usePaginatedDonations.ts
  src/services/aws/aws.ts
  src/services/aws/useEndowment.ts
  src/types/aws/ap/index.ts
  src/types/aws/apes/donation.ts
  src/types/aws/apes/index.ts
  src/types/third-party/redux.ts
Labels: duplicate

#2623 BG-1000: Show validation message from WISE
  src/pages/Admin/Charity/Banking/Banking.tsx
  src/pages/Registration/Steps/Banking/useSubmit.ts
  src/services/aws/wise.ts
Labels: bug, enhancement

#2624 BG-1030: Leaderboard crash
  src/pages/Leaderboard/DonationMetrics.tsx
  src/pages/Leaderboard/Table/Row/index.tsx
  src/services/aws/business_metrics.ts
  src/types/aws/ap/index.ts
Labels: bug

#2626 BG-1014: Fee presentation update
  src/components/donation/Steps/Submit/Breakdown/Breakdown.tsx
  src/components/donation/Steps/Submit/Breakdown/estimateDonation.ts
Labels: refactor

#2628 Pass all Image.props to nested img element
  src/components/Image/Image.tsx
Labels: refactor

#2627 Use `defaultLogo` in `onError` in Leaderboard row image
  src/pages/Leaderboard/Table/Row/index.tsx
Labels: bug

#2629 BG-1005: Fix /auth-redirector URL appearing after redirecting
  src/pages/OAuthRedirector.tsx
Labels: bug

#2630 FIX: can't set default approved banking -details
  src/pages/Admin/Charity/Banking/PayoutMethod/Loaded.tsx
Labels: bug, priority

#2631 BG-1019: Bank form to use new wise-proxy
  src/components/BankDetails/BankDetails.tsx
  src/components/BankDetails/CurrencyOptions.tsx
  src/components/BankDetails/CurrencySelector.tsx
  src/components/BankDetails/ExpectedFunds.tsx
  src/components/BankDetails/RecipientDetails/AccountRequirementsSelector.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetails.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/Form.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RequirementField.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/constants.ts
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/formToCreateRecipientRequest.ts
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/useRecipientDetailsForm/createFieldSchema.ts
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/useRecipientDetailsForm/createSchema.ts
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/useRecipientDetailsForm/index.ts
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/useRecipientDetailsForm/useRecipientDetailsForm.ts
  src/components/BankDetails/RecipientDetails/helpers/dot.ts
  src/components/BankDetails/RecipientDetails/helpers/getDefaultValues.ts
  src/components/BankDetails/RecipientDetails/helpers/index.ts
  src/components/BankDetails/RecipientDetails/helpers/isCountry.ts
  src/components/BankDetails/RecipientDetails/helpers/isTextType.ts
  src/components/BankDetails/RecipientDetails/types.ts
  src/components/BankDetails/RecipientDetails/useRecipientDetails/getDefaultValues.ts
  src/components/BankDetails/RecipientDetails/useRecipientDetails/index.ts
  src/components/BankDetails/RecipientDetails/useRecipientDetails/mergeRequirements.ts
  src/components/BankDetails/RecipientDetails/useRecipientDetails/useRecipientDetails.ts
  src/components/BankDetails/RecipientDetails/useRecipientDetails/useStateReducer.ts
  src/components/BankDetails/UpdateDetailsButton.tsx
  src/components/BankDetails/index.ts
  src/components/BankDetails/types.ts
  src/components/BankDetails/useCurrencies.ts
  src/pages/Admin/Charity/Banking/Banking.tsx
  src/pages/Admin/Charity/Banking/FormButtons.tsx
  src/pages/Registration/Steps/Banking/Banking.tsx
  src/pages/Registration/Steps/Banking/FormButtons.tsx
  src/pages/Registration/Steps/Banking/useSubmit.ts
  src/services/aws/bankDetails.ts
  src/services/aws/wise.ts
  src/types/aws/ap/bankDetails.ts
Labels: bug, refactor

#2632 Closes BG-1041: A user should not be able to continue someone else's registration
  src/services/aws/registration/registration.ts
Labels: bug

#2637 Closes BG-1041: A user should not be able to continue someone else's …
  src/services/aws/registration/registration.ts
Labels: bug, duplicate

#2638 FIX: amplify button no color
  src/index.css
Labels: bug

#2639 Fixes BG-1041: Update `registration-get` endpoint
  src/services/aws/registration/registration.ts
Labels: enhancement

#2640 BG-1037: admin members
  src/components/Icon/icons.ts
  src/constants/routes.ts
  src/pages/Admin/Charity/Members/AddForm.tsx
  src/pages/Admin/Charity/Members/List.tsx
  src/pages/Admin/Charity/Members/Members.tsx
  src/pages/Admin/Charity/Members/index.ts
  src/pages/Admin/Charity/index.tsx
  src/pages/Admin/constants.ts
  src/services/aws/aws.ts
  src/services/aws/users.ts
  src/types/aws/ap/users.ts
Labels: good first issue

#2641 BG-957: SDG Groupings
  src/constants/unsdgs.ts
  src/pages/Marketplace/ActiveFilters.tsx
  src/pages/Marketplace/Cards/useCards.ts
  src/pages/Marketplace/Filter/Categories.tsx
  src/pages/Marketplace/Filter/Filter.tsx
  src/pages/Marketplace/Filter/SDGs.tsx
  src/slices/components/marketFilter/constants.ts
  src/slices/components/marketFilter/marketFilter.ts
  src/slices/components/marketFilter/types.ts
  src/types/lists.ts
Labels: design, refactor

#2642 Bg 1037: Unpushed commits
  src/components/Icon/icons.ts
  src/pages/Admin/Charity/Members/AddForm.tsx
  src/pages/Admin/Charity/Members/List.tsx
Labels: duplicate

#2650 BG-1078 remove leaderboard footer link
  lint-staged.js
  src/App/constants.ts
Labels: bug

#2652 Custom signup confirm text
  src/pages/Signin/Signin.tsx
Labels: refactor

#2651 BG-1054: reg emails endpoint
  src/helpers/registration/handleMutationResult.ts
  src/helpers/registration/index.ts
  src/pages/Application/Loaded.tsx
  src/pages/Registration/Steps/Dashboard/index.tsx
  src/services/aws/aws.ts
  src/services/aws/registration/registration.ts
Labels: enhancement

#2653 FIX: client side vaildation not running
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/Form.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
Labels: bug

#2654 remove contact emails and unused fields from types
  src/pages/Admin/Charity/EditProfile/update.ts
  src/types/aws/ap/index.ts
Labels: bug

#2658 BG-1077 Decimals adjust
  src/components/donation/Steps/Result/Success/index.tsx
Labels: bug

#2659 BG-1087 Profile title break
  src/pages/Profile/Body/Body.tsx
Labels: bug

#2660 Update PUBLIC_ENVIRONMENT env. var to 'dev | production'
  .env.example
  src/constants/env.ts
  src/constants/urls.ts
Labels: enhancement

#2663 Closes BG-956: Minor refactors + explanatory comments for PayPal flow
  src/App/App.tsx
  src/components/donation/Steps/DonateMethods/PayPal/Checkout.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Checkout.tsx
  src/services/apes/apes.ts
  src/types/aws/apes/paypal.ts
Labels: refactor

#2662 BG-1064 Marketplace card imgs
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Admin/Charity/EditProfile/types.ts
  src/pages/Admin/Charity/EditProfile/update.ts
  src/pages/Admin/Charity/EditProfile/useEditProfile.ts
  src/pages/Marketplace/Cards/Card.tsx
  src/services/aws/aws.ts
  src/types/aws/ap/index.ts
Labels: enhancement

#2666 BG-1102: Biome setup (w/ less strict config)
  .husky/pre-commit
  biome.json
  lint-staged.cjs
  package.json
  prettier.config.js
  src/components/BookmarkBtn.tsx
  src/components/FileDropzone/FileDropzone.tsx
  src/components/ImgEditor/ImgEditor.tsx
  src/components/Selector/constants.ts
  src/components/TableSection.tsx
  src/contexts/WalletContext/WalletContext.tsx
  src/contexts/WalletContext/useTerra.ts
  src/helpers/admin/getPayloadDiff.test.ts
  src/pages/Admin/Charity/Banking/PayoutMethod/Loaded.tsx
  src/pages/Admin/Charity/Widget/Configurer/Configurer.tsx
  src/pages/Donations/Filter/CurrencyDropdown.tsx
  src/pages/Gift/Claim/Form.tsx
  src/pages/Marketplace/Toolbar/Sorter.tsx
  src/pages/Registration/Steps/Reference.tsx
  yarn.lock
Labels: refactor

#2655 Towards BG-1045: add donation source
  src/components/donation/Steps/Donater/index.tsx
  src/services/apes/donations/donations.ts
  src/slices/donation/sendDonation/index.ts
  src/slices/donation/types.ts
  src/types/aws/apes/donation.ts
  src/types/lists.ts
Labels: good first issue

#2661 Towards BG-1056, Closes BG-1094: Donation state re-structure for multiple methods
  package.json
  src/components/BankDetails/BankDetails.tsx
  src/components/CurrencySelector/CurrencyOptions.tsx
  src/components/CurrencySelector/CurrencySelector.tsx
  src/components/CurrencySelector/index.ts
  src/components/CurrencySelector/types.ts
  src/components/Icon/icons.ts
  src/components/TokenField/TokenField.tsx
  src/components/donation/Steps/CurrentStep.tsx
  src/components/donation/Steps/DonateMethods/Crypto/Crypto.tsx
  src/components/donation/Steps/DonateMethods/Crypto/Form/index.tsx
  src/components/donation/Steps/DonateMethods/Crypto/constants.ts
  src/components/donation/Steps/DonateMethods/Crypto/index.ts
  src/components/donation/Steps/DonateMethods/Crypto/schema.ts
  src/components/donation/Steps/DonateMethods/Crypto/types.ts
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
  src/components/donation/Steps/DonateMethods/PayPal/Form.tsx
  src/components/donation/Steps/DonateMethods/PayPal/PayPal.tsx
  src/components/donation/Steps/DonateMethods/PayPal/index.ts
  src/components/donation/Steps/DonateMethods/PayPal/types.ts
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Stripe.tsx
  src/components/donation/Steps/DonateMethods/Stripe/index.ts
  src/components/donation/Steps/DonateMethods/Stripe/types.ts
  src/components/donation/Steps/Donater/types.ts
  src/components/donation/Steps/Result/Loading.tsx
  src/components/donation/Steps/Result/Success/index.tsx
  src/components/donation/Steps/Result/index.tsx
  src/components/donation/Steps/Submit/Crypto/Breakdown/Breakdown.tsx
  src/components/donation/Steps/Submit/Crypto/Breakdown/estimateDonation.ts
  src/components/donation/Steps/Submit/Crypto/Breakdown/index.ts
  src/components/donation/Steps/Submit/Crypto/Breakdown/tokenBalance.ts
  src/components/donation/Steps/Submit/Crypto/Container.tsx
  src/components/donation/Steps/Submit/Crypto/Crypto.tsx
  src/components/donation/Steps/Submit/Crypto/Row.tsx
  src/components/donation/Steps/Submit/Crypto/Wallet.tsx
  src/components/donation/Steps/Submit/Crypto/WalletSelection.tsx
  src/components/donation/Steps/Submit/Crypto/index.ts
  src/components/donation/Steps/Submit/Crypto/types.ts
  src/components/donation/Steps/Submit/Err.tsx
  src/components/donation/Steps/Submit/Loader.tsx
  src/components/donation/Steps/Submit/PaypalCheckout/Checkout.tsx
  src/components/donation/Steps/Submit/PaypalCheckout/PaypalCheckout.tsx
  src/components/donation/Steps/Submit/PaypalCheckout/index.ts
  src/components/donation/Steps/Submit/StripeCheckout/Checkout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/index.ts
  src/components/donation/Steps/Submit/Submit.tsx
  src/components/donation/Steps/index.tsx
  src/pages/Donate/Content.tsx
  src/pages/Donate/index.tsx
  src/services/apes/apes.ts
  src/slices/donation/donation.ts
  src/slices/donation/types.ts
  src/types/auth.ts
  src/types/components.ts
  src/types/third-party/redux.ts
Labels: design, refactor

#2670 Closes BG-1108,BG-1109: email not prefilled in paypal
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
  src/slices/donation/donation.ts
Labels: bug

#2671 Closes BG-1104: Move cancel link at the top of the page
  src/components/Icon/icons.ts
  src/components/KYCForm/Form/Controls.tsx
  src/components/KYCForm/Form/index.tsx
  src/components/donation/Steps/BackBtn.tsx
  src/components/donation/Steps/DonateMethods/Crypto/Form/index.tsx
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
  src/components/donation/Steps/DonateMethods/PayPal/Form.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/components/donation/Steps/Submit/Crypto/Container.tsx
  src/components/donation/Steps/Submit/PaypalCheckout/Checkout.tsx
  src/components/donation/Steps/Submit/PaypalCheckout/PaypalCheckout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Checkout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/components/donation/Steps/index.tsx
  src/index.html
  src/pages/Donate/Content.tsx
  src/pages/Donate/FAQ.tsx
  src/pages/Donate/OrgCard.tsx
  src/pages/Donate/index.tsx
  src/pages/DonateWidget/Content.tsx
  src/styles/components.css
Labels: design, refactor
