Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2024-02, with the labels that each got.

#2682 Fix `kyc.name` undefined error
  src/components/KYCForm/KYCForm.tsx
  src/components/KYCForm/types.ts
  src/components/donation/Steps/CurrentStep.tsx
  src/slices/donation/donation.ts
  src/slices/donation/types.ts
Labels: bug

#2683 Linting: unused variable = error
  biome.json
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
  src/components/RichText/RichText.tsx
  src/components/donation/Steps/DonateMethods/Crypto/Form/index.tsx
  src/components/donation/Steps/DonateMethods/PayPal/Form.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/components/donation/Steps/Submit/Crypto/Container.tsx
  src/components/donation/Steps/Submit/Crypto/Crypto.tsx
  src/components/donation/Steps/Submit/PaypalCheckout/PaypalCheckout.tsx
  src/contexts/WalletContext/useInjectedProvider.ts
  src/contexts/WalletContext/useKeplr/useKeplr.ts
  src/contexts/WalletContext/useTerra.ts
  src/contexts/WalletContext/wallet-connect/useKeplrWC.ts
  src/pages/Admin/Charity/Members/AddForm.tsx
  src/pages/Admin/Charity/ProgramEditor/useSubmit.ts
  src/pages/Admin/constants.ts
  src/pages/Gift/Purchase/Purchaser/index.tsx
  src/pages/Registration/SigningResult/Success.tsx
  src/services/apes/donations/usePaginatedDonations.ts
  src/services/aws/aws.ts
  src/services/aws/banking-applications.ts
  src/services/aws/wise.ts
  src/slices/widget.ts
Labels: enhancement

#2685 Closes BG-1079: Duplicate new registration
  src/pages/Registration/Welcome.tsx
  src/services/aws/aws.ts
  src/services/aws/registration/registration.ts
  src/services/aws/tags.ts
Labels: bug, refactor

#2679 Closes BG-1099: Stocks multistep
  src/components/donation/Steps/CurrentStep.tsx
  src/components/donation/Steps/DonateMethods/BuildEmailForm.tsx
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
  src/components/donation/Steps/DonateMethods/Stocks.tsx
  src/components/donation/Steps/DonateMethods/Stocks/Form.tsx
  src/components/donation/Steps/DonateMethods/Stocks/index.ts
  src/components/donation/Steps/Submit/Stocks.tsx
  src/components/donation/Steps/Submit/Submit.tsx
  src/pages/Donate/Content.tsx
  src/slices/donation/donation.ts
  src/slices/donation/types.ts
Labels: design, refactor

#2681 Closes BG-1116: Donation succesful screen
  src/assets/images/celebrating-character.png
  src/components/donation/Steps/Result/Success/Share.tsx
  src/components/donation/Steps/Result/Success/index.tsx
  src/helpers/confetti.ts
  src/pages/DonateFiatThanks.tsx
Labels: design, refactor

#2686 Increase stripe-js pkg version to 2.4.0
  package.json
  yarn.lock
Labels: enhancement

#2684 Closes BG-1107: Splits standalone step
  package.json
  src/assets/icons/leaf.png
  src/assets/icons/send-money.png
  src/components/Split/Portion.tsx
  src/components/Split/Slider.tsx
  src/components/Split/Split.tsx
  src/components/Split/index.ts
  src/components/Split/types.ts
  src/components/TokenField/TokenField.tsx
  src/components/donation/Steps/CurrentStep.tsx
  src/components/donation/Steps/DonateMethods/ChariotConnect/Form.tsx
  src/components/donation/Steps/DonateMethods/Crypto/Crypto.tsx
  src/components/donation/Steps/DonateMethods/Crypto/Form/index.tsx
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
  src/components/donation/Steps/DonateMethods/PayPal/Form.tsx
  src/components/donation/Steps/DonateMethods/PayPal/types.ts
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/components/donation/Steps/DonateMethods/Stripe/types.ts
  src/components/donation/Steps/Splits/Splits.tsx
  src/components/donation/Steps/Splits/index.ts
  src/components/donation/Steps/Submit/ChariotConnectCheckout.tsx
  src/components/donation/Steps/Submit/Crypto/Container.tsx
  src/components/donation/Steps/Submit/PaypalCheckout/PaypalCheckout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/pages/Admin/Charity/Widget/Configurer/Form.tsx
  src/slices/donation/donation.ts
  src/slices/donation/sendDonation/index.ts
  src/slices/donation/types.ts
  src/styles/components.css
  yarn.lock
Labels: design, refactor

#2689 Update Split.tsx to handle 'stocks' separately when reading amount+symbol
  src/components/donation/Steps/Splits/Splits.tsx
Labels: bug

#2687 Closes BG-1008: Donate Widget: on successful donation show the "thank you for the donation" page inside the widget
  src/App/App.tsx
  src/components/donation/Steps/Submit/ChariotConnectCheckout.tsx
  src/components/donation/Steps/Submit/Err.tsx
  src/components/donation/Steps/Submit/PaypalCheckout/Checkout.tsx
  src/components/donation/Steps/Submit/PaypalCheckout/PaypalCheckout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Checkout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/constants/routes.ts
  src/pages/DonateFiatThanks.tsx
  src/pages/DonateWidget/Content.tsx
  src/pages/StripePaymentStatus.tsx
  src/types/lists.ts
Labels: enhancement

#2700 Fix inverted splits
  src/components/donation/Steps/Splits/Splits.tsx
Labels: bug

#2688 Closes BG-1113: FAQ content
  src/pages/Donate/FAQ.tsx
Labels: enhancement

#2691 Closes BG-1067: Public page for anyone to create a nonprofit donation widget
  src/App/App.tsx
  src/constants/routes.ts
  src/index.css
  src/pages/Admin/Charity/index.tsx
  src/pages/Widget/Configurer/Configurer.tsx
  src/pages/Widget/Configurer/EndowmentSelector/EndowmentSelector.tsx
  src/pages/Widget/Configurer/EndowmentSelector/Options.tsx
  src/pages/Widget/Configurer/EndowmentSelector/index.ts
  src/pages/Widget/Configurer/Form.tsx
  src/pages/Widget/Configurer/index.ts
  src/pages/Widget/Configurer/schema.ts
  src/pages/Widget/Configurer/types.ts
  src/pages/Widget/Preview/DonateMethods/AdvancedOptions.tsx
  src/pages/Widget/Preview/DonateMethods/DAFSample.tsx
  src/pages/Widget/Preview/DonateMethods/DonateMethods.tsx
  src/pages/Widget/Preview/DonateMethods/DonaterSample.tsx
  src/pages/Widget/Preview/DonateMethods/StocksSample.tsx
  src/pages/Widget/Preview/DonateMethods/StripeSample.tsx
  src/pages/Widget/Preview/DonateMethods/index.ts
  src/pages/Widget/Preview/Preview.tsx
  src/pages/Widget/Preview/index.ts
  src/pages/Widget/Snippet/Snippet.tsx
  src/pages/Widget/Snippet/index.ts
  src/pages/Widget/Widget.tsx
  src/pages/Widget/index.ts
  src/services/aws/useEndowment.ts
  yarn.lock
Labels: enhancement

#2702 Towards BG-1121: After signing in and being redirected to Marketplace, the URL should be /marketplace and not /auth-redirect
  src/pages/OAuthRedirector.tsx
Labels: bug

#2703 Closes BG-1110: Fix breadcrumbs active link
  src/components/Breadcrumbs.tsx
  src/pages/Profile/Body/Body.tsx
Labels: bug

#2704 BG-1105 Profiles: remove banner overlay
  src/pages/Profile/index.tsx
Labels: duplicate

#2706 BG-1125 Widget: updates to copy (staging)
  src/pages/DonateWidget/Content.tsx
  src/pages/Widget/Preview/Preview.tsx
Labels: duplicate, enhancement

#2707 Closes BG-1132: Fix donation validation
  package.json
  src/components/donation/Steps/DonateMethods/ChariotConnect/Form.tsx
  src/components/donation/Steps/DonateMethods/Crypto/Crypto.tsx
  src/components/donation/Steps/DonateMethods/Crypto/schema.ts
  src/components/donation/Steps/DonateMethods/PayPal/Form.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Checkout.tsx
  src/pages/Admin/Charity/index.tsx
  src/pages/BankingApplications/Filter/index.tsx
  src/pages/BankingApplications/Filter/schema.ts
  src/pages/Widget/Widget.tsx
  src/schemas/number.ts
  src/schemas/shape.ts
Labels: bug, enhancement

#2701 Towards BG-1126: Crypto checkout updates
  src/components/Icon/icons.ts
  src/components/donation/Steps/Submit/Crypto/Breakdown/Breakdown.tsx
  src/components/donation/Steps/Submit/Crypto/Breakdown/estimateDonation.ts
  src/components/donation/Steps/Submit/Crypto/Breakdown/index.ts
  src/components/donation/Steps/Submit/Crypto/Checkout.tsx
  src/components/donation/Steps/Submit/Crypto/Container.tsx
  src/components/donation/Steps/Submit/Crypto/Crypto.tsx
  src/components/donation/Steps/Submit/Crypto/Row.tsx
  src/components/donation/Steps/Submit/Crypto/TxSubmit/TxSubmit.tsx
  src/components/donation/Steps/Submit/Crypto/TxSubmit/estimateDonation.ts
  src/components/donation/Steps/Submit/Crypto/TxSubmit/index.ts
  src/components/donation/Steps/Submit/Crypto/TxSubmit/tokenBalance.ts
  src/components/donation/Steps/Submit/Crypto/TxSubmit/txPackage.ts
  src/components/donation/Steps/Submit/Crypto/Wallet.tsx
  src/components/donation/Steps/Submit/Crypto/WalletSelection.tsx
  src/components/donation/Steps/Submit/Crypto/types.ts
  src/components/donation/Steps/index.tsx
  src/helpers/coin-gecko.ts
  src/services/coingecko.ts
  src/store/store.ts
Labels: design, refactor

#2712 Capitalize nonprofit field name
  src/pages/Registration/Steps/OrgDetails/Form/index.tsx
Labels: design

#2710 Remove unused registerOptions prop from Field.tsx
  src/components/form/Field.tsx
Labels: refactor

#2713 ref BG-1121: Increase auth redirect delay to 1000ms
  src/pages/OAuthRedirector.tsx
Labels: bug

#2709 BG-1107, BG-1126: Fiat checkout summary
  src/components/BankDetails/BankDetails.tsx
  src/components/CurrencySelector/CurrencyOptions.tsx
  src/components/donation/Steps/DonateMethods/ChariotConnect/Form.tsx
  src/components/donation/Steps/DonateMethods/PayPal/Form.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/components/donation/Steps/Splits/Splits.tsx
  src/components/donation/Steps/Submit/ChariotConnectCheckout.tsx
  src/components/donation/Steps/Submit/Crypto/Crypto.tsx
  src/components/donation/Steps/Submit/PaypalCheckout/Checkout.tsx
  src/components/donation/Steps/Submit/PaypalCheckout/PaypalCheckout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Checkout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/components/donation/Steps/Submit/common/Currrency.tsx
  src/components/donation/Steps/Submit/common/Heading.tsx
  src/components/donation/Steps/Submit/common/SplitSummary.tsx
  src/services/apes/apes.ts
  src/services/aws/wise.ts
  src/types/components.ts
Labels: good first issue

#2716 Closes BG-1069: Account Type error should appear closer to the actual component(s)
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
Labels: design

#2714 Closes BG-1095: Add links to donate terms
  src/App/constants.ts
  src/constants/env.ts
  src/pages/Donate/Content.tsx
  src/pages/Donate/FAQ.tsx
Labels: bug, enhancement

#2711 Closes BG-1111: Redesign of Header Navbar
  src/App/Header/DesktopNav.tsx
  src/App/Header/MobileNav/index.ts
  src/App/Header/NavDropdown/Menu.tsx
  src/App/Header/NavDropdown/NavDropdown.tsx
  src/App/Header/NavDropdown/index.ts
  src/App/Header/UserMenu/Menu.tsx
  src/App/Header/UserMenu/UserMenu.tsx
  src/App/Header/index.tsx
  src/App/Header/useHeaderClassNames.ts
  src/App/Layout.tsx
  src/App/__tests__/App.test.tsx
  src/App/constants.ts
  src/App/useHeaderLinks.ts
  src/assets/images/bettergiving-logo-with-name-all-blue.svg
  src/components/Image/DappLogo.tsx
  src/hooks/useHandleScreenResize.ts
  src/pages/Admin/Sidebar/SidebarOpener/useSidebarOpener.ts
  src/pages/Marketplace/index.tsx
  src/pages/Registration/Steps/ProgressIndicator.tsx
  yarn.lock
Labels: design

#2720 Closes BG-1123: Donate Widget: log the "Invalid widget config found - loaded defaults" message, don't display it
  src/contexts/ErrorContext/ErrorContext.tsx
  src/errors/ErrorHandler.tsx
  src/pages/DonateWidget/Content.tsx
  src/pages/DonateWidget/donaterConfig.ts
  src/pages/DonateWidget/parseConfig.ts
  src/types/widget.ts
Labels: design

#2721 Closes BG-1134: set Splits currency code as uppercase by default
  src/components/donation/Steps/Splits/Splits.tsx
Labels: design

#2729 Closes BG-1070: BankDetails: fields should have a red border when an error appears
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
Labels: design

#2727 Closes BG-1071: BankDetails: improve selector styles
  src/components/BankDetails/RecipientDetails/RecipientDetails.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
  src/components/Selector/NativeSelect.tsx
  src/components/Selector/index.ts
  src/components/form/Label.tsx
  src/pages/Registration/Steps/Documentation/FSA/Form/index.tsx
Labels: design

#2728 Header Navbar redesign changes v2
  src/App/App.tsx
  src/App/Header/NavDropdown.tsx
  src/App/Header/NavDropdown/Menu.tsx
  src/App/Header/NavDropdown/NavDropdown.tsx
  src/App/Header/NavDropdown/index.ts
  src/App/Header/index.tsx
  src/App/Header/useHeaderClassNames.ts
  src/contexts/Auth.tsx
  src/pages/Admin/Context.tsx
  src/pages/Admin/Layout.tsx
  src/pages/Application/Application.tsx
  src/pages/Applications/Applications.tsx
  src/pages/BankingApplication/BankingApplication.tsx
  src/pages/BankingApplications/BankingApplications.tsx
  src/pages/Donate/Content.tsx
  src/pages/Donate/index.tsx
  src/pages/DonateFiatThanks.tsx
  src/pages/Donations/index.tsx
  src/pages/Gift/index.tsx
  src/pages/Leaderboard/index.tsx
  src/pages/Profile/index.tsx
  src/pages/Registration/Steps/index.tsx
  src/pages/Registration/index.tsx
  src/pages/Signin/Signin.tsx
  src/pages/StripePaymentStatus.tsx
Labels: design

#2730 Use native Key type instead of ValKey
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
  src/components/Selector/MultiSelector.tsx
  src/pages/Registration/Steps/ContactDetails/constants.ts
  src/types/components.ts
Labels: refactor

#2732 Update all input fields to trim start & end space characters
  src/App/Footer/Newsletter/SubscriptionForm.tsx
  src/components/KYCForm/schema.ts
  src/components/donation/Steps/DonateMethods/ChariotConnect/Form.tsx
  src/components/donation/Steps/DonateMethods/PayPal/Form.tsx
  src/components/donation/Steps/DonateMethods/Stocks/Form.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/pages/Admin/Charity/Banking/PayoutMethod/Prompt.tsx
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Admin/Charity/Members/AddForm.tsx
  src/pages/Admin/Charity/ProgramEditor/schema.ts
  src/pages/Application/Prompt.tsx
  src/pages/Applications/Filter/schema.ts
  src/pages/BankingApplication/Prompt.tsx
  src/pages/BankingApplications/Prompt.tsx
  src/pages/Donations/Filter/schema.ts
  src/pages/Gift/Claim/index.tsx
  src/pages/Gift/Mailer/schema.ts
  src/pages/Registration/Resume/index.tsx
  src/pages/Registration/Steps/ContactDetails/schema.ts
  src/pages/Registration/Steps/Documentation/FSA/schema.ts
  src/pages/Registration/Steps/Documentation/NonFSA/NonFSA.tsx
  src/pages/Registration/Steps/OrgDetails/schema.ts
  src/schemas/shape.ts
  src/schemas/string.ts
Labels: enhancement

#2731 BG-1080: Update DAF donation flow to include a manual DAF donation option
  src/assets/images/chariot-logo-with-name.svg
  src/components/donation/Steps/BackBtn.tsx
  src/components/donation/Steps/DonateMethods/ChariotConnect/Form.tsx
  src/components/donation/Steps/Submit/DAFCheckout/ChariotCheckout.tsx
  src/components/donation/Steps/Submit/DAFCheckout/DAFCheckout.tsx
  src/components/donation/Steps/Submit/DAFCheckout/ManualDonation.tsx
  src/components/donation/Steps/Submit/DAFCheckout/index.ts
  src/components/donation/Steps/Submit/Stocks.tsx
  src/components/donation/Steps/Submit/Submit.tsx
  src/styles/components.css
Labels: enhancement, design

#2733 Navmenu image fix & other minor changes
  src/App/Header/UserMenu/UserMenu.tsx
  src/App/Header/index.tsx
  src/assets/images/DAFDirect.png
  src/assets/images/angelgiving-H-logo-wht.svg
  src/assets/images/bettergiving-logo-with-name-all-blue.svg
  src/assets/images/bettergiving-logo.png
  src/pages/Widget/Preview/DonateMethods/DAFSample.tsx
Labels: bug, enhancement

#2734 Remove delay from OAuthRedirector
  src/pages/OAuthRedirector.tsx
Labels: enhancement

#2742 BG-1163 Remove Chariot, only manual DAF donations for now
  src/components/donation/Steps/DonateMethods/Daf/Form.tsx
  src/components/donation/Steps/DonateMethods/Daf/index.ts
  src/components/donation/Steps/DonateMethods/Daf/types.ts
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
  src/components/donation/Steps/Submit/DAFCheckout/ChariotDonation.tsx
  src/components/donation/Steps/Submit/DAFCheckout/DAFCheckout.tsx
  src/components/donation/Steps/Submit/DAFCheckout/ManualDonation.tsx
  src/components/donation/Steps/Submit/Submit.tsx
  src/slices/donation/types.ts
Labels: enhancement

#2740 BG-1151 NavBar changes pt3
  src/App/App.tsx
  src/App/Header/index.tsx
  src/App/Header/useHeaderClassNames.ts
  src/App/Layout.tsx
  src/contexts/Auth.tsx
  src/pages/Admin/Context.tsx
  src/pages/Admin/Layout.tsx
  src/pages/Application/Application.tsx
  src/pages/Applications/Applications.tsx
  src/pages/BankingApplication/BankingApplication.tsx
  src/pages/BankingApplications/BankingApplications.tsx
  src/pages/Donate/index.tsx
  src/pages/Donations/index.tsx
  src/pages/Marketplace/index.tsx
  src/pages/Profile/index.tsx
  src/pages/Signin/Signin.tsx
  src/pages/StripePaymentStatus.tsx
Labels: bug

#2741 Towards BG-1150: Move kyc to checkout page
  biome.json
  src/components/KYCForm/Form/Tooltip.tsx
  src/components/KYCForm/Form/index.tsx
  src/components/KYCForm/KYCForm.tsx
  src/components/KYCForm/types.ts
  src/components/TokenField/TokenField.tsx
  src/components/donation/Steps/CurrentStep.tsx
  src/components/donation/Steps/DonateMethods/Crypto/Crypto.tsx
  src/components/donation/Steps/DonateMethods/Crypto/Form/index.tsx
  src/components/donation/Steps/DonateMethods/Crypto/constants.ts
  src/components/donation/Steps/DonateMethods/Daf/Form.tsx
  src/components/donation/Steps/DonateMethods/PayPal/Form.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/components/donation/Steps/Splits/Splits.tsx
  src/components/donation/Steps/Submit/Crypto/Crypto.tsx
  src/components/donation/Steps/Submit/DAFCheckout/ChariotDonation.tsx
  src/components/donation/Steps/Submit/DAFCheckout/DAFCheckout.tsx
  src/components/donation/Steps/Submit/DAFCheckout/ManualDonation.tsx
  src/components/donation/Steps/Submit/PaypalCheckout/PaypalCheckout.tsx
  src/components/donation/Steps/Submit/Stocks.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/components/donation/Steps/Submit/common/Currrency.tsx
  src/components/donation/Steps/Submit/common/Heading.tsx
  src/components/donation/Steps/Submit/types.ts
  src/components/donation/Steps/Summary/DonorForm.tsx
  src/components/donation/Steps/Summary/Summary.tsx
  src/components/donation/Steps/Summary/index.ts
  src/components/donation/Steps/common/BackBtn.tsx
  src/components/donation/Steps/common/Currrency.tsx
  src/components/donation/Steps/common/SplitSummary.tsx
  src/components/donation/Steps/common/Summary.tsx
  src/components/donation/Steps/common/Token.tsx
  src/pages/Donate/index.tsx
  src/pages/DonateWidget/Content.tsx
  src/pages/Donations/useShowKYCForm.ts
  src/services/apes/apes.ts
  src/slices/donation/donation.ts
  src/slices/donation/sendDonation/index.ts
  src/slices/donation/types.ts
  src/types/aws/apes/donation.ts
Labels: refactor

#2743 Show pending TXs from the On-Hold table as a separate table on the My Donations page
  src/pages/Donations/DonationsSection.tsx
  src/pages/Donations/Filter/index.tsx
  src/pages/Donations/index.tsx
  src/services/apes/donations/donations.ts
  src/services/apes/donations/usePaginatedDonations.ts
  src/types/aws/apes/donation.ts
Labels: enhancement

#2751 Fix bugs #2744
  src/components/RichText/RichText.tsx
  src/components/RichText/RichTextEditor.tsx
  src/components/RichText/types.ts
Labels: bug

#2744 Update RichTextEditor content parameter to always keep track of number of characters
  src/components/RichText/RichText.tsx
  src/components/RichText/RichTextEditor.tsx
  src/components/RichText/types.ts
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Admin/Charity/EditProfile/types.ts
  src/pages/Admin/Charity/EditProfile/update.ts
  src/pages/Admin/Charity/ProgramEditor/Milestones/Milestones.tsx
  src/pages/Admin/Charity/ProgramEditor/ProgramEditor.tsx
  src/pages/Admin/Charity/ProgramEditor/schema.ts
  src/pages/Admin/Charity/ProgramEditor/types.ts
  src/pages/Admin/Charity/ProgramEditor/useSubmit.ts
  src/pages/Gift/Mailer/Form.tsx
  src/pages/Gift/Mailer/index.tsx
  src/pages/Gift/Mailer/schema.ts
  src/pages/Gift/Mailer/types.ts
  src/pages/Profile/Body/GeneralInfo/GeneralInfo.tsx
  src/pages/Profile/Body/GeneralInfo/Programs.tsx
  src/pages/Profile/Body/Program/Milestones.tsx
  src/pages/Profile/Body/Program/Program.tsx
  src/schemas/shape.ts
  src/types/components.ts
Labels: bug, priority

#2752 Update RichTextEditor content parameter to always keep track of number of characters
  src/components/RichText/RichText.tsx
  src/components/RichText/RichTextEditor.tsx
  src/components/RichText/types.ts
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Admin/Charity/EditProfile/types.ts
  src/pages/Admin/Charity/EditProfile/update.ts
  src/pages/Admin/Charity/ProgramEditor/Milestones/Milestones.tsx
  src/pages/Admin/Charity/ProgramEditor/ProgramEditor.tsx
  src/pages/Admin/Charity/ProgramEditor/schema.ts
  src/pages/Admin/Charity/ProgramEditor/types.ts
  src/pages/Admin/Charity/ProgramEditor/useSubmit.ts
  src/pages/Gift/Mailer/Form.tsx
  src/pages/Gift/Mailer/index.tsx
  src/pages/Gift/Mailer/schema.ts
  src/pages/Gift/Mailer/types.ts
  src/pages/Profile/Body/GeneralInfo/GeneralInfo.tsx
  src/pages/Profile/Body/GeneralInfo/Programs.tsx
  src/pages/Profile/Body/Program/Milestones.tsx
  src/pages/Profile/Body/Program/Program.tsx
  src/schemas/shape.ts
  src/types/components.ts
Labels: bug

#2745 Closes BG-1153: Express checkout
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
  src/components/donation/Steps/DonateMethods/PayPal/Form.tsx
  src/components/donation/Steps/DonateMethods/PayPal/index.ts
  src/components/donation/Steps/DonateMethods/PayPal/types.ts
  src/components/donation/Steps/Submit/PaypalCheckout/PaypalCheckout.tsx
  src/components/donation/Steps/Submit/PaypalCheckout/index.ts
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Checkout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Paypal.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/index.ts
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/components/donation/Steps/Submit/Submit.tsx
  src/slices/donation/types.ts
Labels: refactor
