Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2024-06, with the labels that each got.

#3038 Update tsconfig
  src/types/third-party/redux.ts
  tsconfig.json
Labels: enhancement

#3039 FIX: remove placeholder nonprofit name
  src/components/donation/Steps/Result/Success/index.tsx
  src/components/donation/Steps/Share.tsx
  src/pages/DonateFiatThanks.tsx
Labels: bug, priority

#2978 BG-1336: Donate to ap wallet directly
  package.json
  src/App/App.tsx
  src/components/Copier/Copier.tsx
  src/components/Selector/MultiSelector.tsx
  src/components/TokenField/TokenOptions.tsx
  src/components/donation/Steps/Submit/Crypto/Checkout.tsx
  src/components/donation/Steps/Submit/Crypto/DirectMode.tsx
  src/components/donation/Steps/Submit/Crypto/TxSubmit/TxSubmit.tsx
  src/components/donation/Steps/Submit/Crypto/TxSubmit/estimateDonation.ts
  src/components/donation/Steps/Submit/Crypto/TxSubmit/tokenBalance.ts
  src/components/donation/Steps/Submit/Crypto/WalletSelection.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Checkout.tsx
  src/components/donation/Steps/Summary/DonorForm.tsx
  src/components/donation/Steps/common/ContinueBtn.tsx
  src/constants/chains.ts
  src/constants/routes.ts
  src/contexts/WalletContext/useInjectedProvider.ts
  src/pages/DonateThanks.tsx
  src/pages/StripePaymentStatus.tsx
  src/pages/Widget/Snippet/Snippet.tsx
  src/schemas/string.ts
  src/services/apes/apes.ts
  src/types/aws/apes/donation.ts
  src/types/aws/apes/index.ts
  src/types/chain.ts
  src/types/wallet.ts
  yarn.lock
Labels: good first issue

#3040 BG-1380: share fixes
  src/components/donation/Steps/Share.tsx
Labels: bug

#3041 Program metrics
  src/pages/Admin/Charity/ProgramEditor/ProgramInfo/ProgramInfo.tsx
  src/pages/Admin/Charity/ProgramEditor/ProgramInfo/schema.ts
  src/pages/Admin/Charity/ProgramEditor/ProgramInfo/types.ts
  src/pages/Admin/Charity/ProgramEditor/ProgramInfo/useSubmit.ts
  src/pages/Profile/Body/Program/Program.tsx
  src/types/aws/ap/index.ts
Labels: good first issue

#3049 BG-1381: Program selector in widget
  src/components/donation/Steps/DonateMethods/Crypto/Crypto.tsx
  src/components/donation/Steps/DonateMethods/Crypto/Form.tsx
  src/components/donation/Steps/DonateMethods/Crypto/constants.ts
  src/components/donation/Steps/DonateMethods/Stocks/Form.tsx
  src/components/donation/Steps/Submit/Stocks.tsx
  src/components/donation/Steps/Summary/Summary.tsx
  src/components/donation/Steps/Tip/Tip.tsx
  src/components/donation/Steps/common/ProgramSelector.tsx
  src/components/donation/Steps/common/constants.ts
  src/components/donation/Steps/index.tsx
  src/components/donation/Steps/types.ts
  src/components/donation/index.ts
  src/pages/DonateWidget/Content.tsx
  src/pages/DonateWidget/parseConfig.ts
  src/pages/Widget/Configurer/Configurer.tsx
  src/pages/Widget/Preview.tsx
  src/pages/Widget/Snippet/Snippet.tsx
  src/pages/Widget/Widget.tsx
  src/types/widget.ts
Labels: enhancement, good first issue, refactor

#3051 BG-1383 BG-1384 minor fixes
  src/components/donation/Steps/Submit/DAFCheckout/ManualDonation.tsx
  src/pages/Widget/Configurer/Configurer.tsx
Labels: bug, enhancement

#3050 BG-1382: Users unable to create programs occasionally
  src/App/App.tsx
  src/services/aws/aws.ts
  src/slices/auth.ts
  src/types/auth.ts
Labels: bug, enhancement, priority

#3052 User bookmarks
  src/App/Header/UserMenu/Bookmarks.tsx
  src/App/Header/UserMenu/EndowmentLink.tsx
  src/App/Header/UserMenu/Menu.tsx
  src/components/BookmarkBtn.tsx
  src/pages/Profile/Body/Body.tsx
  src/services/aws/aws.ts
  src/services/types.ts
  src/types/aws/ap/index.ts
Labels: bug, refactor

#3054 Header search V1
  src/App/Header/SearchDropdown.tsx
  src/App/Header/SearchField.tsx
  src/App/Header/index.tsx
  src/pages/Marketplace/ActiveFilters.tsx
  src/pages/Marketplace/Cards/index.tsx
  src/pages/Marketplace/Cards/useCards.ts
  src/pages/Marketplace/Context.tsx
  src/pages/Marketplace/Filter/Categories.tsx
  src/pages/Marketplace/Filter/Countries.tsx
  src/pages/Marketplace/Filter/Designations.tsx
  src/pages/Marketplace/Filter/Filter.tsx
  src/pages/Marketplace/Filter/KYCFilter.tsx
  src/pages/Marketplace/Filter/VerificationFilter.tsx
  src/pages/Marketplace/Toolbar/Search.tsx
  src/pages/Marketplace/Toolbar/Sorter.tsx
  src/pages/Marketplace/index.tsx
  src/slices/components/index.ts
  src/slices/components/marketFilter/constants.ts
  src/slices/components/marketFilter/index.ts
  src/slices/components/marketFilter/marketFilter.ts
  src/slices/components/marketFilter/types.ts
  src/store/store.ts
  src/types/app.ts
  src/types/routeStates.ts
Labels: good first issue, refactor

#3065 Search dropdown countries
  src/App/Header/SearchDropdown.tsx
  src/pages/Marketplace/index.tsx
  src/types/app.ts
Labels: good first issue

#3067 Add ms multiplier to periodic token refresh request
  src/App/App.tsx
Labels: bug

#3068 BG-1393: UK aid UI
  src/components/donation/Steps/Submit/Crypto/DirectMode.tsx
  src/components/donation/Steps/Submit/Crypto/TxSubmit/TxSubmit.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Checkout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/components/donation/Steps/Summary/DonorForm.tsx
  src/components/donation/Steps/Summary/Summary.tsx
  src/components/donation/Steps/common/constants.ts
  src/components/donation/Steps/index.tsx
  src/components/donation/Steps/types.ts
  src/types/aws/ap/donations.ts
  src/types/aws/apes/donation.ts
Labels: good first issue, design

#3070 Display top countries
  src/App/Header/SearchDropdown/SearchDropdown.tsx
  src/App/Header/SearchDropdown/TopCountries.tsx
  src/App/Header/SearchDropdown/index.ts
  src/services/apes/apes.ts
Labels: enhancement

#3080 new chains integrated
  src/components/donation/Steps/Submit/Crypto/TxSubmit/estimateDonation.ts
  src/components/donation/Steps/Submit/Crypto/TxSubmit/tokenBalance.ts
  src/components/donation/Steps/Submit/Crypto/TxSubmit/txPackage.ts
  src/constants/chainIds.ts
  src/constants/chains.ts
  src/contexts/WalletContext/useKeplr/useKeplr.ts
  src/contexts/WalletContext/wallet-connect/useKeplrWC.ts
  src/helpers/tx/estimateTx/estimateTx.ts
  src/helpers/tx/sendTx/sendTx.ts
  src/schemas/string.ts
  src/types/aws/apes/index.ts
  src/types/chain.ts
  src/types/lists.ts
Labels: enhancement

#3081 BG-1390: Cards v2
  src/App/Header/UserMenu/Bookmarks.tsx
  src/components/BookmarkBtn.tsx
  src/pages/Marketplace/Cards/Card.tsx
  src/services/aws/aws.ts
  src/types/aws/ap/index.ts
Labels: enhancement, design, refactor

#3069 Custom tokens UI
  biome.json
  lefthook.yml
  package.json
  src/App/Header/SearchDropdown/TopCountries.tsx
  src/components/TokenField/TokenOptions.tsx
  src/components/TokenField/TokenSearch/Options.tsx
  src/components/TokenField/TokenSearch/TokenSearch.tsx
  src/components/TokenField/TokenSearch/coins.json
  src/components/TokenField/TokenSearch/index.ts
  src/components/TokenField/TokenSearch/types.ts
  src/components/TokenField/TokenSelector.tsx
  src/components/donation/index.ts
  src/constants/chains.ts
  src/services/coingecko.ts
  src/types/chain.ts
  yarn.lock
Labels: good first issue

#3082 Chain selector
  src/components/donation/Steps/DonateMethods/Crypto/ChainSelector/ChainSelector.tsx
  src/components/donation/Steps/DonateMethods/Crypto/ChainSelector/Options.tsx
  src/components/donation/Steps/DonateMethods/Crypto/ChainSelector/index.ts
  src/components/donation/Steps/DonateMethods/Crypto/ChainSelector/types.ts
  src/components/donation/Steps/DonateMethods/Crypto/Crypto.tsx
  src/components/donation/Steps/DonateMethods/Crypto/Form.tsx
  src/components/donation/Steps/Submit/Crypto/Checkout.tsx
  src/components/donation/Steps/Submit/Crypto/Crypto.tsx
  src/components/donation/Steps/Submit/Crypto/DirectMode.tsx
  src/components/donation/Steps/Submit/Crypto/TxSubmit/TxSubmit.tsx
  src/components/donation/Steps/common/constants.ts
  src/components/donation/Steps/index.tsx
  src/components/donation/Steps/types.ts
  src/constants/chains.ts
  src/types/chain.ts
Labels: enhancement, design

#3083 Fix: incorrect crypto source
  src/components/donation/Steps/Submit/Crypto/TxSubmit/TxSubmit.tsx
Labels: bug, priority

#3084 Osmosis support added
  src/components/donation/Steps/Submit/Crypto/TxSubmit/estimateDonation.ts
  src/components/donation/Steps/Submit/Crypto/TxSubmit/tokenBalance.ts
  src/components/donation/Steps/Submit/Crypto/TxSubmit/txPackage.ts
  src/constants/chainIds.ts
  src/constants/chains.ts
  src/contexts/WalletContext/useKeplr/useKeplr.ts
  src/contexts/WalletContext/wallet-connect/useKeplrWC.ts
  src/helpers/tx/estimateTx/estimateTx.ts
  src/helpers/tx/sendTx/sendTx.ts
  src/schemas/string.ts
  src/types/aws/apes/index.ts
  src/types/chain.ts
  src/types/lists.ts
Labels: enhancement

#3087 Add coinbase extension wallet
  package.json
  public/icons/wallets/binance.png
  src/assets/icons/wallets/coinbase.png
  src/assets/icons/wallets/keplr.png
  src/assets/icons/wallets/metamask.png
  src/assets/icons/wallets/terra-extension.jpg
  src/assets/icons/wallets/trust.png
  src/assets/icons/wallets/unknown.svg
  src/assets/icons/wallets/wallet-connect.png
  src/assets/icons/wallets/xdefi.jpg
  src/assets/icons/wallets/xdefi.png
  src/contexts/WalletContext/WalletContext.tsx
  src/contexts/WalletContext/useInjectedProvider.ts
  src/contexts/WalletContext/useKeplr/useKeplr.ts
  src/contexts/WalletContext/useTerra.ts
  src/contexts/WalletContext/wallet-connect/useEVMWC.ts
  src/contexts/WalletContext/wallet-connect/useKeplrWC.ts
  src/helpers/evm/evm.ts
  src/types/wallet.ts
  yarn.lock
Labels: enhancement

#3089 In honor of field
  src/components/donation/Steps/Submit/Crypto/TxSubmit/TxSubmit.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Checkout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/components/donation/Steps/Summary/Summary.tsx
  src/components/donation/Steps/Summary/SummaryForm.tsx
  src/components/donation/Steps/index.tsx
  src/components/donation/Steps/types.ts
  src/types/aws/apes/donation.ts
Labels: good first issue

#3091 Fix token selector search and updates
  src/components/TokenField/TokenOptions.tsx
  src/components/TokenField/TokenSelector.tsx
Labels: bug, design

#3104 BG-1423: chain selector updates
  src/components/TokenField/TokenOptions.tsx
  src/components/TokenField/types.ts
  src/components/donation/Steps/DonateMethods/Crypto/ChainSelector/ChainSelector.tsx
  src/components/donation/Steps/DonateMethods/Crypto/ChainSelector/types.ts
  src/components/donation/Steps/DonateMethods/Crypto/Crypto.tsx
  src/components/donation/Steps/DonateMethods/Crypto/Form.tsx
  src/components/donation/Steps/DonateMethods/Crypto/types.ts
  src/components/donation/Steps/common/constants.ts
  src/constants/chains.ts
Labels: enhancement, refactor

#3106 Network dropdown bug fixes
  src/components/donation/Steps/DonateMethods/Crypto/ChainSelector/ChainSelector.tsx
Labels: bug

#3102 BG-1424: Improve token search
  biome.json
  src/assets/icons/token-placeholder.svg
  src/components/TokenField/TokenOptions.tsx
  src/components/TokenField/TokenSearch/Options.tsx
  src/components/TokenField/TokenSearch/TokenSearch.tsx
  src/components/TokenField/TokenSearch/coins.json
  src/components/TokenField/TokenSearch/index.ts
  src/components/TokenField/TokenSearch/types.ts
  src/components/TokenField/TokenSelector/TokenOptions.tsx
  src/components/TokenField/TokenSelector/TokenSelector.tsx
  src/components/TokenField/TokenSelector/coins/arbitrum-one.json
  src/components/TokenField/TokenSelector/coins/base.json
  src/components/TokenField/TokenSelector/coins/binance-smart-chain.json
  src/components/TokenField/TokenSelector/coins/ethereum.json
  src/components/TokenField/TokenSelector/coins/juno.json
  src/components/TokenField/TokenSelector/coins/kujira.json
  src/components/TokenField/TokenSelector/coins/optimistic-ethereum.json
  src/components/TokenField/TokenSelector/coins/osmosis.json
  src/components/TokenField/TokenSelector/coins/polygon-pos.json
  src/components/TokenField/TokenSelector/coins/stargaze.json
  src/components/TokenField/TokenSelector/coins/terra.json
  src/components/TokenField/TokenSelector/index.ts
  src/components/TokenField/TokenSelector/types.ts
  src/components/TokenField/types.ts
  src/components/donation/Steps/common/constants.ts
  src/types/aws/apes/index.ts
Labels: enhancement, refactor

#3103 Bug: wallet connection stuck at loading
  package.json
  yarn.lock
Labels: bug

#3109 Network select should focus first when all is error
  src/components/TokenField/TokenField.tsx
  src/components/TokenField/TokenSelector/TokenOptions.tsx
  src/components/TokenField/TokenSelector/TokenSelector.tsx
  src/components/TokenField/types.ts
  src/components/donation/Steps/DonateMethods/Crypto/ChainSelector/ChainSelector.tsx
  src/components/donation/Steps/DonateMethods/Crypto/ChainSelector/Options.tsx
  src/components/donation/Steps/DonateMethods/Crypto/ChainSelector/index.ts
  src/components/donation/Steps/DonateMethods/Crypto/ChainSelector/types.ts
  src/components/donation/Steps/DonateMethods/Crypto/Crypto.tsx
  src/components/donation/Steps/DonateMethods/Crypto/Form.tsx
  src/components/donation/Steps/DonateMethods/Crypto/index.ts
  src/components/donation/Steps/DonateMethods/Crypto/types.ts
  src/components/donation/Steps/DonateMethods/Crypto/useRhf.ts
  src/pages/Gift/Purchase/Purchaser/Form/index.tsx
Labels: bug, enhancement, refactor

#3108 Donate crash + cherry pick from master
  src/App/App.tsx
  src/components/donation/Steps/Result/Success/index.tsx
  src/components/donation/Steps/Share.tsx
  src/components/donation/Steps/Submit/Crypto/TxSubmit/TxSubmit.tsx
  src/components/donation/Steps/Summary/Summary.tsx
  src/components/donation/Steps/Summary/SummaryForm.tsx
  src/constants/urls.ts
  src/pages/DonateThanks.tsx
  src/services/aws/aws.ts
  src/slices/auth.ts
  src/types/auth.ts
Labels: bug, duplicate

#3110 Crypto form integration test
  src/components/donation/Steps/DonateMethods/Crypto/Form.test.tsx
  src/setupTests.ts
Labels: enhancement
