Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2024-09, with the labels that each got.

#3269 Remove lowecase rule
  src/pages/ResetPassword/InitForm.tsx
  src/pages/SignUp/SignupForm/SignupForm.tsx
  src/pages/Signin.tsx
Labels: refactor

#3270 Remove tx wording on eidit profile prompts
  src/pages/Admin/Charity/EditProfile/useEditProfile.ts
  src/pages/Admin/Charity/common/useUpdateEndowment.ts
Labels: bug

#3271 Search result fallback logo
  src/App/Header/SearchDropdown/SearchDropdown.tsx
  src/assets/laira/laira.ts
  src/components/donation/Steps/common/Summary.tsx
  src/content/benefits/index.ts
  src/pages/UserDashboard/Donations/NoDonations.tsx
  src/pages/Widget/Preview.tsx
  src/pages/informational/DonorInfo/BottomCta.tsx
  src/pages/informational/NonprofitInfo/BottomCta.tsx
  src/pages/informational/NonprofitInfo/DonationFormInfo.tsx
  src/pages/informational/NonprofitInfo/WhyBG.tsx
  src/pages/informational/WpPlugin.tsx
Labels: design / ux

#3283 Remove daf card order restriction
  src/components/DonateMethods/helpers.test.ts
  src/components/DonateMethods/helpers.ts
  src/pages/Admin/Charity/Settings/Form.tsx
  src/pages/Donate/Content.tsx
  src/pages/Widget/Configurer/Configurer.tsx
  src/pages/Widget/Widget.tsx
Labels: design / ux, refactor

#3285 Add incrementers in DAF form
  src/components/Signup/ConfirmForm.tsx
  src/components/donation/Steps/DonateMethods/Daf/Form.tsx
  src/components/donation/Steps/DonateMethods/Daf/useRhf.ts
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/components/donation/Steps/DonateMethods/Stripe/types.ts
  src/components/donation/Steps/DonateMethods/Stripe/useRhf.ts
  src/components/donation/Steps/common/Incrementers.tsx
  src/components/form/Form.tsx
  src/components/form/index.ts
  src/pages/Admin/Charity/Media/VideoEditor.tsx
  src/pages/Admin/Charity/ProgramEditor/Milestone/Milestone.tsx
  src/pages/Admin/Charity/ProgramEditor/ProgramInfo/ProgramInfo.tsx
  src/pages/Admin/Charity/Settings/Form.tsx
  src/pages/Widget/Configurer/Configurer.tsx
Labels: design / ux, refactor

#3286 Fix rich text editor unwanted styles appearing
  public/scripts/complydog-sans-quill.min.js
  public/scripts/cookie-consent-notice.js
  public/scripts/cookie-consent.js
  src/components/Seo.tsx
  src/index.html
Labels: bug

#3297 remove fsa in faq
  src/pages/Donate/FAQ.tsx
Labels: content

#3298 Post signup to hubspot
  src/components/Signup/SignupForm.tsx
  src/pages/SignUp/SignupForm/SignupForm.tsx
  src/pages/SignUp/SignupForm/UserTypeSelector.tsx
  src/pages/SignUp/types.ts
  src/services/aws/hubspot.ts
Labels: good first issue

#3309 Processing fee calculation
  src/components/donation/Steps/Summary/helpers.ts
Labels: bug

#3310 Processing fee flat
  src/components/donation/Steps/Summary/helpers.ts
Labels: bug

#3311 Apply processing fee to whole amount
  src/components/donation/Steps/Summary/Summary.tsx
  src/components/donation/Steps/Summary/helpers.ts
Labels: bug

#3313 Chariot: processing fee
  src/components/donation/Steps/Submit/DAFCheckout/ChariotCheckout.tsx
  src/components/donation/Steps/Summary/Summary.tsx
  src/components/donation/Steps/common/min-fee-allowance.ts
Labels: bug

#3314 Add usd value crypto
  src/components/TokenField/TokenField.tsx
Labels: design / ux

#3315 Incrementers crypto
  src/components/donation/Steps/DonateMethods/Crypto/Form.tsx
  src/components/donation/Steps/DonateMethods/Crypto/useRhf.ts
  src/components/donation/Steps/DonateMethods/Stripe/Form.test.tsx
  src/components/donation/Steps/DonateMethods/Stripe/useRhf.ts
  src/components/donation/Steps/common/Incrementers.tsx
Labels: good first issue, design / ux

#3316 Program name in donation records
  src/components/donation/Steps/Submit/Crypto/DirectMode.tsx
  src/components/donation/Steps/Submit/DAFCheckout/ChariotCheckout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Checkout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/pages/Admin/Charity/Donations/DonationsTable.tsx
  src/pages/Admin/Charity/Donations/Row.tsx
  src/pages/Admin/Charity/Donations/Table.tsx
  src/pages/UserDashboard/Donations/MobileTable.tsx
  src/pages/UserDashboard/Donations/Table.tsx
  src/services/aws/aws.ts
  src/types/aws/ap/donations.ts
  src/types/aws/apes/donation.ts
Labels: good first issue

#3328 Stripe fee update
  src/constants/common.ts
Labels: bug

#3330 Bg 1597
  src/components/donation/Steps/Tip/Tip.tsx
  src/pages/Admin/Charity/Settings/HideBGTipCheckbox.tsx
Labels: content

#3333 Use doc proxy prod alias
  src/pages/Registration/SigningResult/Success.tsx
Labels: enhancement

#3334 Fix to accept setup intent
  src/components/donation/Steps/Submit/StripeCheckout/Checkout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.test.tsx
  src/pages/StripePaymentStatus.tsx
Labels: bug
