Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2024-04, with the labels that each got.

#2828 Dynamically set payment frequency for Stripe subscriptions
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
Labels: bug

#2829 FIX: can't set default approved banking -details (#2630)
  src/pages/Admin/Charity/Banking/PayoutMethod/Loaded.tsx
Labels: bug, duplicate

#2830 BG-1196: Consolidate "My Donations" table functionality to single set of controls that act upon both tables
  src/components/QueryLoader.tsx
  src/pages/Donations/DonationsSection.tsx
  src/pages/Donations/MobileTable.tsx
  src/pages/Donations/NoDonations.tsx
  src/pages/Donations/StatusTabs.tsx
  src/pages/Donations/Table.tsx
  src/pages/Donations/index.tsx
  src/services/apes/donations/usePaginatedDonations.ts
  src/types/aws/apes/donation.ts
Labels: enhancement, design

#2822 Endowment claiming
  src/App/Header/UserMenu/UserMenu.tsx
  src/contexts/Auth.tsx
  src/helpers/determineAuthRedirectPath.ts
  src/pages/Application/Loaded.tsx
  src/pages/Applications/Table.tsx
  src/pages/OAuthRedirector.tsx
  src/pages/Profile/Body/Body.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/DetailsColumn.tsx
  src/pages/Profile/Body/GeneralInfo/GeneralInfo.tsx
  src/pages/Registration/Steps/ContactDetails/index.tsx
  src/pages/Registration/Steps/Documentation/NonFSA/NonFSA.tsx
  src/pages/Registration/Steps/Documentation/NonFSA/types.ts
  src/pages/Registration/Steps/Documentation/NonFSA/useSubmit.ts
  src/pages/Registration/Steps/FSAInquiry/FSAInquiry.tsx
  src/pages/Registration/Steps/OrgDetails/Form/index.tsx
  src/pages/Registration/Steps/OrgDetails/index.tsx
  src/pages/Registration/Steps/getRegistrationState.ts
  src/pages/Registration/Steps/index.tsx
  src/pages/Registration/Welcome.tsx
  src/pages/Registration/types.ts
  src/pages/SignUp/SignupForm/SignupForm.tsx
  src/pages/SignUp/Success.tsx
  src/pages/Signin.tsx
  src/services/aws/aws.ts
  src/services/aws/registration/registration.ts
  src/types/auth.ts
  src/types/aws/ap/index.ts
  src/types/aws/ap/registration.ts
  src/types/routeStates.ts
Labels: good first issue

#2833 FB - Unclaimed Nonprofits
  src/App/Header/UserMenu/UserMenu.tsx
  src/components/Icon/icons.ts
  src/components/Tooltip.tsx
  src/components/VerifiedIcon.tsx
  src/contexts/Auth.tsx
  src/helpers/determineAuthRedirectPath.ts
  src/pages/Application/Loaded.tsx
  src/pages/Applications/Table.tsx
  src/pages/Donate/Content.tsx
  src/pages/Donate/OrgCard.tsx
  src/pages/Marketplace/ActiveFilters.tsx
  src/pages/Marketplace/Cards/Card.tsx
  src/pages/Marketplace/Cards/useCards.ts
  src/pages/Marketplace/Filter/Filter.tsx
  src/pages/Marketplace/Filter/VerificationFilter.tsx
  src/pages/OAuthRedirector.tsx
  src/pages/Profile/Body/Body.tsx
  src/pages/Profile/Body/GeneralInfo/DetailsColumn/DetailsColumn.tsx
  src/pages/Profile/Body/GeneralInfo/GeneralInfo.tsx
  src/pages/Registration/Steps/ContactDetails/index.tsx
  src/pages/Registration/Steps/Documentation/NonFSA/NonFSA.tsx
  src/pages/Registration/Steps/Documentation/NonFSA/types.ts
  src/pages/Registration/Steps/Documentation/NonFSA/useSubmit.ts
  src/pages/Registration/Steps/FSAInquiry/FSAInquiry.tsx
  src/pages/Registration/Steps/OrgDetails/Form/index.tsx
  src/pages/Registration/Steps/OrgDetails/index.tsx
  src/pages/Registration/Steps/getRegistrationState.ts
  src/pages/Registration/Steps/index.tsx
  src/pages/Registration/Welcome.tsx
  src/pages/Registration/types.ts
  src/pages/SignUp/SignupForm/SignupForm.tsx
  src/pages/SignUp/Success.tsx
  src/pages/Signin.tsx
  src/pages/Widget/Configurer/EndowmentSelector/Options.tsx
  src/services/aws/aws.ts
  src/services/aws/registration/registration.ts
  src/slices/components/marketFilter/constants.ts
  src/slices/components/marketFilter/marketFilter.ts
  src/slices/components/marketFilter/types.ts
  src/types/auth.ts
  src/types/aws/ap/index.ts
  src/types/aws/ap/registration.ts
  src/types/aws/common.ts
  src/types/routeStates.ts
Labels: feature-branch

#2835 Closes BG-1234: searches both verified/unverified
  src/pages/Marketplace/Cards/useCards.ts
Labels: bug

#2836 Bump endpoint version for S3 file uploader to use `v2`
  src/helpers/uploadFiles.test.ts
  src/helpers/uploadFiles.ts
Labels: enhancement

#2837 BG-1233: My Donations: Minor UI tweaks
  src/pages/Donations/StatusTabs.tsx
  src/pages/Donations/index.tsx
Labels: design

#2839 BG-1213: URI validation bug: should encode all URIs before submitting to AWS to be RFC-compliant
  src/helpers/uploadFiles.ts
Labels: bug

#2838 BG-1210: DonateWidget/DonateFiatThanks: the page jitters after the confetti animation completes
  src/helpers/confetti.ts
  src/pages/DonateFiatThanks.tsx
Labels: bug, design

#2841 BG-1224 Logo updates
  public/images/angelprotocol-H-logo-wht.svg
  src/assets/favicon.png
  src/assets/images/bettergiving-logo.png
  src/assets/images/bettergiving-logo.svg
  src/assets/images/chariot-logo-with-name.svg
  src/components/Image/DappLogo.tsx
  src/components/donation/Steps/Tip/Tip.tsx
Labels: bug, good first issue

#2840 Fix: hide express checkout OrSeparator when subscription
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
Labels: bug

#2843 BG-1238: Remove Receipt column for Pending donations
  src/components/TableSection.tsx
  src/pages/Donations/MobileTable.tsx
  src/pages/Donations/Table.tsx
  src/pages/Donations/index.tsx
  src/pages/Donations/types.ts
Labels: enhancement

#2844 Quickfix for PR #2840: Remove accidental comment display from UI
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
Labels: bug, design

#2845 BG-1187: ProgramEditor: after submitting, the user should be navigated back to Programs page
  src/pages/Admin/Charity/ProgramEditor/useSubmit.ts
Labels: enhancement

#2842 Closes BG-1237: Edit profile, profile link update
  src/pages/Admin/Charity/EditProfile/Form.tsx
Labels: refactor

#2847 BG-1246: Programs: show some loading indicator when deleting a program and disable said program
  src/pages/Admin/Charity/Programs/Program.tsx
Labels: design

#2846 BG-1244: Donate: remove "more options" button from DonateMethods
  src/components/donation/Steps/DonateMethods/DonateMethods.tsx
Labels: design

#2848 Closes BG-1254: ACH routing number invalid
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/useRecipientDetailsForm/createFieldSchema.ts
Labels: bug, priority

#2851 Widget footer logo update
  src/assets/images/bettergiving-logo-white.png
  src/components/Image/DappLogo.tsx
  src/pages/DonateWidget/DonateWidget.tsx
  src/pages/Widget/Preview.tsx
Labels: design

#2850 Required not working
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
Labels: bug

#2854 BG-1082: enable `useExhaustiveDependencies` and fix warnings
  biome.json
  src/components/IFrame.tsx
  src/components/RichText/RichText.tsx
  src/contexts/ErrorContext/ErrorContext.tsx
  src/contexts/WalletContext/useInjectedProvider.ts
  src/contexts/WalletContext/wallet-connect/useEVMWC.ts
  src/contexts/WalletContext/wallet-connect/useKeplrWC.ts
  src/hooks/useHandleScreenResize.ts
  src/hooks/useScrollTop.ts
  src/hooks/useSort.ts
  src/pages/Registration/Steps/StepGuard.tsx
  src/pages/Widget/Widget.tsx
Labels: enhancement, refactor

#2852 Cherry pick wise validation via proxy
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
Labels: duplicate

#2855 Delete IFrame as it's unused
  src/components/IFrame.tsx
Labels: refactor

#2863 BG-1256 Environ adaptable WP API URLs
  src/constants/urls.ts
Labels: enhancement

#2853 Reflect donations endpoint changes
  src/pages/Admin/Charity/Donations/DonationsTable.tsx
  src/pages/Admin/Charity/Donations/Table.tsx
  src/pages/Donations/Filter/NetworkDropdown.tsx
  src/pages/Donations/Filter/index.tsx
  src/pages/Donations/MobileTable.tsx
  src/pages/Donations/NoDonations.tsx
  src/pages/Donations/StatusTabs.tsx
  src/pages/Donations/Table.tsx
  src/pages/Donations/index.tsx
  src/pages/Donations/types.ts
  src/services/apes/donations/donations.ts
  src/services/apes/donations/index.ts
  src/services/apes/tags.ts
  src/services/aws/aws.ts
  src/services/aws/usePaginatedDonations.ts
  src/slices/donation/sendDonation/index.ts
  src/types/aws/ap/donations.ts
  src/types/aws/apes/donation.ts
  src/types/aws/index.ts
Labels: bug, enhancement

#2864 hide paypal & OR separator if the env var is the empty default
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Paypal.tsx
Labels: bug

#2865 Avoid layout shift
  src/App/Header/index.tsx
  src/App/Header/useHeaderClassNames.ts
  src/App/Layout.tsx
  src/index.html
  src/pages/Donate/index.tsx
Labels: bug, enhancement

#2866 Closes BG-1247: Use final usd in nonprofit donation records
  src/pages/Admin/Charity/Donations/DonationsTable.tsx
  src/pages/Admin/Charity/Donations/Row.tsx
  src/pages/Admin/Charity/Donations/Table.tsx
Labels: enhancement, refactor

#2867 Follow up fix to reimplemented donations query
  src/services/aws/usePaginatedDonations.ts
Labels: bug

#2871 BG-1278 Fix WP URL
  src/constants/urls.ts
Labels: bug, priority

#2869 BG-1225: Donation success page: Show the name of the nonprofit donor chose
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Checkout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Paypal.tsx
  src/pages/DonateFiatThanks.tsx
  src/pages/StripePaymentStatus.tsx
  src/services/apes/apes.ts
Labels: enhancement

#2873 Donate page: Create PayPal order (donation intent) only on button click
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Checkout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Paypal.tsx
  src/services/apes/apes.ts
Labels: enhancement

#2870 UI Error handling
  src/App/Footer/Newsletter/SubscriptionForm.tsx
  src/App/Layout.tsx
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
  src/components/BookmarkBtn.tsx
  src/components/ImgEditor/useImgEditor.ts
  src/components/Prompt/TxPrompt.tsx
  src/components/Signup/ConfirmForm.tsx
  src/components/Signup/SignupForm.tsx
  src/components/donation/Steps/Submit/Err.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Checkout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Checkout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Paypal.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/constants/common.ts
  src/contexts/ErrorContext/ErrorContext.tsx
  src/contexts/ErrorContext/index.ts
  src/errors/DefaultFallback.tsx
  src/errors/ErrorBoundary.tsx
  src/errors/ErrorHandler.tsx
  src/errors/ErrorTrigger.tsx
  src/errors/errors.ts
  src/pages/Admin/Charity/Banking/Banking.tsx
  src/pages/Admin/Charity/Banking/PayoutMethod/DeletePrompt.tsx
  src/pages/Admin/Charity/Banking/PayoutMethod/Prompt.tsx
  src/pages/Admin/Charity/EditProfile/useEditProfile.ts
  src/pages/Admin/Charity/Members/AddForm.tsx
  src/pages/Admin/Charity/ProgramEditor/useSubmit.ts
  src/pages/Admin/Charity/Programs/Program.tsx
  src/pages/Admin/Charity/common/useUpdateEndowment.ts
  src/pages/Application/Prompt.tsx
  src/pages/BankingApplication/Prompt.tsx
  src/pages/BankingApplications/Prompt.tsx
  src/pages/DonateWidget/Content.tsx
  src/pages/DonateWidget/DonateWidget.tsx
  src/pages/DonateWidget/parseConfig.ts
  src/pages/Donations/useShowKYCForm.ts
  src/pages/Gift/Claim/Form.tsx
  src/pages/Gift/Mailer/Form.tsx
  src/pages/Registration/Resume/useSubmit.ts
  src/pages/Registration/SigningResult/ErrorPage.tsx
  src/pages/Registration/Steps/Banking/useSubmit.ts
  src/pages/Registration/Steps/ContactDetails/Form/useSubmit.ts
  src/pages/Registration/Steps/Dashboard/index.tsx
  src/pages/Registration/Steps/Documentation/FSA/Form/useSubmit.ts
  src/pages/Registration/Steps/Documentation/NonFSA/useSubmit.ts
  src/pages/Registration/Steps/FSAInquiry/useSubmit.ts
  src/pages/Registration/Steps/OrgDetails/Form/useSubmit.ts
  src/pages/ResetPassword/InitForm.tsx
  src/pages/ResetPassword/SetPasswordForm.tsx
  src/pages/SignUp/ConfirmForm.tsx
  src/pages/SignUp/SignupForm/SignupForm.tsx
  src/pages/Signin.tsx
  src/slices/donation/sendDonation/index.ts
Labels: bug, enhancement

#2872 Slug preview
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/EditProfile/Slug.tsx
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Admin/Charity/EditProfile/useEditProfile.ts
Labels: enhancement

#2874 Incorrect card sizes
  src/pages/Blog/Post.tsx
  src/pages/Blog/Posts.tsx
Labels: design

#2875 Remove `usdRate` from fiat donation payload and update PayPal proxy endpoint
  src/components/donation/Steps/Submit/StripeCheckout/Paypal/Checkout.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
  src/services/apes/apes.ts
Labels: enhancement

#2876 BG-1289 Widget word replaced
  src/pages/Widget/Preview.tsx
  src/pages/Widget/Widget.tsx
Labels: good first issue

#2877 BG-1281: master fixes
  src/constants/urls.ts
  src/pages/Donate/Content.tsx
  src/services/aws/usePaginatedDonations.ts
Labels: duplicate

#2878 Include tip amount to crypto donation
  src/components/donation/Steps/Submit/Crypto/TxSubmit/TxSubmit.tsx
  src/components/donation/Steps/Submit/Crypto/TxSubmit/estimateDonation.ts
Labels: bug

#2879 Default currency
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/services/apes/apes.ts
  src/types/aws/apes/donation.ts
Labels: enhancement

#2880 BG-1239: Improve / Expand pending donation information
  src/pages/Donations/Filter/NetworkDropdown.tsx
  src/pages/Donations/Table.tsx
  src/types/aws/ap/donations.ts
Labels: enhancement

#2868 Add third tab in the Donor's "My Donations" page that would allow them to see all payment intents explicitly
  src/pages/Donations/StatusTabs.tsx
  src/types/aws/ap/donations.ts
Labels: enhancement

#2891 BG-1295: Donation increment buttons
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/components/donation/Steps/DonateMethods/Stripe/Incrementers.tsx
Labels: enhancement, design

#2893 Set selected currency in cookie
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/constants/urls.ts
Labels: enhancement

#2896 Get/set cookie in client
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/helpers/cookie.ts
  src/services/apes/apes.ts
Labels: bug

#2898 Temp hide bookmark btn
  src/pages/Profile/Body/Body.tsx
Labels: bug

#2892 BG-1286: compound SF opt-in
  src/pages/Admin/Charity/EditProfile/update.ts
  src/pages/Admin/Charity/Settings/Form.tsx
  src/pages/Admin/Charity/Settings/ReceiptMsg.tsx
  src/pages/Admin/Charity/Settings/Settings.tsx
  src/pages/Admin/Charity/Settings/types.ts
  src/types/aws/ap/index.ts
Labels: good first issue

#2897 BG-1298: fix img editor issues
  src/components/ImgEditor/ImgCropper.tsx
  src/components/ImgEditor/ImgEditor.tsx
  src/components/ImgEditor/types.ts
  src/components/ImgEditor/useImgEditor.ts
  src/contexts/ModalContext.tsx
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Admin/Charity/ProgramEditor/schema.ts
Labels: bug

#2901 Follow up fixes
  src/App/Header/NavDropdown.tsx
  src/App/__tests__/App.test.tsx
  src/components/landing/AnimatedSVG.jsx
  src/components/landing/BenefitsCarousel.jsx
  src/components/landing/BlogCard.jsx
  src/components/landing/Card.jsx
  src/components/landing/Carousel.jsx
  src/components/landing/Comments.jsx
  src/components/landing/DateFormatter.jsx
  src/components/landing/Footer.jsx
  src/components/landing/HeroBottom.jsx
  src/components/landing/MakeAdmin.jsx
  src/components/landing/Menu.jsx
  src/components/landing/MenuCategories.jsx
  src/components/landing/MenuPosts.jsx
  src/components/landing/Navbar.jsx
  src/components/landing/StepsCard.jsx
  src/components/landing/TabletAnimation.jsx
  src/components/landing/Testimonials.jsx
  src/constants/useGetTestimonials.js
  src/constants/useGetUser.js
  src/pages/Home/Homepage/Home.jsx
  src/pages/Home/sections/Home/Benefits.jsx
  src/pages/Home/sections/Home/Blogs.jsx
  src/pages/Home/sections/Home/Hero.jsx
  src/pages/Home/sections/Home/Path.jsx
  src/pages/Home/sections/Home/Testimonials.jsx
  src/pages/Home/sections/Home/Video.jsx
  src/pages/Home/state/PageState.jsx
  src/pages/Home/state/UserState.jsx
Labels: bug

#2899 Landing page fixes
  src/App/App.tsx
  src/App/Header/NavDropdown.tsx
  src/App/__tests__/App.test.tsx
  src/assets/landing/heartOfText.png
  src/components/landing/AdminNavbar.jsx
  src/components/landing/AnimatedSVG.jsx
  src/components/landing/BenefitsCarousel.jsx
  src/components/landing/BenefitssCrousal.jsx
  src/components/landing/BlogCard.jsx
  src/components/landing/Button.jsx
  src/components/landing/CRUDButtons.jsx
  src/components/landing/Card.jsx
  src/components/landing/Carousel.jsx
  src/components/landing/Comments.jsx
  src/components/landing/Crousal.jsx
  src/components/landing/DateFormatter.jsx
  src/components/landing/Footer.jsx
  src/components/landing/HeroBottom.jsx
  src/components/landing/JoinUsBanner.jsx
  src/components/landing/MakeAdmin.jsx
  src/components/landing/Menu.jsx
  src/components/landing/MenuCategories.jsx
  src/components/landing/MenuPosts.jsx
  src/components/landing/MobileAnimation.jsx
  src/components/landing/Navbar.jsx
  src/components/landing/NewNavbar.jsx
  src/components/landing/StepsCard.jsx
  src/components/landing/TabletAnimation.jsx
  src/components/landing/TestimonialCard.jsx
  src/components/landing/Testimonials.jsx
  src/constants/env.ts
  src/constants/useGetBlogs.js
  src/constants/useGetTestimonials.js
  src/constants/useGetUser.js
  src/pages/Home/App.css
  src/pages/Home/Homepage/Home.jsx
  src/pages/Home/index.ts
  src/pages/Home/sections/Home/Animation.jsx
  src/pages/Home/sections/Home/Benefits.jsx
  src/pages/Home/sections/Home/Blogs.jsx
  src/pages/Home/sections/Home/Brands.jsx
  src/pages/Home/sections/Home/Hero.jsx
  src/pages/Home/sections/Home/Path.jsx
  src/pages/Home/sections/Home/Testimonials.jsx
  src/pages/Home/sections/Home/Video.jsx
  src/pages/Home/state/PageState.js
  src/pages/Home/state/PageState.jsx
  src/pages/Home/state/UserState.js
  src/pages/Home/state/UserState.jsx
  src/styles/landing/benefitsCarousel.css
  src/styles/landing/carousel.css
  src/styles/landing/crousal.css
Labels: bug, help wanted

#2902 Convert common arbitrary values to built in tailwind classes
  src/components/landing/AdminNavbar.jsx
  src/components/landing/AnimatedSVG.jsx
  src/components/landing/BenefitsCarousel.jsx
  src/components/landing/BlogCard.jsx
  src/components/landing/Button.jsx
  src/components/landing/CRUDButtons.jsx
  src/components/landing/Card.jsx
  src/components/landing/Carousel.jsx
  src/components/landing/Footer.jsx
  src/components/landing/HeroBottom.jsx
  src/components/landing/JoinUsBanner.jsx
  src/components/landing/MobileAnimation.jsx
  src/components/landing/Navbar.jsx
  src/components/landing/NewNavbar.jsx
  src/components/landing/StepsCard.jsx
  src/components/landing/TabletAnimation.jsx
  src/components/landing/TestimonialCard.jsx
  src/components/landing/Testimonials.jsx
  src/pages/Admin/Charity/Banking/PayoutMethods/Table.tsx
  src/pages/Home/App.css
  src/pages/Home/sections/Home/Blogs.jsx
  src/pages/Home/sections/Home/Brands.jsx
  src/pages/Home/sections/Home/Hero.jsx
  src/pages/Home/sections/Home/Path.jsx
  src/pages/Home/sections/Home/Testimonials.jsx
  src/pages/Home/sections/Home/Video.jsx
Labels: refactor

#2903 `DAPP_URL` to `BASE_URL` fix
  src/components/Seo.tsx
  src/components/donation/Steps/Result/Success/Share.tsx
  src/components/landing/BlogCard.jsx
  src/constants/env.ts
  src/pages/Admin/Charity/Seo.tsx
  src/pages/Donate/index.tsx
  src/pages/DonateFiatThanks.tsx
  src/pages/DonateWidget/Content.tsx
  src/pages/Leaderboard/index.tsx
  src/pages/Profile/index.tsx
  src/pages/Registration/index.tsx
  src/pages/Widget/Widget.tsx
Labels: bug

#2904 To tsx
  src/components/Media.tsx
  src/components/landing/AnimatedSVG.tsx
  src/components/landing/BenefitsCarousel.tsx
  src/components/landing/BlogCard.tsx
  src/components/landing/Button.tsx
  src/components/landing/CRUDButtons.jsx
  src/components/landing/Card.tsx
  src/components/landing/Carousel.tsx
  src/components/landing/Comments.jsx
  src/components/landing/DateFormatter.jsx
  src/components/landing/Footer.tsx
  src/components/landing/HeroBottom.jsx
  src/components/landing/HeroBottom.tsx
  src/components/landing/JoinUsBanner.tsx
  src/components/landing/Menu.jsx
  src/components/landing/MenuCategories.jsx
  src/components/landing/MenuPosts.jsx
  src/components/landing/MobileAnimation.tsx
  src/components/landing/Navbar.jsx
  src/components/landing/Navbar.tsx
  src/components/landing/NewNavbar.jsx
  src/components/landing/NewNavbar.tsx
  src/components/landing/StepsCard.tsx
  src/components/landing/TabletAnimation.tsx
  src/components/landing/TestimonialCard.tsx
  src/components/landing/Testimonials.tsx
  src/constants/useGetBlogs.js
  src/constants/useGetTestimonials.ts
  src/pages/Blog/Post.tsx
  src/pages/Blog/Posts.tsx
  src/pages/Home/App.css
  src/pages/Home/Homepage/Home.tsx
  src/pages/Home/sections/Home/Animation.tsx
  src/pages/Home/sections/Home/Benefits.jsx
  src/pages/Home/sections/Home/Blogs.jsx
  src/pages/Home/sections/Home/Blogs.tsx
  src/pages/Home/sections/Home/Brands.jsx
  src/pages/Home/sections/Home/Brands.tsx
  src/pages/Home/sections/Home/Hero.tsx
  src/pages/Home/sections/Home/Path.tsx
  src/pages/Home/sections/Home/Testimonials.tsx
  src/pages/Home/sections/Home/Video.tsx
  src/pages/Home/state/PageState.jsx
  src/pages/Home/state/UserState.jsx
  tailwind.config.js
Labels: refactor

#2905 redirect signins to marketplace, not to root
  src/helpers/determineAuthRedirectPath.ts
Labels: bug

#2915 temp hide landing page btns
  src/pages/Home/sections/Home/Path.tsx
  src/pages/Home/sections/Home/Video.tsx
Labels: bug

#2917 Static pages for legal
  src/App/App.tsx
  src/components/landing/Footer.tsx
  src/constants/routes.ts
  src/constants/urls.ts
  src/pages/Legal/PrivacyPolicy.tsx
  src/pages/Legal/TermsDonors.tsx
  src/pages/Legal/TermsNonprofits.tsx
Labels: bug, enhancement

#2916 Home groupings
  src/components/landing/JoinUsBanner.tsx
  src/components/landing/Testimonials.tsx
  src/pages/Home/Animation/AnimatedSVG.tsx
  src/pages/Home/Animation/Animation.tsx
  src/pages/Home/Animation/MobileAnimation.tsx
  src/pages/Home/Animation/StepsCard.tsx
  src/pages/Home/Animation/TabletAnimation.tsx
  src/pages/Home/Animation/index.ts
  src/pages/Home/Benefits/BenefitsCarousel.tsx
  src/pages/Home/Benefits/Carousel.tsx
  src/pages/Home/Benefits/Path.tsx
  src/pages/Home/Benefits/index.ts
  src/pages/Home/Blogs/BlogCard.tsx
  src/pages/Home/Blogs/Blogs.tsx
  src/pages/Home/Blogs/index.ts
  src/pages/Home/Brands.tsx
  src/pages/Home/Footer.tsx
  src/pages/Home/Hero/Hero.tsx
  src/pages/Home/Hero/Navbar.tsx
  src/pages/Home/Hero/index.ts
  src/pages/Home/HeroBottom/Card.tsx
  src/pages/Home/HeroBottom/HeroBottom.tsx
  src/pages/Home/HeroBottom/index.ts
  src/pages/Home/Home.tsx
  src/pages/Home/NewNavbar.tsx
  src/pages/Home/Testimonials/TestimonialCard.tsx
  src/pages/Home/Testimonials/Testimonials.tsx
  src/pages/Home/Testimonials/index.ts
  src/pages/Home/Testimonials/useGetTestimonials.ts
  src/pages/Home/Video.tsx
  src/pages/Home/common/Button.tsx
  src/pages/Home/image/Ellipse 32.png
  src/pages/Home/image/Inifnite Half-right.jpg
  src/pages/Home/image/Inifnite Half-right.png
  src/pages/Home/image/half1.jpg
  src/pages/Home/image/half1.png
  src/pages/Home/index.ts
  src/pages/Home/sections/Home/Animation.tsx
Labels: refactor

#2919 Scope custom classes, remove unused
  src/index.css
  src/pages/Home/Animation/AnimatedSVG.tsx
  src/pages/Home/Animation/MobileAnimation.tsx
  src/pages/Home/Animation/TabletAnimation.tsx
  src/pages/Home/Animation/mobile.module.css
  src/pages/Home/Animation/tablet.module.css
  src/pages/Home/App.css
  src/pages/Home/Benefits/BenefitsCarousel.tsx
  src/pages/Home/Benefits/Carousel.tsx
  src/pages/Home/Benefits/benefits.module.css
  src/pages/Home/Blogs/BlogCard.tsx
  src/pages/Home/Blogs/Blogs.tsx
  src/pages/Home/Blogs/styles.module.css
  src/pages/Home/Hero/Hero.tsx
  src/pages/Home/Hero/Navbar.tsx
  src/pages/Home/Hero/styles.module.css
  src/pages/Home/HeroBottom/HeroBottom.tsx
  src/pages/Home/HeroBottom/styles.module.css
  src/pages/Home/Home.tsx
  src/pages/Home/NewNavbar.tsx
  src/pages/Home/Testimonials/TestimonialCard.tsx
  src/pages/Home/Testimonials/Testimonials.tsx
  src/pages/Home/Testimonials/styles.module.css
  src/pages/Home/Video.tsx
  src/styles/landing/BlogPage.css
  src/styles/landing/MenuCategories.css
  src/styles/landing/MenuPosts.css
  src/styles/landing/benefitsCarousel.css
  src/styles/landing/carousel.css
  src/styles/landing/comments.css
  src/styles/landing/hero.css
  src/styles/landing/menu.css
  src/styles/landing/svgAnimation.css
  src/styles/landing/writeBlog.css
Labels: bug, refactor

#2918 Reuse layout
  src/App/App.tsx
  src/App/Footer/FooterV2.tsx
  src/App/Footer/Newsletter/Newsletter.tsx
  src/App/Footer/Newsletter/SubscriptionForm.tsx
  src/App/Footer/Socials.tsx
  src/App/Header/NavDropdown.tsx
  src/App/Header/NavbarLanding.tsx
  src/App/Header/index.tsx
  src/App/Header/useHeaderClassNames.ts
  src/App/Layout.tsx
  src/App/__tests__/App.test.tsx
  src/App/constants.ts
  src/components/Image/DappLogo.tsx
  src/pages/Home/Benefits/Carousel.tsx
  src/pages/Home/Footer.tsx
  src/pages/Home/Hero/Hero.tsx
  src/pages/Home/Hero/Navbar.tsx
  src/pages/Home/Home.tsx
Labels: bug, enhancement

#2920 BG-1291: Check token balance is greater than or equal to the total amount, not just the donation amount
  src/components/donation/Steps/Submit/Crypto/TxSubmit/estimateDonation.ts
Labels: bug

#2922 Legal pages updates
  src/pages/Legal/PrivacyPolicy.tsx
  src/pages/Legal/TermsDonors.tsx
  src/pages/Legal/TermsNonprofits.tsx
Labels: bug

#2923 Hide blemish overflow
  src/pages/Home/Benefits/Path.tsx
  src/pages/Home/HeroBottom/HeroBottom.tsx
  src/pages/Home/Video.tsx
Labels: bug, design

#2924 hidden -> clip
  src/pages/Home/Benefits/Path.tsx
  src/pages/Home/HeroBottom/HeroBottom.tsx
  src/pages/Home/Video.tsx
Labels: bug

#2926 temp removal of paypal btns from checkout
  src/components/donation/Steps/Splits/Splits.tsx
  src/components/donation/Steps/Submit/StripeCheckout/StripeCheckout.tsx
Labels: bug

#2938 Fix: donate header below main header
  src/App/Layout.tsx
  src/pages/Donate/Content.tsx
Labels: bug, priority

#2937 Update Polygon and Ethereum testnets to Amoy and Sepolia
  src/components/donation/Steps/DonateMethods/Crypto/Crypto.tsx
  src/constants/chainIds.ts
  src/constants/chains.ts
  src/pages/Gift/Purchase/Purchaser/Form/index.tsx
  src/schemas/string.ts
  src/types/chain.ts
Labels: bug, enhancement

#2939 misc hotfixes for v2.1
  src/App/Footer/FooterV2.tsx
  src/App/__tests__/App.test.tsx
  src/App/constants.ts
  src/components/donation/Steps/DonateMethods/Stripe/Form.tsx
  src/pages/Home/Benefits/Path.tsx
  src/pages/Home/Hero/Hero.tsx
  src/pages/Home/Testimonials/Testimonials.tsx
  src/pages/SignUp/SignupForm/SignupForm.tsx
  src/pages/SignUp/Success.tsx
  src/pages/Signin.tsx
Labels: bug, priority
