Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2024-12, with the labels that each got.

#3471 Registration creation onload instead onclick
  src/pages/Registration/Signup/Form.tsx
  src/pages/Registration/Welcome.tsx
  src/services/aws/registration/registration.ts
Labels: bug, enhancement

#3472 Optimistic file uploads
  package.json
  src/components/BankDetails/RecipientDetails/RecipientDetailsForm/RecipientDetailsForm.tsx
  src/components/BankDetails/types.ts
  src/components/FileDropzone/DropzoneText.tsx
  src/components/FileDropzone/FileDropzone.tsx
  src/components/FileDropzone/helpers.ts
  src/components/FileDropzone/index.ts
  src/components/FileDropzone/types.ts
  src/components/ImgEditor/ImgCropper.tsx
  src/components/ImgEditor/ImgEditor.tsx
  src/components/ImgEditor/types.ts
  src/components/ImgEditor/useImgEditor.ts
  src/helpers/uploadFile.ts
  src/pages/Admin/Charity/Banking/Banking.tsx
  src/pages/Admin/Charity/EditProfile/Form.tsx
  src/pages/Admin/Charity/EditProfile/index.tsx
  src/pages/Admin/Charity/EditProfile/schema.ts
  src/pages/Admin/Charity/EditProfile/useEditProfile.ts
  src/pages/Admin/Charity/ProgramEditor/Milestone/Milestone.tsx
  src/pages/Admin/Charity/ProgramEditor/Milestone/schema.ts
  src/pages/Admin/Charity/ProgramEditor/Milestone/types.ts
  src/pages/Admin/Charity/ProgramEditor/Milestone/useMutate.ts
  src/pages/Admin/Charity/ProgramEditor/ProgramInfo/ProgramInfo.tsx
  src/pages/Admin/Charity/ProgramEditor/ProgramInfo/schema.ts
  src/pages/Admin/Charity/ProgramEditor/ProgramInfo/types.ts
  src/pages/Admin/Charity/ProgramEditor/ProgramInfo/useSubmit.ts
  src/pages/Admin/Charity/ProgramEditor/common.ts
  src/pages/Registration/Steps/Banking/types.ts
  src/pages/Registration/Steps/Banking/useSubmit.ts
  src/pages/Registration/Steps/Documentation/Documentation.tsx
  src/pages/Registration/Steps/Documentation/FSA/Form/index.tsx
  src/pages/Registration/Steps/Documentation/FSA/Form/useSubmit.ts
  src/pages/Registration/Steps/Documentation/FSA/index.ts
  src/pages/Registration/Steps/Documentation/FSA/index.tsx
  src/pages/Registration/Steps/Documentation/FSA/schema.ts
  src/pages/Registration/Steps/Documentation/FSA/types.ts
  src/pages/UserDashboard/EditProfile/Form.tsx
  src/pages/UserDashboard/EditProfile/types.ts
  src/pages/UserDashboard/EditProfile/useRhf.ts
  src/schemas/file.ts
  src/types/components.ts
  src/types/lists.ts
  yarn.lock
Labels: enhancement, refactor

#3474 Lock period from 5 day to 1 day
  src/pages/Admin/Charity/Dashboard/monthPeriod.ts
Labels: bug

#3442 Increments update
  package.json
  src/components/Increments.tsx
  src/components/donation/Steps/common/Incrementers.tsx
  src/constants/common.ts
  src/pages/Admin/Charity/Settings/Form.tsx
  src/pages/Widget/Configurer/Configurer.tsx
  src/pages/Widget/Preview.tsx
  src/pages/Widget/Snippet/Snippet.tsx
  yarn.lock
Labels: enhancement

#3499 APES API Auth Updates
  src/pages/Admin/Context.tsx
  src/services/apes/donations.ts
Labels: enhancement
