Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2025-03, with the labels that each got.

#3576 About-2
  scripts/to-webp.sh
  src/assets/people/brylle.webp
  src/assets/people/chauncey.webp
  src/assets/people/chauncey2.webp
  src/assets/people/dianne.webp
  src/assets/people/john.webp
  src/assets/people/justin.webp
  src/assets/people/pallav.webp
  src/assets/people/shaun.webp
  src/assets/people/tejaswini.webp
  src/assets/people/tim.webp
  src/layout/app/header.tsx
  src/pages/home/header/header.tsx
  src/pages/informational/about/team.tsx
Labels: design / ux

#3579 Fundraiser to accept `slug` when editing
  package.json
  pnpm-lock.yaml
  src/.server/aws/helpers.ts
  src/.server/fund.ts
  src/api/get/endow.ts
  src/api/get/fund.ts
  src/api/schema/segment.ts
  src/pages/donate-fund/api.ts
  src/pages/funds/edit-fund/api.ts
  src/pages/funds/edit-fund/edit-fund.tsx
  src/pages/funds/edit-fund/form.tsx
  src/pages/funds/edit-fund/schema.ts
  src/pages/funds/edit-fund/slug.tsx
  src/pages/funds/edit-fund/use-rhf.ts
  src/pages/funds/fund/api.ts
Labels: enhancement, dependencies

#3582 Table display date format update
  src/helpers/date-format.ts
  src/helpers/index.ts
  src/pages/admin/banking/payout-methods/table.tsx
  src/pages/admin/dashboard/payout-history/table.tsx
  src/pages/admin/donations/row.tsx
  src/pages/applications/table.tsx
  src/pages/banking-applications/table.tsx
  src/pages/user-dashboard/donations/table.tsx
Labels: enhancement, good first issue, wip

#3585 Fix NPO settings update failure
  src/.server/aws/helpers.ts
  src/.server/aws/update-builder.test.ts
  src/.server/aws/update-builder.ts
  src/.server/fund.ts
  src/.server/npo.ts
  src/.server/user-bookmarks.ts
  src/api/donate-loader.ts
  src/pages/admin/endow-update-action.ts
  src/pages/admin/layout.tsx
  src/pages/profile/body/common/npo-id.ts
  src/pages/profile/profile-loader.ts
Labels: bug
