Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2025-02, with the labels that each got.

#3573 TGB Page
  scripts/img-fat-trim.sh
  scripts/to-webp.sh
  src/assets/images/bg-logo-leaf-bg.webp
  src/assets/images/bg-logo.webp
  src/assets/laira/laira-laptop-full.webp
  src/assets/laira/laira.ts
  src/content/benefits/sf-benefits.ts
  src/pages/landing-b/bottom-cta.tsx
  src/pages/landing-b/brands.tsx
  src/pages/landing-b/feature.tsx
  src/pages/landing-b/footer.tsx
  src/pages/landing-b/index.tsx
  src/pages/landing-b/prob-sol.tsx
  src/pages/landing-b/socials.tsx
  src/pages/landing-b/top.tsx
  vite.config.js
Labels: good first issue, design / ux

#3574 Accept custom token
  package.json
  pnpm-lock.yaml
  public/icons/currencies/karate.png
  src/.server/crypto-intent/crypto-intent.ts
  src/.server/crypto-intent/index.ts
  src/.server/crypto-intent/np.ts
  src/.server/env.ts
  src/components/donation/steps/submit/crypto/crypto.tsx
  src/components/donation/steps/submit/crypto/direct-mode.tsx
  src/components/donation/steps/submit/crypto/pay-qr.tsx
  src/components/token-field/token-selector/token-options.tsx
  src/constants/common.ts
  src/pages/user-dashboard/donations/payment-resumer.tsx
  src/routes/api.crypto-intents.$id.ts
  src/routes/api.crypto-intents.ts
  src/services/aws/mock.ts
  src/types/crypto.ts
  src/types/donations.ts
Labels: good first issue

#3575 Hot Fix - Inconsistent search results
  src/pages/home/api.ts
Labels: bug

#3577 np webhook
  package.json
  pnpm-lock.yaml
  src/.server/aws/db.ts
  src/.server/aws/ses.ts
  src/.server/crypto-intent/crypto-intent.ts
  src/.server/crypto-intent/np.ts
  src/.server/env.ts
  src/.server/sdks.ts
  src/components/token-field/token-selector/token-options.tsx
  src/routes/api.nowpayments-webhook.$stage/handlers/confirming.ts
  src/routes/api.nowpayments-webhook.$stage/handlers/expired.ts
  src/routes/api.nowpayments-webhook.$stage/handlers/failed.ts
  src/routes/api.nowpayments-webhook.$stage/handlers/settled.ts
  src/routes/api.nowpayments-webhook.$stage/handlers/waiting.ts
  src/routes/api.nowpayments-webhook.$stage/helpers.ts
  src/routes/api.nowpayments-webhook.$stage/route.ts
  src/routes/api.nowpayments-webhook.$stage/types.ts
  src/routes/api.nowpayments.$.ts
  src/services/aws/mock.ts
Labels: bug, enhancement
