Repository AngelProtocolFinance/angelprotocol-web-app, pull requests merged in 2025-04, with the labels that each got.

#3591 Add registration number in fundraiser member option
  src/pages/funds/create-fund/endowment-selector/options.tsx
  src/types/npo.ts
Labels: enhancement

#3590 Fundraisers hero
  src/pages/funds/funds.tsx
  src/pages/funds/hero.tsx
  src/pages/funds/hero.webp
  src/pages/marketplace/index.tsx
Labels: design / ux, content

#3586 Donation calculator
  package.json
  pnpm-lock.yaml
  src/helpers/to-usd.ts
  src/pages/donation-calculator/benefits.tsx
  src/pages/donation-calculator/bg-view.ts
  src/pages/donation-calculator/bottom-cta.tsx
  src/pages/donation-calculator/chart.tsx
  src/pages/donation-calculator/docs.tsx
  src/pages/donation-calculator/dollar-mask.ts
  src/pages/donation-calculator/form1.tsx
  src/pages/donation-calculator/form2.tsx
  src/pages/donation-calculator/hero.png
  src/pages/donation-calculator/hero.tsx
  src/pages/donation-calculator/index.tsx
  src/pages/donation-calculator/pct-slider.tsx
  src/pages/donation-calculator/result1.tsx
  src/pages/donation-calculator/result2.tsx
  src/pages/donation-calculator/table.tsx
  src/pages/donation-calculator/types.ts
  src/pages/donation-calculator/usd.tsx
  vite.config.js
Labels: good first issue

#3600 Update `title` tag on Better Giving pages
  src/pages/admin/layout.tsx
  src/pages/applications/index.ts
  src/pages/donate-fund/index.tsx
  src/pages/donate-fund/meta.ts
  src/pages/informational/about/team.tsx
  src/pages/reset-password/reset-password.tsx
  src/pages/user-dashboard/layout.tsx
Labels: good first issue

#3599 Cognito signup - new attribute `referral_id`
  package.json
  pnpm-lock.yaml
  src/.server/auth/cognito.ts
  src/helpers/nanoid.ts
  vite.config.js.timestamp-1744185665155-bae3f05dd298b.mjs
Labels: enhancement
